server:
  port: 9527

spring:
  aop:
    proxy-target-class: true

  messages:
    encoding: utf-8

  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 8
        max-idle: 500
        max-active: 2000
        max-wait: 10000
    timeout: 0


management:
  endpoints:
    web:
      exposure:
        include: ['httptrace', 'metrics']


lambda-framework:
  #数据源配置
  log4jdbc.enable: false
  datasource:
    jdbcUrl: jdbc:mysql://47.106.71.105:3306/lambda-mls?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true&useSSL=false
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      connection-test-query: select 1
      max-lifetime: 1800000
      connection-timeout: 30000
      pool-name: Lambda-Framework-HikariCP

lambda-portal:
  # 是否在控制台打印 SQL
  #showsql: false
  # 是否异步记录用户操作日志
  openAopLog: true

  shiro:
    # 后端免认证接口 url
    anonUrl: /login,/logout/**,/regist,/user/check/**,/swagger-ui.html,/swagger-resources/**,/webjars/**,/images/**,/v2/api-docs**,/configuration/ui,/configuration/security
    # token有效期，单位秒
    jwtTimeOut: 3600

lambda-workflow-engine:
  daemon:
    enable: true
    maxRunningJobs: 8

## table 上传文件接口
uploadFileDir: ./uploadFile/
