package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.CfAlgorithm;
import com.yatop.lambda.base.model.CfAlgorithmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfAlgorithmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_algorithm
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    long countByExample(CfAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_algorithm
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int deleteByExample(CfAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_algorithm
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int deleteByPrimaryKey(Long algorithmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_algorithm
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int insert(CfAlgorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_algorithm
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int insertSelective(CfAlgorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_algorithm
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    List<CfAlgorithm> selectByExample(CfAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_algorithm
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    CfAlgorithm selectByPrimaryKey(Long algorithmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_algorithm
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") CfAlgorithm record, @Param("example") CfAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_algorithm
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int updateByExample(@Param("record") CfAlgorithm record, @Param("example") CfAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_algorithm
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int updateByPrimaryKeySelective(CfAlgorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_algorithm
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int updateByPrimaryKey(CfAlgorithm record);
}