package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.CfCharType;
import com.yatop.lambda.base.model.CfCharTypeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfCharTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_char_type
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    long countByExample(CfCharTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_char_type
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int deleteByExample(CfCharTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_char_type
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int deleteByPrimaryKey(Integer charTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_char_type
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int insert(CfCharType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_char_type
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int insertSelective(CfCharType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_char_type
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    List<CfCharType> selectByExample(CfCharTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_char_type
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    CfCharType selectByPrimaryKey(Integer charTypeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_char_type
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int updateByExampleSelective(@Param("record") CfCharType record, @Param("example") CfCharTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_char_type
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int updateByExample(@Param("record") CfCharType record, @Param("example") CfCharTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_char_type
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int updateByPrimaryKeySelective(CfCharType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_char_type
     *
     * @mbg.generated Sat Mar 02 13:34:42 CST 2019
     */
    int updateByPrimaryKey(CfCharType record);
}