package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.CfSpecification;
import com.yatop.lambda.base.model.CfSpecificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfSpecificationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_specification
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    long countByExample(CfSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_specification
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int deleteByExample(CfSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_specification
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int deleteByPrimaryKey(String specId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_specification
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int insert(CfSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_specification
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int insertSelective(CfSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_specification
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    List<CfSpecification> selectByExample(CfSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_specification
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    CfSpecification selectByPrimaryKey(String specId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_specification
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") CfSpecification record, @Param("example") CfSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_specification
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int updateByExample(@Param("record") CfSpecification record, @Param("example") CfSpecificationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_specification
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int updateByPrimaryKeySelective(CfSpecification record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_specification
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int updateByPrimaryKey(CfSpecification record);
}