package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.CfSpecChar;
import com.yatop.lambda.base.model.CfSpecCharExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CfSpecCharMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_spec_char
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    long countByExample(CfSpecCharExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_spec_char
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int deleteByExample(CfSpecCharExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_spec_char
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int deleteByPrimaryKey(@Param("specId") String specId, @Param("charId") String charId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_spec_char
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int insert(CfSpecChar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_spec_char
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int insertSelective(CfSpecChar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_spec_char
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    List<CfSpecChar> selectByExample(CfSpecCharExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_spec_char
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    CfSpecChar selectByPrimaryKey(@Param("specId") String specId, @Param("charId") String charId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_spec_char
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int updateByExampleSelective(@Param("record") CfSpecChar record, @Param("example") CfSpecCharExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_spec_char
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int updateByExample(@Param("record") CfSpecChar record, @Param("example") CfSpecCharExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_spec_char
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int updateByPrimaryKeySelective(CfSpecChar record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_spec_char
     *
     * @mbg.generated Fri Mar 01 13:16:55 CST 2019
     */
    int updateByPrimaryKey(CfSpecChar record);
}