package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.WfCfgCharacteristic;
import com.yatop.lambda.base.model.WfCfgCharacteristicExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WfCfgCharacteristicMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_characteristic
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    long countByExample(WfCfgCharacteristicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_characteristic
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByExample(WfCfgCharacteristicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_characteristic
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByPrimaryKey(String charId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_characteristic
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insert(WfCfgCharacteristic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_characteristic
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insertSelective(WfCfgCharacteristic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_characteristic
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    List<WfCfgCharacteristic> selectByExample(WfCfgCharacteristicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_characteristic
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    WfCfgCharacteristic selectByPrimaryKey(String charId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_characteristic
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") WfCfgCharacteristic record, @Param("example") WfCfgCharacteristicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_characteristic
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExample(@Param("record") WfCfgCharacteristic record, @Param("example") WfCfgCharacteristicExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_characteristic
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKeySelective(WfCfgCharacteristic record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_characteristic
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKey(WfCfgCharacteristic record);
}