package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.WfCfgAlgorithm;
import com.yatop.lambda.base.model.WfCfgAlgorithmExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WfCfgAlgorithmMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_algorithm
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    long countByExample(WfCfgAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_algorithm
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByExample(WfCfgAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_algorithm
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByPrimaryKey(Long algorithmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_algorithm
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insert(WfCfgAlgorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_algorithm
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insertSelective(WfCfgAlgorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_algorithm
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    List<WfCfgAlgorithm> selectByExample(WfCfgAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_algorithm
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    WfCfgAlgorithm selectByPrimaryKey(Long algorithmId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_algorithm
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") WfCfgAlgorithm record, @Param("example") WfCfgAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_algorithm
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExample(@Param("record") WfCfgAlgorithm record, @Param("example") WfCfgAlgorithmExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_algorithm
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKeySelective(WfCfgAlgorithm record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_algorithm
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKey(WfCfgAlgorithm record);
}