package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.WfCfgComponent;
import com.yatop.lambda.base.model.WfCfgComponentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WfCfgComponentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_component
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    long countByExample(WfCfgComponentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_component
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByExample(WfCfgComponentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_component
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByPrimaryKey(String cmptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_component
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insert(WfCfgComponent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_component
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insertSelective(WfCfgComponent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_component
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    List<WfCfgComponent> selectByExample(WfCfgComponentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_component
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    WfCfgComponent selectByPrimaryKey(String cmptId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_component
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") WfCfgComponent record, @Param("example") WfCfgComponentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_component
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExample(@Param("record") WfCfgComponent record, @Param("example") WfCfgComponentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_component
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKeySelective(WfCfgComponent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_component
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKey(WfCfgComponent record);
}