package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.WfCfgCmptSpecRel;
import com.yatop.lambda.base.model.WfCfgCmptSpecRelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WfCfgCmptSpecRelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_cmpt_spec_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    long countByExample(WfCfgCmptSpecRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_cmpt_spec_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByExample(WfCfgCmptSpecRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_cmpt_spec_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByPrimaryKey(@Param("cmptId") String cmptId, @Param("specType") Integer specType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_cmpt_spec_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insert(WfCfgCmptSpecRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_cmpt_spec_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insertSelective(WfCfgCmptSpecRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_cmpt_spec_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    List<WfCfgCmptSpecRel> selectByExample(WfCfgCmptSpecRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_cmpt_spec_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    WfCfgCmptSpecRel selectByPrimaryKey(@Param("cmptId") String cmptId, @Param("specType") Integer specType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_cmpt_spec_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") WfCfgCmptSpecRel record, @Param("example") WfCfgCmptSpecRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_cmpt_spec_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExample(@Param("record") WfCfgCmptSpecRel record, @Param("example") WfCfgCmptSpecRelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_cmpt_spec_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKeySelective(WfCfgCmptSpecRel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_cmpt_spec_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKey(WfCfgCmptSpecRel record);
}