package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.WfCfgModulePort;
import com.yatop.lambda.base.model.WfCfgModulePortExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WfCfgModulePortMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_port
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    long countByExample(WfCfgModulePortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_port
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByExample(WfCfgModulePortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_port
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByPrimaryKey(Long portId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_port
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insert(WfCfgModulePort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_port
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insertSelective(WfCfgModulePort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_port
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    List<WfCfgModulePort> selectByExample(WfCfgModulePortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_port
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    WfCfgModulePort selectByPrimaryKey(Long portId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_port
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") WfCfgModulePort record, @Param("example") WfCfgModulePortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_port
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExample(@Param("record") WfCfgModulePort record, @Param("example") WfCfgModulePortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_port
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKeySelective(WfCfgModulePort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_port
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKey(WfCfgModulePort record);
}