package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.WfCfgModuleCatalog;
import com.yatop.lambda.base.model.WfCfgModuleCatalogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WfCfgModuleCatalogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_catalog
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    long countByExample(WfCfgModuleCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_catalog
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByExample(WfCfgModuleCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_catalog
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByPrimaryKey(Long catalogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_catalog
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insert(WfCfgModuleCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_catalog
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insertSelective(WfCfgModuleCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_catalog
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    List<WfCfgModuleCatalog> selectByExample(WfCfgModuleCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_catalog
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    WfCfgModuleCatalog selectByPrimaryKey(Long catalogId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_catalog
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") WfCfgModuleCatalog record, @Param("example") WfCfgModuleCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_catalog
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExample(@Param("record") WfCfgModuleCatalog record, @Param("example") WfCfgModuleCatalogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_catalog
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKeySelective(WfCfgModuleCatalog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_catalog
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKey(WfCfgModuleCatalog record);
}