package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.WfCfgModulePropCtrl;
import com.yatop.lambda.base.model.WfCfgModulePropCtrlExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WfCfgModulePropCtrlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    long countByExample(WfCfgModulePropCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByExample(WfCfgModulePropCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int deleteByPrimaryKey(Long controlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insert(WfCfgModulePropCtrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int insertSelective(WfCfgModulePropCtrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    List<WfCfgModulePropCtrl> selectByExample(WfCfgModulePropCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    WfCfgModulePropCtrl selectByPrimaryKey(Long controlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExampleSelective(@Param("record") WfCfgModulePropCtrl record, @Param("example") WfCfgModulePropCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByExample(@Param("record") WfCfgModulePropCtrl record, @Param("example") WfCfgModulePropCtrlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKeySelective(WfCfgModulePropCtrl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    int updateByPrimaryKey(WfCfgModulePropCtrl record);
}