package com.yatop.lambda.base.mapper;

import com.yatop.lambda.base.model.WfSnapshotParameter;
import com.yatop.lambda.base.model.WfSnapshotParameterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface WfSnapshotParameterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot_parameter
     *
     * @mbg.generated Wed Jan 02 00:41:22 CST 2019
     */
    long countByExample(WfSnapshotParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot_parameter
     *
     * @mbg.generated Wed Jan 02 00:41:22 CST 2019
     */
    int deleteByExample(WfSnapshotParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot_parameter
     *
     * @mbg.generated Wed Jan 02 00:41:22 CST 2019
     */
    int insert(WfSnapshotParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot_parameter
     *
     * @mbg.generated Wed Jan 02 00:41:22 CST 2019
     */
    int insertSelective(WfSnapshotParameter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot_parameter
     *
     * @mbg.generated Wed Jan 02 00:41:22 CST 2019
     */
    List<WfSnapshotParameter> selectByExampleWithBLOBs(WfSnapshotParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot_parameter
     *
     * @mbg.generated Wed Jan 02 00:41:22 CST 2019
     */
    List<WfSnapshotParameter> selectByExample(WfSnapshotParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot_parameter
     *
     * @mbg.generated Wed Jan 02 00:41:22 CST 2019
     */
    int updateByExampleSelective(@Param("record") WfSnapshotParameter record, @Param("example") WfSnapshotParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot_parameter
     *
     * @mbg.generated Wed Jan 02 00:41:22 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") WfSnapshotParameter record, @Param("example") WfSnapshotParameterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot_parameter
     *
     * @mbg.generated Wed Jan 02 00:41:22 CST 2019
     */
    int updateByExample(@Param("record") WfSnapshotParameter record, @Param("example") WfSnapshotParameterExample example);
}