package com.yatop.lambda.base.model;

import java.io.Serializable;
import java.util.Date;

public class CfCmptCharType implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char_type.CHAR_TYPE_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Integer charTypeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char_type.CHAR_TYPE_CODE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String charTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char_type.CHAR_TYPE_NAME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String charTypeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char_type.IS_WILDTYPE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Integer isWildtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char_type.SPEC_TYPE_MASK
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Integer specTypeMask;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char_type.CLASS_PATH
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String classPath;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char_type.DESCRIPTION
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char_type.STATUS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char_type.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char_type.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char_type.CREATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char_type.CREATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String createOper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cf_cmpt_char_type
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char_type.CHAR_TYPE_ID
     *
     * @return the value of cf_cmpt_char_type.CHAR_TYPE_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Integer getCharTypeId() {
        return charTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char_type.CHAR_TYPE_ID
     *
     * @param charTypeId the value for cf_cmpt_char_type.CHAR_TYPE_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCharTypeId(Integer charTypeId) {
        this.charTypeId = charTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char_type.CHAR_TYPE_CODE
     *
     * @return the value of cf_cmpt_char_type.CHAR_TYPE_CODE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getCharTypeCode() {
        return charTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char_type.CHAR_TYPE_CODE
     *
     * @param charTypeCode the value for cf_cmpt_char_type.CHAR_TYPE_CODE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCharTypeCode(String charTypeCode) {
        this.charTypeCode = charTypeCode == null ? null : charTypeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char_type.CHAR_TYPE_NAME
     *
     * @return the value of cf_cmpt_char_type.CHAR_TYPE_NAME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getCharTypeName() {
        return charTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char_type.CHAR_TYPE_NAME
     *
     * @param charTypeName the value for cf_cmpt_char_type.CHAR_TYPE_NAME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCharTypeName(String charTypeName) {
        this.charTypeName = charTypeName == null ? null : charTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char_type.IS_WILDTYPE
     *
     * @return the value of cf_cmpt_char_type.IS_WILDTYPE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Integer getIsWildtype() {
        return isWildtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char_type.IS_WILDTYPE
     *
     * @param isWildtype the value for cf_cmpt_char_type.IS_WILDTYPE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setIsWildtype(Integer isWildtype) {
        this.isWildtype = isWildtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char_type.SPEC_TYPE_MASK
     *
     * @return the value of cf_cmpt_char_type.SPEC_TYPE_MASK
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Integer getSpecTypeMask() {
        return specTypeMask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char_type.SPEC_TYPE_MASK
     *
     * @param specTypeMask the value for cf_cmpt_char_type.SPEC_TYPE_MASK
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setSpecTypeMask(Integer specTypeMask) {
        this.specTypeMask = specTypeMask;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char_type.CLASS_PATH
     *
     * @return the value of cf_cmpt_char_type.CLASS_PATH
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getClassPath() {
        return classPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char_type.CLASS_PATH
     *
     * @param classPath the value for cf_cmpt_char_type.CLASS_PATH
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setClassPath(String classPath) {
        this.classPath = classPath == null ? null : classPath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char_type.DESCRIPTION
     *
     * @return the value of cf_cmpt_char_type.DESCRIPTION
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char_type.DESCRIPTION
     *
     * @param description the value for cf_cmpt_char_type.DESCRIPTION
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char_type.STATUS
     *
     * @return the value of cf_cmpt_char_type.STATUS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char_type.STATUS
     *
     * @param status the value for cf_cmpt_char_type.STATUS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char_type.LAST_UPDATE_TIME
     *
     * @return the value of cf_cmpt_char_type.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char_type.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for cf_cmpt_char_type.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char_type.LAST_UPDATE_OPER
     *
     * @return the value of cf_cmpt_char_type.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char_type.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for cf_cmpt_char_type.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char_type.CREATE_TIME
     *
     * @return the value of cf_cmpt_char_type.CREATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char_type.CREATE_TIME
     *
     * @param createTime the value for cf_cmpt_char_type.CREATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char_type.CREATE_OPER
     *
     * @return the value of cf_cmpt_char_type.CREATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char_type.CREATE_OPER
     *
     * @param createOper the value for cf_cmpt_char_type.CREATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_cmpt_char_type
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CfCmptCharType other = (CfCmptCharType) that;
        return (this.getCharTypeId() == null ? other.getCharTypeId() == null : this.getCharTypeId().equals(other.getCharTypeId()))
            && (this.getCharTypeCode() == null ? other.getCharTypeCode() == null : this.getCharTypeCode().equals(other.getCharTypeCode()))
            && (this.getCharTypeName() == null ? other.getCharTypeName() == null : this.getCharTypeName().equals(other.getCharTypeName()))
            && (this.getIsWildtype() == null ? other.getIsWildtype() == null : this.getIsWildtype().equals(other.getIsWildtype()))
            && (this.getSpecTypeMask() == null ? other.getSpecTypeMask() == null : this.getSpecTypeMask().equals(other.getSpecTypeMask()))
            && (this.getClassPath() == null ? other.getClassPath() == null : this.getClassPath().equals(other.getClassPath()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_cmpt_char_type
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCharTypeId() == null) ? 0 : getCharTypeId().hashCode());
        result = prime * result + ((getCharTypeCode() == null) ? 0 : getCharTypeCode().hashCode());
        result = prime * result + ((getCharTypeName() == null) ? 0 : getCharTypeName().hashCode());
        result = prime * result + ((getIsWildtype() == null) ? 0 : getIsWildtype().hashCode());
        result = prime * result + ((getSpecTypeMask() == null) ? 0 : getSpecTypeMask().hashCode());
        result = prime * result + ((getClassPath() == null) ? 0 : getClassPath().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }
}