package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;

public class CfCmptChar extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CHAR_ID
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private String charId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CHAR_ID:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean charIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CHAR_CODE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private String charCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CHAR_CODE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean charCodeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CHAR_NAME
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private String charName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CHAR_NAME:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean charNameColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CHAR_ALIAS
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private String charAlias;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CHAR_ALIAS:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean charAliasColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.SPEC_TYPE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private Integer specType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.SPEC_TYPE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean specTypeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CHAR_TYPE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private Integer charType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CHAR_TYPE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean charTypeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.SRC_LEVEL
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private Integer srcLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.SRC_LEVEL:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean srcLevelColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.ALLOW_GLOBAL
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private Integer allowGlobal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.ALLOW_GLOBAL:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean allowGlobalColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.IS_REQUIRED
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private Integer isRequired;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.IS_REQUIRED:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean isRequiredColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.IS_LIMITED
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private Integer isLimited;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.IS_LIMITED:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean isLimitedColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.MAX_LENGTH
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private Integer maxLength;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.MAX_LENGTH:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean maxLengthColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.STEP_SIZE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private String stepSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.STEP_SIZE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean stepSizeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.MIN_VALUE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private String minValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.MIN_VALUE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean minValueColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.MAX_VALUE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private String maxValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.MAX_VALUE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean maxValueColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.DEFAULT_VALUE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private String defaultValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.DEFAULT_VALUE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean defaultValueColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.DESCRIPTION
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.DESCRIPTION:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.STATUS
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.STATUS:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.LAST_UPDATE_TIME
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.LAST_UPDATE_OPER
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CREATE_TIME
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CREATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CREATE_OPER
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cf_cmpt_char.CREATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private boolean createOperColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cf_cmpt_char
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_ID
     *
     * @return the value of cf_cmpt_char.CHAR_ID
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public String getCharId() {
        return charId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_ID:Coloured
     *
     * @return the value of cf_cmpt_char.CHAR_ID:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCharIdColoured() {
        return charIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_ID:Coloured
     *
     * @return the value of cf_cmpt_char.CHAR_ID:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCharIdNotColoured() {
        return !charIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CHAR_ID
     *
     * @param charId the value for cf_cmpt_char.CHAR_ID
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCharId(String charId) {
        this.charId = charId == null ? null : charId.trim();
        this.charIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CHAR_ID:Coloured
     *
     * @param charIdColoured the value for cf_cmpt_char.CHAR_ID:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCharIdColoured(boolean charIdColoured) {
        this.charIdColoured = charIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_CODE
     *
     * @return the value of cf_cmpt_char.CHAR_CODE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public String getCharCode() {
        return charCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_CODE:Coloured
     *
     * @return the value of cf_cmpt_char.CHAR_CODE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCharCodeColoured() {
        return charCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_CODE:Coloured
     *
     * @return the value of cf_cmpt_char.CHAR_CODE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCharCodeNotColoured() {
        return !charCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CHAR_CODE
     *
     * @param charCode the value for cf_cmpt_char.CHAR_CODE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCharCode(String charCode) {
        this.charCode = charCode == null ? null : charCode.trim();
        this.charCodeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CHAR_CODE:Coloured
     *
     * @param charCodeColoured the value for cf_cmpt_char.CHAR_CODE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCharCodeColoured(boolean charCodeColoured) {
        this.charCodeColoured = charCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_NAME
     *
     * @return the value of cf_cmpt_char.CHAR_NAME
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public String getCharName() {
        return charName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_NAME:Coloured
     *
     * @return the value of cf_cmpt_char.CHAR_NAME:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCharNameColoured() {
        return charNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_NAME:Coloured
     *
     * @return the value of cf_cmpt_char.CHAR_NAME:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCharNameNotColoured() {
        return !charNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CHAR_NAME
     *
     * @param charName the value for cf_cmpt_char.CHAR_NAME
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCharName(String charName) {
        this.charName = charName == null ? null : charName.trim();
        this.charNameColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CHAR_NAME:Coloured
     *
     * @param charNameColoured the value for cf_cmpt_char.CHAR_NAME:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCharNameColoured(boolean charNameColoured) {
        this.charNameColoured = charNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_ALIAS
     *
     * @return the value of cf_cmpt_char.CHAR_ALIAS
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public String getCharAlias() {
        return charAlias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_ALIAS:Coloured
     *
     * @return the value of cf_cmpt_char.CHAR_ALIAS:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCharAliasColoured() {
        return charAliasColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_ALIAS:Coloured
     *
     * @return the value of cf_cmpt_char.CHAR_ALIAS:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCharAliasNotColoured() {
        return !charAliasColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CHAR_ALIAS
     *
     * @param charAlias the value for cf_cmpt_char.CHAR_ALIAS
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCharAlias(String charAlias) {
        this.charAlias = charAlias == null ? null : charAlias.trim();
        this.charAliasColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CHAR_ALIAS:Coloured
     *
     * @param charAliasColoured the value for cf_cmpt_char.CHAR_ALIAS:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCharAliasColoured(boolean charAliasColoured) {
        this.charAliasColoured = charAliasColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.SPEC_TYPE
     *
     * @return the value of cf_cmpt_char.SPEC_TYPE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public Integer getSpecType() {
        return specType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.SPEC_TYPE:Coloured
     *
     * @return the value of cf_cmpt_char.SPEC_TYPE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isSpecTypeColoured() {
        return specTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.SPEC_TYPE:Coloured
     *
     * @return the value of cf_cmpt_char.SPEC_TYPE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isSpecTypeNotColoured() {
        return !specTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.SPEC_TYPE
     *
     * @param specType the value for cf_cmpt_char.SPEC_TYPE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setSpecType(Integer specType) {
        this.specType = specType;
        this.specTypeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.SPEC_TYPE:Coloured
     *
     * @param specTypeColoured the value for cf_cmpt_char.SPEC_TYPE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setSpecTypeColoured(boolean specTypeColoured) {
        this.specTypeColoured = specTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_TYPE
     *
     * @return the value of cf_cmpt_char.CHAR_TYPE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public Integer getCharType() {
        return charType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_TYPE:Coloured
     *
     * @return the value of cf_cmpt_char.CHAR_TYPE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCharTypeColoured() {
        return charTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CHAR_TYPE:Coloured
     *
     * @return the value of cf_cmpt_char.CHAR_TYPE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCharTypeNotColoured() {
        return !charTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CHAR_TYPE
     *
     * @param charType the value for cf_cmpt_char.CHAR_TYPE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCharType(Integer charType) {
        this.charType = charType;
        this.charTypeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CHAR_TYPE:Coloured
     *
     * @param charTypeColoured the value for cf_cmpt_char.CHAR_TYPE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCharTypeColoured(boolean charTypeColoured) {
        this.charTypeColoured = charTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.SRC_LEVEL
     *
     * @return the value of cf_cmpt_char.SRC_LEVEL
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public Integer getSrcLevel() {
        return srcLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.SRC_LEVEL:Coloured
     *
     * @return the value of cf_cmpt_char.SRC_LEVEL:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isSrcLevelColoured() {
        return srcLevelColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.SRC_LEVEL:Coloured
     *
     * @return the value of cf_cmpt_char.SRC_LEVEL:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isSrcLevelNotColoured() {
        return !srcLevelColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.SRC_LEVEL
     *
     * @param srcLevel the value for cf_cmpt_char.SRC_LEVEL
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setSrcLevel(Integer srcLevel) {
        this.srcLevel = srcLevel;
        this.srcLevelColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.SRC_LEVEL:Coloured
     *
     * @param srcLevelColoured the value for cf_cmpt_char.SRC_LEVEL:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setSrcLevelColoured(boolean srcLevelColoured) {
        this.srcLevelColoured = srcLevelColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.ALLOW_GLOBAL
     *
     * @return the value of cf_cmpt_char.ALLOW_GLOBAL
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public Integer getAllowGlobal() {
        return allowGlobal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.ALLOW_GLOBAL:Coloured
     *
     * @return the value of cf_cmpt_char.ALLOW_GLOBAL:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isAllowGlobalColoured() {
        return allowGlobalColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.ALLOW_GLOBAL:Coloured
     *
     * @return the value of cf_cmpt_char.ALLOW_GLOBAL:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isAllowGlobalNotColoured() {
        return !allowGlobalColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.ALLOW_GLOBAL
     *
     * @param allowGlobal the value for cf_cmpt_char.ALLOW_GLOBAL
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setAllowGlobal(Integer allowGlobal) {
        this.allowGlobal = allowGlobal;
        this.allowGlobalColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.ALLOW_GLOBAL:Coloured
     *
     * @param allowGlobalColoured the value for cf_cmpt_char.ALLOW_GLOBAL:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setAllowGlobalColoured(boolean allowGlobalColoured) {
        this.allowGlobalColoured = allowGlobalColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.IS_REQUIRED
     *
     * @return the value of cf_cmpt_char.IS_REQUIRED
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public Integer getIsRequired() {
        return isRequired;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.IS_REQUIRED:Coloured
     *
     * @return the value of cf_cmpt_char.IS_REQUIRED:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isIsRequiredColoured() {
        return isRequiredColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.IS_REQUIRED:Coloured
     *
     * @return the value of cf_cmpt_char.IS_REQUIRED:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isIsRequiredNotColoured() {
        return !isRequiredColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.IS_REQUIRED
     *
     * @param isRequired the value for cf_cmpt_char.IS_REQUIRED
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setIsRequired(Integer isRequired) {
        this.isRequired = isRequired;
        this.isRequiredColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.IS_REQUIRED:Coloured
     *
     * @param isRequiredColoured the value for cf_cmpt_char.IS_REQUIRED:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setIsRequiredColoured(boolean isRequiredColoured) {
        this.isRequiredColoured = isRequiredColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.IS_LIMITED
     *
     * @return the value of cf_cmpt_char.IS_LIMITED
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public Integer getIsLimited() {
        return isLimited;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.IS_LIMITED:Coloured
     *
     * @return the value of cf_cmpt_char.IS_LIMITED:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isIsLimitedColoured() {
        return isLimitedColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.IS_LIMITED:Coloured
     *
     * @return the value of cf_cmpt_char.IS_LIMITED:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isIsLimitedNotColoured() {
        return !isLimitedColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.IS_LIMITED
     *
     * @param isLimited the value for cf_cmpt_char.IS_LIMITED
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setIsLimited(Integer isLimited) {
        this.isLimited = isLimited;
        this.isLimitedColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.IS_LIMITED:Coloured
     *
     * @param isLimitedColoured the value for cf_cmpt_char.IS_LIMITED:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setIsLimitedColoured(boolean isLimitedColoured) {
        this.isLimitedColoured = isLimitedColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.MAX_LENGTH
     *
     * @return the value of cf_cmpt_char.MAX_LENGTH
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public Integer getMaxLength() {
        return maxLength;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.MAX_LENGTH:Coloured
     *
     * @return the value of cf_cmpt_char.MAX_LENGTH:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isMaxLengthColoured() {
        return maxLengthColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.MAX_LENGTH:Coloured
     *
     * @return the value of cf_cmpt_char.MAX_LENGTH:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isMaxLengthNotColoured() {
        return !maxLengthColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.MAX_LENGTH
     *
     * @param maxLength the value for cf_cmpt_char.MAX_LENGTH
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setMaxLength(Integer maxLength) {
        this.maxLength = maxLength;
        this.maxLengthColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.MAX_LENGTH:Coloured
     *
     * @param maxLengthColoured the value for cf_cmpt_char.MAX_LENGTH:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setMaxLengthColoured(boolean maxLengthColoured) {
        this.maxLengthColoured = maxLengthColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.STEP_SIZE
     *
     * @return the value of cf_cmpt_char.STEP_SIZE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public String getStepSize() {
        return stepSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.STEP_SIZE:Coloured
     *
     * @return the value of cf_cmpt_char.STEP_SIZE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isStepSizeColoured() {
        return stepSizeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.STEP_SIZE:Coloured
     *
     * @return the value of cf_cmpt_char.STEP_SIZE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isStepSizeNotColoured() {
        return !stepSizeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.STEP_SIZE
     *
     * @param stepSize the value for cf_cmpt_char.STEP_SIZE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setStepSize(String stepSize) {
        this.stepSize = stepSize == null ? null : stepSize.trim();
        this.stepSizeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.STEP_SIZE:Coloured
     *
     * @param stepSizeColoured the value for cf_cmpt_char.STEP_SIZE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setStepSizeColoured(boolean stepSizeColoured) {
        this.stepSizeColoured = stepSizeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.MIN_VALUE
     *
     * @return the value of cf_cmpt_char.MIN_VALUE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public String getMinValue() {
        return minValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.MIN_VALUE:Coloured
     *
     * @return the value of cf_cmpt_char.MIN_VALUE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isMinValueColoured() {
        return minValueColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.MIN_VALUE:Coloured
     *
     * @return the value of cf_cmpt_char.MIN_VALUE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isMinValueNotColoured() {
        return !minValueColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.MIN_VALUE
     *
     * @param minValue the value for cf_cmpt_char.MIN_VALUE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setMinValue(String minValue) {
        this.minValue = minValue == null ? null : minValue.trim();
        this.minValueColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.MIN_VALUE:Coloured
     *
     * @param minValueColoured the value for cf_cmpt_char.MIN_VALUE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setMinValueColoured(boolean minValueColoured) {
        this.minValueColoured = minValueColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.MAX_VALUE
     *
     * @return the value of cf_cmpt_char.MAX_VALUE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public String getMaxValue() {
        return maxValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.MAX_VALUE:Coloured
     *
     * @return the value of cf_cmpt_char.MAX_VALUE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isMaxValueColoured() {
        return maxValueColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.MAX_VALUE:Coloured
     *
     * @return the value of cf_cmpt_char.MAX_VALUE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isMaxValueNotColoured() {
        return !maxValueColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.MAX_VALUE
     *
     * @param maxValue the value for cf_cmpt_char.MAX_VALUE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setMaxValue(String maxValue) {
        this.maxValue = maxValue == null ? null : maxValue.trim();
        this.maxValueColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.MAX_VALUE:Coloured
     *
     * @param maxValueColoured the value for cf_cmpt_char.MAX_VALUE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setMaxValueColoured(boolean maxValueColoured) {
        this.maxValueColoured = maxValueColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.DEFAULT_VALUE
     *
     * @return the value of cf_cmpt_char.DEFAULT_VALUE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public String getDefaultValue() {
        return defaultValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.DEFAULT_VALUE:Coloured
     *
     * @return the value of cf_cmpt_char.DEFAULT_VALUE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isDefaultValueColoured() {
        return defaultValueColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.DEFAULT_VALUE:Coloured
     *
     * @return the value of cf_cmpt_char.DEFAULT_VALUE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isDefaultValueNotColoured() {
        return !defaultValueColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.DEFAULT_VALUE
     *
     * @param defaultValue the value for cf_cmpt_char.DEFAULT_VALUE
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setDefaultValue(String defaultValue) {
        this.defaultValue = defaultValue == null ? null : defaultValue.trim();
        this.defaultValueColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.DEFAULT_VALUE:Coloured
     *
     * @param defaultValueColoured the value for cf_cmpt_char.DEFAULT_VALUE:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setDefaultValueColoured(boolean defaultValueColoured) {
        this.defaultValueColoured = defaultValueColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.DESCRIPTION
     *
     * @return the value of cf_cmpt_char.DESCRIPTION
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.DESCRIPTION:Coloured
     *
     * @return the value of cf_cmpt_char.DESCRIPTION:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.DESCRIPTION:Coloured
     *
     * @return the value of cf_cmpt_char.DESCRIPTION:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isDescriptionNotColoured() {
        return !descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.DESCRIPTION
     *
     * @param description the value for cf_cmpt_char.DESCRIPTION
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for cf_cmpt_char.DESCRIPTION:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.STATUS
     *
     * @return the value of cf_cmpt_char.STATUS
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.STATUS:Coloured
     *
     * @return the value of cf_cmpt_char.STATUS:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.STATUS:Coloured
     *
     * @return the value of cf_cmpt_char.STATUS:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isStatusNotColoured() {
        return !statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.STATUS
     *
     * @param status the value for cf_cmpt_char.STATUS
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.STATUS:Coloured
     *
     * @param statusColoured the value for cf_cmpt_char.STATUS:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.LAST_UPDATE_TIME
     *
     * @return the value of cf_cmpt_char.LAST_UPDATE_TIME
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of cf_cmpt_char.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of cf_cmpt_char.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isLastUpdateTimeNotColoured() {
        return !lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for cf_cmpt_char.LAST_UPDATE_TIME
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for cf_cmpt_char.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.LAST_UPDATE_OPER
     *
     * @return the value of cf_cmpt_char.LAST_UPDATE_OPER
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of cf_cmpt_char.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of cf_cmpt_char.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isLastUpdateOperNotColoured() {
        return !lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for cf_cmpt_char.LAST_UPDATE_OPER
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for cf_cmpt_char.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CREATE_TIME
     *
     * @return the value of cf_cmpt_char.CREATE_TIME
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CREATE_TIME:Coloured
     *
     * @return the value of cf_cmpt_char.CREATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CREATE_TIME:Coloured
     *
     * @return the value of cf_cmpt_char.CREATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCreateTimeNotColoured() {
        return !createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CREATE_TIME
     *
     * @param createTime the value for cf_cmpt_char.CREATE_TIME
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for cf_cmpt_char.CREATE_TIME:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CREATE_OPER
     *
     * @return the value of cf_cmpt_char.CREATE_OPER
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CREATE_OPER:Coloured
     *
     * @return the value of cf_cmpt_char.CREATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cf_cmpt_char.CREATE_OPER:Coloured
     *
     * @return the value of cf_cmpt_char.CREATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public boolean isCreateOperNotColoured() {
        return !createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CREATE_OPER
     *
     * @param createOper the value for cf_cmpt_char.CREATE_OPER
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cf_cmpt_char.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for cf_cmpt_char.CREATE_OPER:Coloured
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_cmpt_char
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        CfCmptChar other = (CfCmptChar) that;
        return (this.getCharId() == null ? other.getCharId() == null : this.getCharId().equals(other.getCharId()))
            && (this.getCharCode() == null ? other.getCharCode() == null : this.getCharCode().equals(other.getCharCode()))
            && (this.getCharName() == null ? other.getCharName() == null : this.getCharName().equals(other.getCharName()))
            && (this.getCharAlias() == null ? other.getCharAlias() == null : this.getCharAlias().equals(other.getCharAlias()))
            && (this.getSpecType() == null ? other.getSpecType() == null : this.getSpecType().equals(other.getSpecType()))
            && (this.getCharType() == null ? other.getCharType() == null : this.getCharType().equals(other.getCharType()))
            && (this.getSrcLevel() == null ? other.getSrcLevel() == null : this.getSrcLevel().equals(other.getSrcLevel()))
            && (this.getAllowGlobal() == null ? other.getAllowGlobal() == null : this.getAllowGlobal().equals(other.getAllowGlobal()))
            && (this.getIsRequired() == null ? other.getIsRequired() == null : this.getIsRequired().equals(other.getIsRequired()))
            && (this.getIsLimited() == null ? other.getIsLimited() == null : this.getIsLimited().equals(other.getIsLimited()))
            && (this.getMaxLength() == null ? other.getMaxLength() == null : this.getMaxLength().equals(other.getMaxLength()))
            && (this.getStepSize() == null ? other.getStepSize() == null : this.getStepSize().equals(other.getStepSize()))
            && (this.getMinValue() == null ? other.getMinValue() == null : this.getMinValue().equals(other.getMinValue()))
            && (this.getMaxValue() == null ? other.getMaxValue() == null : this.getMaxValue().equals(other.getMaxValue()))
            && (this.getDefaultValue() == null ? other.getDefaultValue() == null : this.getDefaultValue().equals(other.getDefaultValue()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_cmpt_char
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCharId() == null) ? 0 : getCharId().hashCode());
        result = prime * result + ((getCharCode() == null) ? 0 : getCharCode().hashCode());
        result = prime * result + ((getCharName() == null) ? 0 : getCharName().hashCode());
        result = prime * result + ((getCharAlias() == null) ? 0 : getCharAlias().hashCode());
        result = prime * result + ((getSpecType() == null) ? 0 : getSpecType().hashCode());
        result = prime * result + ((getCharType() == null) ? 0 : getCharType().hashCode());
        result = prime * result + ((getSrcLevel() == null) ? 0 : getSrcLevel().hashCode());
        result = prime * result + ((getAllowGlobal() == null) ? 0 : getAllowGlobal().hashCode());
        result = prime * result + ((getIsRequired() == null) ? 0 : getIsRequired().hashCode());
        result = prime * result + ((getIsLimited() == null) ? 0 : getIsLimited().hashCode());
        result = prime * result + ((getMaxLength() == null) ? 0 : getMaxLength().hashCode());
        result = prime * result + ((getStepSize() == null) ? 0 : getStepSize().hashCode());
        result = prime * result + ((getMinValue() == null) ? 0 : getMinValue().hashCode());
        result = prime * result + ((getMaxValue() == null) ? 0 : getMaxValue().hashCode());
        result = prime * result + ((getDefaultValue() == null) ? 0 : getDefaultValue().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_cmpt_char
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    @Override
    public void copyProperties(Object that) {
        if (this == that || that == null || this.getClass() != that.getClass() ) {
            return;
        }
        CfCmptChar other = (CfCmptChar) that;
        if(other.isCharIdColoured() ) {this.setCharId(other.getCharId() );}
        if(other.isCharCodeColoured() ) {this.setCharCode(other.getCharCode() );}
        if(other.isCharNameColoured() ) {this.setCharName(other.getCharName() );}
        if(other.isCharAliasColoured() ) {this.setCharAlias(other.getCharAlias() );}
        if(other.isSpecTypeColoured() ) {this.setSpecType(other.getSpecType() );}
        if(other.isCharTypeColoured() ) {this.setCharType(other.getCharType() );}
        if(other.isSrcLevelColoured() ) {this.setSrcLevel(other.getSrcLevel() );}
        if(other.isAllowGlobalColoured() ) {this.setAllowGlobal(other.getAllowGlobal() );}
        if(other.isIsRequiredColoured() ) {this.setIsRequired(other.getIsRequired() );}
        if(other.isIsLimitedColoured() ) {this.setIsLimited(other.getIsLimited() );}
        if(other.isMaxLengthColoured() ) {this.setMaxLength(other.getMaxLength() );}
        if(other.isStepSizeColoured() ) {this.setStepSize(other.getStepSize() );}
        if(other.isMinValueColoured() ) {this.setMinValue(other.getMinValue() );}
        if(other.isMaxValueColoured() ) {this.setMaxValue(other.getMaxValue() );}
        if(other.isDefaultValueColoured() ) {this.setDefaultValue(other.getDefaultValue() );}
        if(other.isDescriptionColoured() ) {this.setDescription(other.getDescription() );}
        if(other.isStatusColoured() ) {this.setStatus(other.getStatus() );}
        if(other.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(other.getLastUpdateTime() );}
        if(other.isLastUpdateOperColoured() ) {this.setLastUpdateOper(other.getLastUpdateOper() );}
        if(other.isCreateTimeColoured() ) {this.setCreateTime(other.getCreateTime() );}
        if(other.isCreateOperColoured() ) {this.setCreateOper(other.getCreateOper() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_cmpt_char
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    @Override
    public JSONObject toJSON() {
        HashMap<String, Object> hashMap = new HashMap();
        if(this.charIdColoured) {hashMap.put("charId", this.charId);}
        if(this.charCodeColoured) {hashMap.put("charCode", this.charCode);}
        if(this.charNameColoured) {hashMap.put("charName", this.charName);}
        if(this.charAliasColoured) {hashMap.put("charAlias", this.charAlias);}
        if(this.specTypeColoured) {hashMap.put("specType", this.specType);}
        if(this.charTypeColoured) {hashMap.put("charType", this.charType);}
        if(this.srcLevelColoured) {hashMap.put("srcLevel", this.srcLevel);}
        if(this.allowGlobalColoured) {hashMap.put("allowGlobal", this.allowGlobal);}
        if(this.isRequiredColoured) {hashMap.put("isRequired", this.isRequired);}
        if(this.isLimitedColoured) {hashMap.put("isLimited", this.isLimited);}
        if(this.maxLengthColoured) {hashMap.put("maxLength", this.maxLength);}
        if(this.stepSizeColoured) {hashMap.put("stepSize", this.stepSize);}
        if(this.minValueColoured) {hashMap.put("minValue", this.minValue);}
        if(this.maxValueColoured) {hashMap.put("maxValue", this.maxValue);}
        if(this.defaultValueColoured) {hashMap.put("defaultValue", this.defaultValue);}
        if(this.descriptionColoured) {hashMap.put("description", this.description);}
        if(this.statusColoured) {hashMap.put("status", this.status);}
        if(this.lastUpdateTimeColoured) {hashMap.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOperColoured) {hashMap.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTimeColoured) {hashMap.put("createTime", this.createTime);}
        if(this.createOperColoured) {hashMap.put("createOper", this.createOper);}
        return (JSONObject) JSON.toJSON(hashMap);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cf_cmpt_char
     *
     * @mbg.generated Mon Dec 10 12:31:47 CST 2018
     */
    @Override
    public void clear() {
        if(this.charIdColoured) {this.charId = null; this.charIdColoured = false;}
        if(this.charCodeColoured) {this.charCode = null; this.charCodeColoured = false;}
        if(this.charNameColoured) {this.charName = null; this.charNameColoured = false;}
        if(this.charAliasColoured) {this.charAlias = null; this.charAliasColoured = false;}
        if(this.specTypeColoured) {this.specType = null; this.specTypeColoured = false;}
        if(this.charTypeColoured) {this.charType = null; this.charTypeColoured = false;}
        if(this.srcLevelColoured) {this.srcLevel = null; this.srcLevelColoured = false;}
        if(this.allowGlobalColoured) {this.allowGlobal = null; this.allowGlobalColoured = false;}
        if(this.isRequiredColoured) {this.isRequired = null; this.isRequiredColoured = false;}
        if(this.isLimitedColoured) {this.isLimited = null; this.isLimitedColoured = false;}
        if(this.maxLengthColoured) {this.maxLength = null; this.maxLengthColoured = false;}
        if(this.stepSizeColoured) {this.stepSize = null; this.stepSizeColoured = false;}
        if(this.minValueColoured) {this.minValue = null; this.minValueColoured = false;}
        if(this.maxValueColoured) {this.maxValue = null; this.maxValueColoured = false;}
        if(this.defaultValueColoured) {this.defaultValue = null; this.defaultValueColoured = false;}
        if(this.descriptionColoured) {this.description = null; this.descriptionColoured = false;}
        if(this.statusColoured) {this.status = null; this.statusColoured = false;}
        if(this.lastUpdateTimeColoured) {this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;}
        if(this.lastUpdateOperColoured) {this.lastUpdateOper = null; this.lastUpdateOperColoured = false;}
        if(this.createTimeColoured) {this.createTime = null; this.createTimeColoured = false;}
        if(this.createOperColoured) {this.createOper = null; this.createOperColoured = false;}
        return;
    }
}