package com.yatop.lambda.base.model;

import java.io.Serializable;
import java.util.Date;

public class DwDataWarehouse implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.DW_ID
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private Long dwId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.DW_CODE
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private String dwCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.DW_NAME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private String dwName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.DW_TYPE
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private Integer dwType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.OWNER_PROJECT_ID
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private Long ownerProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.DATA_DFS_DIR
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private String dataDfsDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.DATA_LOCAL_DIR
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private String dataLocalDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.DESCRIPTION
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.STATUS
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.LAST_UPDATE_TIME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.LAST_UPDATE_OPER
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.CREATE_TIME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_warehouse.CREATE_OPER
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private String createOper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dw_data_warehouse
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.DW_ID
     *
     * @return the value of dw_data_warehouse.DW_ID
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public Long getDwId() {
        return dwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.DW_ID
     *
     * @param dwId the value for dw_data_warehouse.DW_ID
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setDwId(Long dwId) {
        this.dwId = dwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.DW_CODE
     *
     * @return the value of dw_data_warehouse.DW_CODE
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public String getDwCode() {
        return dwCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.DW_CODE
     *
     * @param dwCode the value for dw_data_warehouse.DW_CODE
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setDwCode(String dwCode) {
        this.dwCode = dwCode == null ? null : dwCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.DW_NAME
     *
     * @return the value of dw_data_warehouse.DW_NAME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public String getDwName() {
        return dwName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.DW_NAME
     *
     * @param dwName the value for dw_data_warehouse.DW_NAME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setDwName(String dwName) {
        this.dwName = dwName == null ? null : dwName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.DW_TYPE
     *
     * @return the value of dw_data_warehouse.DW_TYPE
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public Integer getDwType() {
        return dwType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.DW_TYPE
     *
     * @param dwType the value for dw_data_warehouse.DW_TYPE
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setDwType(Integer dwType) {
        this.dwType = dwType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.OWNER_PROJECT_ID
     *
     * @return the value of dw_data_warehouse.OWNER_PROJECT_ID
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public Long getOwnerProjectId() {
        return ownerProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.OWNER_PROJECT_ID
     *
     * @param ownerProjectId the value for dw_data_warehouse.OWNER_PROJECT_ID
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setOwnerProjectId(Long ownerProjectId) {
        this.ownerProjectId = ownerProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.DATA_DFS_DIR
     *
     * @return the value of dw_data_warehouse.DATA_DFS_DIR
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public String getDataDfsDir() {
        return dataDfsDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.DATA_DFS_DIR
     *
     * @param dataDfsDir the value for dw_data_warehouse.DATA_DFS_DIR
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setDataDfsDir(String dataDfsDir) {
        this.dataDfsDir = dataDfsDir == null ? null : dataDfsDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.DATA_LOCAL_DIR
     *
     * @return the value of dw_data_warehouse.DATA_LOCAL_DIR
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public String getDataLocalDir() {
        return dataLocalDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.DATA_LOCAL_DIR
     *
     * @param dataLocalDir the value for dw_data_warehouse.DATA_LOCAL_DIR
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setDataLocalDir(String dataLocalDir) {
        this.dataLocalDir = dataLocalDir == null ? null : dataLocalDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.DESCRIPTION
     *
     * @return the value of dw_data_warehouse.DESCRIPTION
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.DESCRIPTION
     *
     * @param description the value for dw_data_warehouse.DESCRIPTION
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.STATUS
     *
     * @return the value of dw_data_warehouse.STATUS
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.STATUS
     *
     * @param status the value for dw_data_warehouse.STATUS
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.LAST_UPDATE_TIME
     *
     * @return the value of dw_data_warehouse.LAST_UPDATE_TIME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for dw_data_warehouse.LAST_UPDATE_TIME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.LAST_UPDATE_OPER
     *
     * @return the value of dw_data_warehouse.LAST_UPDATE_OPER
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for dw_data_warehouse.LAST_UPDATE_OPER
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.CREATE_TIME
     *
     * @return the value of dw_data_warehouse.CREATE_TIME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.CREATE_TIME
     *
     * @param createTime the value for dw_data_warehouse.CREATE_TIME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_warehouse.CREATE_OPER
     *
     * @return the value of dw_data_warehouse.CREATE_OPER
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_warehouse.CREATE_OPER
     *
     * @param createOper the value for dw_data_warehouse.CREATE_OPER
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_data_warehouse
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DwDataWarehouse other = (DwDataWarehouse) that;
        return (this.getDwId() == null ? other.getDwId() == null : this.getDwId().equals(other.getDwId()))
            && (this.getDwCode() == null ? other.getDwCode() == null : this.getDwCode().equals(other.getDwCode()))
            && (this.getDwName() == null ? other.getDwName() == null : this.getDwName().equals(other.getDwName()))
            && (this.getDwType() == null ? other.getDwType() == null : this.getDwType().equals(other.getDwType()))
            && (this.getOwnerProjectId() == null ? other.getOwnerProjectId() == null : this.getOwnerProjectId().equals(other.getOwnerProjectId()))
            && (this.getDataDfsDir() == null ? other.getDataDfsDir() == null : this.getDataDfsDir().equals(other.getDataDfsDir()))
            && (this.getDataLocalDir() == null ? other.getDataLocalDir() == null : this.getDataLocalDir().equals(other.getDataLocalDir()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_data_warehouse
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getDwId() == null) ? 0 : getDwId().hashCode());
        result = prime * result + ((getDwCode() == null) ? 0 : getDwCode().hashCode());
        result = prime * result + ((getDwName() == null) ? 0 : getDwName().hashCode());
        result = prime * result + ((getDwType() == null) ? 0 : getDwType().hashCode());
        result = prime * result + ((getOwnerProjectId() == null) ? 0 : getOwnerProjectId().hashCode());
        result = prime * result + ((getDataDfsDir() == null) ? 0 : getDataDfsDir().hashCode());
        result = prime * result + ((getDataLocalDir() == null) ? 0 : getDataLocalDir().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }
}