package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;

public class DwDataTable extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.TABLE_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long tableId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.TABLE_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean tableIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.TABLE_NAME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.TABLE_NAME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean tableNameColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.TABLE_TYPE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Integer tableType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.TABLE_TYPE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean tableTypeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.OWNER_DW_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long ownerDwId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.OWNER_DW_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean ownerDwIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.REL_EXPERIMENT_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long relExperimentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.REL_EXPERIMENT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean relExperimentIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.REL_JOB_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long relJobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.REL_JOB_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean relJobIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.REL_NODE_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long relNodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.REL_NODE_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean relNodeIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.REL_CHAR_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long relCharId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.REL_CHAR_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean relCharIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.TABLE_COLUMNS
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long tableColumns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.TABLE_COLUMNS:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean tableColumnsColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.TABLE_ROWS
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long tableRows;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.TABLE_ROWS:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean tableRowsColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.DATA_FILE_TYPE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Integer dataFileType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.DATA_FILE_TYPE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean dataFileTypeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.DATA_FILE_SIZE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long dataFileSize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.DATA_FILE_SIZE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean dataFileSizeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.DATA_FILE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String dataFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.DATA_FILE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean dataFileColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.DATA_SUMMARY_FILE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String dataSummaryFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.DATA_SUMMARY_FILE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean dataSummaryFileColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.TABLE_STATE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Integer tableState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.TABLE_STATE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean tableStateColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.DESCRIPTION
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.DESCRIPTION:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.STATUS
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.STATUS:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.LAST_UPDATE_OPER
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.CREATE_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.CREATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.CREATE_OPER
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dw_data_table.CREATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean createOperColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dw_data_table
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.TABLE_ID
     *
     * @return the value of dw_data_table.TABLE_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getTableId() {
        return tableId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.TABLE_ID:Coloured
     *
     * @return the value of dw_data_table.TABLE_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isTableIdColoured() {
        return tableIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.TABLE_ID
     *
     * @param tableId the value for dw_data_table.TABLE_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setTableId(Long tableId) {
        this.tableId = tableId;
        this.tableIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.TABLE_ID:Coloured
     *
     * @param tableIdColoured the value for dw_data_table.TABLE_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setTableIdColoured(boolean tableIdColoured) {
        this.tableIdColoured = tableIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.TABLE_NAME
     *
     * @return the value of dw_data_table.TABLE_NAME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.TABLE_NAME:Coloured
     *
     * @return the value of dw_data_table.TABLE_NAME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isTableNameColoured() {
        return tableNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.TABLE_NAME
     *
     * @param tableName the value for dw_data_table.TABLE_NAME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
        this.tableNameColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.TABLE_NAME:Coloured
     *
     * @param tableNameColoured the value for dw_data_table.TABLE_NAME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setTableNameColoured(boolean tableNameColoured) {
        this.tableNameColoured = tableNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.TABLE_TYPE
     *
     * @return the value of dw_data_table.TABLE_TYPE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Integer getTableType() {
        return tableType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.TABLE_TYPE:Coloured
     *
     * @return the value of dw_data_table.TABLE_TYPE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isTableTypeColoured() {
        return tableTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.TABLE_TYPE
     *
     * @param tableType the value for dw_data_table.TABLE_TYPE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setTableType(Integer tableType) {
        this.tableType = tableType;
        this.tableTypeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.TABLE_TYPE:Coloured
     *
     * @param tableTypeColoured the value for dw_data_table.TABLE_TYPE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setTableTypeColoured(boolean tableTypeColoured) {
        this.tableTypeColoured = tableTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.OWNER_DW_ID
     *
     * @return the value of dw_data_table.OWNER_DW_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getOwnerDwId() {
        return ownerDwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.OWNER_DW_ID:Coloured
     *
     * @return the value of dw_data_table.OWNER_DW_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isOwnerDwIdColoured() {
        return ownerDwIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.OWNER_DW_ID
     *
     * @param ownerDwId the value for dw_data_table.OWNER_DW_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setOwnerDwId(Long ownerDwId) {
        this.ownerDwId = ownerDwId;
        this.ownerDwIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.OWNER_DW_ID:Coloured
     *
     * @param ownerDwIdColoured the value for dw_data_table.OWNER_DW_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setOwnerDwIdColoured(boolean ownerDwIdColoured) {
        this.ownerDwIdColoured = ownerDwIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.REL_EXPERIMENT_ID
     *
     * @return the value of dw_data_table.REL_EXPERIMENT_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getRelExperimentId() {
        return relExperimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.REL_EXPERIMENT_ID:Coloured
     *
     * @return the value of dw_data_table.REL_EXPERIMENT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isRelExperimentIdColoured() {
        return relExperimentIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.REL_EXPERIMENT_ID
     *
     * @param relExperimentId the value for dw_data_table.REL_EXPERIMENT_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelExperimentId(Long relExperimentId) {
        this.relExperimentId = relExperimentId;
        this.relExperimentIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.REL_EXPERIMENT_ID:Coloured
     *
     * @param relExperimentIdColoured the value for dw_data_table.REL_EXPERIMENT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelExperimentIdColoured(boolean relExperimentIdColoured) {
        this.relExperimentIdColoured = relExperimentIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.REL_JOB_ID
     *
     * @return the value of dw_data_table.REL_JOB_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getRelJobId() {
        return relJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.REL_JOB_ID:Coloured
     *
     * @return the value of dw_data_table.REL_JOB_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isRelJobIdColoured() {
        return relJobIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.REL_JOB_ID
     *
     * @param relJobId the value for dw_data_table.REL_JOB_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelJobId(Long relJobId) {
        this.relJobId = relJobId;
        this.relJobIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.REL_JOB_ID:Coloured
     *
     * @param relJobIdColoured the value for dw_data_table.REL_JOB_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelJobIdColoured(boolean relJobIdColoured) {
        this.relJobIdColoured = relJobIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.REL_NODE_ID
     *
     * @return the value of dw_data_table.REL_NODE_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getRelNodeId() {
        return relNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.REL_NODE_ID:Coloured
     *
     * @return the value of dw_data_table.REL_NODE_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isRelNodeIdColoured() {
        return relNodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.REL_NODE_ID
     *
     * @param relNodeId the value for dw_data_table.REL_NODE_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelNodeId(Long relNodeId) {
        this.relNodeId = relNodeId;
        this.relNodeIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.REL_NODE_ID:Coloured
     *
     * @param relNodeIdColoured the value for dw_data_table.REL_NODE_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelNodeIdColoured(boolean relNodeIdColoured) {
        this.relNodeIdColoured = relNodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.REL_CHAR_ID
     *
     * @return the value of dw_data_table.REL_CHAR_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getRelCharId() {
        return relCharId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.REL_CHAR_ID:Coloured
     *
     * @return the value of dw_data_table.REL_CHAR_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isRelCharIdColoured() {
        return relCharIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.REL_CHAR_ID
     *
     * @param relCharId the value for dw_data_table.REL_CHAR_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelCharId(Long relCharId) {
        this.relCharId = relCharId;
        this.relCharIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.REL_CHAR_ID:Coloured
     *
     * @param relCharIdColoured the value for dw_data_table.REL_CHAR_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelCharIdColoured(boolean relCharIdColoured) {
        this.relCharIdColoured = relCharIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.TABLE_COLUMNS
     *
     * @return the value of dw_data_table.TABLE_COLUMNS
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getTableColumns() {
        return tableColumns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.TABLE_COLUMNS:Coloured
     *
     * @return the value of dw_data_table.TABLE_COLUMNS:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isTableColumnsColoured() {
        return tableColumnsColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.TABLE_COLUMNS
     *
     * @param tableColumns the value for dw_data_table.TABLE_COLUMNS
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setTableColumns(Long tableColumns) {
        this.tableColumns = tableColumns;
        this.tableColumnsColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.TABLE_COLUMNS:Coloured
     *
     * @param tableColumnsColoured the value for dw_data_table.TABLE_COLUMNS:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setTableColumnsColoured(boolean tableColumnsColoured) {
        this.tableColumnsColoured = tableColumnsColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.TABLE_ROWS
     *
     * @return the value of dw_data_table.TABLE_ROWS
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getTableRows() {
        return tableRows;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.TABLE_ROWS:Coloured
     *
     * @return the value of dw_data_table.TABLE_ROWS:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isTableRowsColoured() {
        return tableRowsColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.TABLE_ROWS
     *
     * @param tableRows the value for dw_data_table.TABLE_ROWS
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setTableRows(Long tableRows) {
        this.tableRows = tableRows;
        this.tableRowsColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.TABLE_ROWS:Coloured
     *
     * @param tableRowsColoured the value for dw_data_table.TABLE_ROWS:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setTableRowsColoured(boolean tableRowsColoured) {
        this.tableRowsColoured = tableRowsColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.DATA_FILE_TYPE
     *
     * @return the value of dw_data_table.DATA_FILE_TYPE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Integer getDataFileType() {
        return dataFileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.DATA_FILE_TYPE:Coloured
     *
     * @return the value of dw_data_table.DATA_FILE_TYPE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isDataFileTypeColoured() {
        return dataFileTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.DATA_FILE_TYPE
     *
     * @param dataFileType the value for dw_data_table.DATA_FILE_TYPE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setDataFileType(Integer dataFileType) {
        this.dataFileType = dataFileType;
        this.dataFileTypeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.DATA_FILE_TYPE:Coloured
     *
     * @param dataFileTypeColoured the value for dw_data_table.DATA_FILE_TYPE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setDataFileTypeColoured(boolean dataFileTypeColoured) {
        this.dataFileTypeColoured = dataFileTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.DATA_FILE_SIZE
     *
     * @return the value of dw_data_table.DATA_FILE_SIZE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getDataFileSize() {
        return dataFileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.DATA_FILE_SIZE:Coloured
     *
     * @return the value of dw_data_table.DATA_FILE_SIZE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isDataFileSizeColoured() {
        return dataFileSizeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.DATA_FILE_SIZE
     *
     * @param dataFileSize the value for dw_data_table.DATA_FILE_SIZE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setDataFileSize(Long dataFileSize) {
        this.dataFileSize = dataFileSize;
        this.dataFileSizeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.DATA_FILE_SIZE:Coloured
     *
     * @param dataFileSizeColoured the value for dw_data_table.DATA_FILE_SIZE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setDataFileSizeColoured(boolean dataFileSizeColoured) {
        this.dataFileSizeColoured = dataFileSizeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.DATA_FILE
     *
     * @return the value of dw_data_table.DATA_FILE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getDataFile() {
        return dataFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.DATA_FILE:Coloured
     *
     * @return the value of dw_data_table.DATA_FILE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isDataFileColoured() {
        return dataFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.DATA_FILE
     *
     * @param dataFile the value for dw_data_table.DATA_FILE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setDataFile(String dataFile) {
        this.dataFile = dataFile == null ? null : dataFile.trim();
        this.dataFileColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.DATA_FILE:Coloured
     *
     * @param dataFileColoured the value for dw_data_table.DATA_FILE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setDataFileColoured(boolean dataFileColoured) {
        this.dataFileColoured = dataFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.DATA_SUMMARY_FILE
     *
     * @return the value of dw_data_table.DATA_SUMMARY_FILE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getDataSummaryFile() {
        return dataSummaryFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.DATA_SUMMARY_FILE:Coloured
     *
     * @return the value of dw_data_table.DATA_SUMMARY_FILE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isDataSummaryFileColoured() {
        return dataSummaryFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.DATA_SUMMARY_FILE
     *
     * @param dataSummaryFile the value for dw_data_table.DATA_SUMMARY_FILE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setDataSummaryFile(String dataSummaryFile) {
        this.dataSummaryFile = dataSummaryFile == null ? null : dataSummaryFile.trim();
        this.dataSummaryFileColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.DATA_SUMMARY_FILE:Coloured
     *
     * @param dataSummaryFileColoured the value for dw_data_table.DATA_SUMMARY_FILE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setDataSummaryFileColoured(boolean dataSummaryFileColoured) {
        this.dataSummaryFileColoured = dataSummaryFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.TABLE_STATE
     *
     * @return the value of dw_data_table.TABLE_STATE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Integer getTableState() {
        return tableState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.TABLE_STATE:Coloured
     *
     * @return the value of dw_data_table.TABLE_STATE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isTableStateColoured() {
        return tableStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.TABLE_STATE
     *
     * @param tableState the value for dw_data_table.TABLE_STATE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setTableState(Integer tableState) {
        this.tableState = tableState;
        this.tableStateColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.TABLE_STATE:Coloured
     *
     * @param tableStateColoured the value for dw_data_table.TABLE_STATE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setTableStateColoured(boolean tableStateColoured) {
        this.tableStateColoured = tableStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.DESCRIPTION
     *
     * @return the value of dw_data_table.DESCRIPTION
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.DESCRIPTION:Coloured
     *
     * @return the value of dw_data_table.DESCRIPTION:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.DESCRIPTION
     *
     * @param description the value for dw_data_table.DESCRIPTION
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for dw_data_table.DESCRIPTION:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.STATUS
     *
     * @return the value of dw_data_table.STATUS
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.STATUS:Coloured
     *
     * @return the value of dw_data_table.STATUS:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.STATUS
     *
     * @param status the value for dw_data_table.STATUS
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.STATUS:Coloured
     *
     * @param statusColoured the value for dw_data_table.STATUS:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.LAST_UPDATE_TIME
     *
     * @return the value of dw_data_table.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of dw_data_table.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for dw_data_table.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for dw_data_table.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.LAST_UPDATE_OPER
     *
     * @return the value of dw_data_table.LAST_UPDATE_OPER
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of dw_data_table.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for dw_data_table.LAST_UPDATE_OPER
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for dw_data_table.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.CREATE_TIME
     *
     * @return the value of dw_data_table.CREATE_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.CREATE_TIME:Coloured
     *
     * @return the value of dw_data_table.CREATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.CREATE_TIME
     *
     * @param createTime the value for dw_data_table.CREATE_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for dw_data_table.CREATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.CREATE_OPER
     *
     * @return the value of dw_data_table.CREATE_OPER
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dw_data_table.CREATE_OPER:Coloured
     *
     * @return the value of dw_data_table.CREATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.CREATE_OPER
     *
     * @param createOper the value for dw_data_table.CREATE_OPER
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dw_data_table.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for dw_data_table.CREATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_data_table
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        DwDataTable other = (DwDataTable) that;
        return (this.getTableId() == null ? other.getTableId() == null : this.getTableId().equals(other.getTableId()))
            && (this.getTableName() == null ? other.getTableName() == null : this.getTableName().equals(other.getTableName()))
            && (this.getTableType() == null ? other.getTableType() == null : this.getTableType().equals(other.getTableType()))
            && (this.getOwnerDwId() == null ? other.getOwnerDwId() == null : this.getOwnerDwId().equals(other.getOwnerDwId()))
            && (this.getRelExperimentId() == null ? other.getRelExperimentId() == null : this.getRelExperimentId().equals(other.getRelExperimentId()))
            && (this.getRelJobId() == null ? other.getRelJobId() == null : this.getRelJobId().equals(other.getRelJobId()))
            && (this.getRelNodeId() == null ? other.getRelNodeId() == null : this.getRelNodeId().equals(other.getRelNodeId()))
            && (this.getRelCharId() == null ? other.getRelCharId() == null : this.getRelCharId().equals(other.getRelCharId()))
            && (this.getTableColumns() == null ? other.getTableColumns() == null : this.getTableColumns().equals(other.getTableColumns()))
            && (this.getTableRows() == null ? other.getTableRows() == null : this.getTableRows().equals(other.getTableRows()))
            && (this.getDataFileType() == null ? other.getDataFileType() == null : this.getDataFileType().equals(other.getDataFileType()))
            && (this.getDataFileSize() == null ? other.getDataFileSize() == null : this.getDataFileSize().equals(other.getDataFileSize()))
            && (this.getDataFile() == null ? other.getDataFile() == null : this.getDataFile().equals(other.getDataFile()))
            && (this.getDataSummaryFile() == null ? other.getDataSummaryFile() == null : this.getDataSummaryFile().equals(other.getDataSummaryFile()))
            && (this.getTableState() == null ? other.getTableState() == null : this.getTableState().equals(other.getTableState()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_data_table
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTableId() == null) ? 0 : getTableId().hashCode());
        result = prime * result + ((getTableName() == null) ? 0 : getTableName().hashCode());
        result = prime * result + ((getTableType() == null) ? 0 : getTableType().hashCode());
        result = prime * result + ((getOwnerDwId() == null) ? 0 : getOwnerDwId().hashCode());
        result = prime * result + ((getRelExperimentId() == null) ? 0 : getRelExperimentId().hashCode());
        result = prime * result + ((getRelJobId() == null) ? 0 : getRelJobId().hashCode());
        result = prime * result + ((getRelNodeId() == null) ? 0 : getRelNodeId().hashCode());
        result = prime * result + ((getRelCharId() == null) ? 0 : getRelCharId().hashCode());
        result = prime * result + ((getTableColumns() == null) ? 0 : getTableColumns().hashCode());
        result = prime * result + ((getTableRows() == null) ? 0 : getTableRows().hashCode());
        result = prime * result + ((getDataFileType() == null) ? 0 : getDataFileType().hashCode());
        result = prime * result + ((getDataFileSize() == null) ? 0 : getDataFileSize().hashCode());
        result = prime * result + ((getDataFile() == null) ? 0 : getDataFile().hashCode());
        result = prime * result + ((getDataSummaryFile() == null) ? 0 : getDataSummaryFile().hashCode());
        result = prime * result + ((getTableState() == null) ? 0 : getTableState().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_data_table
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    @Override
    public void copyProperties(Object that) {
        if (this == that || that == null || this.getClass() != that.getClass() ) {
            return;
        }
        DwDataTable other = (DwDataTable) that;
        if(other.isTableIdColoured() ) {this.setTableId(other.getTableId() );}
        if(other.isTableNameColoured() ) {this.setTableName(other.getTableName() );}
        if(other.isTableTypeColoured() ) {this.setTableType(other.getTableType() );}
        if(other.isOwnerDwIdColoured() ) {this.setOwnerDwId(other.getOwnerDwId() );}
        if(other.isRelExperimentIdColoured() ) {this.setRelExperimentId(other.getRelExperimentId() );}
        if(other.isRelJobIdColoured() ) {this.setRelJobId(other.getRelJobId() );}
        if(other.isRelNodeIdColoured() ) {this.setRelNodeId(other.getRelNodeId() );}
        if(other.isRelCharIdColoured() ) {this.setRelCharId(other.getRelCharId() );}
        if(other.isTableColumnsColoured() ) {this.setTableColumns(other.getTableColumns() );}
        if(other.isTableRowsColoured() ) {this.setTableRows(other.getTableRows() );}
        if(other.isDataFileTypeColoured() ) {this.setDataFileType(other.getDataFileType() );}
        if(other.isDataFileSizeColoured() ) {this.setDataFileSize(other.getDataFileSize() );}
        if(other.isDataFileColoured() ) {this.setDataFile(other.getDataFile() );}
        if(other.isDataSummaryFileColoured() ) {this.setDataSummaryFile(other.getDataSummaryFile() );}
        if(other.isTableStateColoured() ) {this.setTableState(other.getTableState() );}
        if(other.isDescriptionColoured() ) {this.setDescription(other.getDescription() );}
        if(other.isStatusColoured() ) {this.setStatus(other.getStatus() );}
        if(other.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(other.getLastUpdateTime() );}
        if(other.isLastUpdateOperColoured() ) {this.setLastUpdateOper(other.getLastUpdateOper() );}
        if(other.isCreateTimeColoured() ) {this.setCreateTime(other.getCreateTime() );}
        if(other.isCreateOperColoured() ) {this.setCreateOper(other.getCreateOper() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_data_table
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    @Override
    public JSONObject toJSON() {
        HashMap<String, Object> hashMap = new HashMap();
        if(this.tableIdColoured) {hashMap.put("tableId", this.tableId);}
        if(this.tableNameColoured) {hashMap.put("tableName", this.tableName);}
        if(this.tableTypeColoured) {hashMap.put("tableType", this.tableType);}
        if(this.ownerDwIdColoured) {hashMap.put("ownerDwId", this.ownerDwId);}
        if(this.relExperimentIdColoured) {hashMap.put("relExperimentId", this.relExperimentId);}
        if(this.relJobIdColoured) {hashMap.put("relJobId", this.relJobId);}
        if(this.relNodeIdColoured) {hashMap.put("relNodeId", this.relNodeId);}
        if(this.relCharIdColoured) {hashMap.put("relCharId", this.relCharId);}
        if(this.tableColumnsColoured) {hashMap.put("tableColumns", this.tableColumns);}
        if(this.tableRowsColoured) {hashMap.put("tableRows", this.tableRows);}
        if(this.dataFileTypeColoured) {hashMap.put("dataFileType", this.dataFileType);}
        if(this.dataFileSizeColoured) {hashMap.put("dataFileSize", this.dataFileSize);}
        if(this.dataFileColoured) {hashMap.put("dataFile", this.dataFile);}
        if(this.dataSummaryFileColoured) {hashMap.put("dataSummaryFile", this.dataSummaryFile);}
        if(this.tableStateColoured) {hashMap.put("tableState", this.tableState);}
        if(this.descriptionColoured) {hashMap.put("description", this.description);}
        if(this.statusColoured) {hashMap.put("status", this.status);}
        if(this.lastUpdateTimeColoured) {hashMap.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOperColoured) {hashMap.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTimeColoured) {hashMap.put("createTime", this.createTime);}
        if(this.createOperColoured) {hashMap.put("createOper", this.createOper);}
        return (JSONObject) JSON.toJSON(hashMap);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dw_data_table
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    @Override
    public void clear() {
        if(this.tableIdColoured) {this.tableId = null; this.tableIdColoured = false;}
        if(this.tableNameColoured) {this.tableName = null; this.tableNameColoured = false;}
        if(this.tableTypeColoured) {this.tableType = null; this.tableTypeColoured = false;}
        if(this.ownerDwIdColoured) {this.ownerDwId = null; this.ownerDwIdColoured = false;}
        if(this.relExperimentIdColoured) {this.relExperimentId = null; this.relExperimentIdColoured = false;}
        if(this.relJobIdColoured) {this.relJobId = null; this.relJobIdColoured = false;}
        if(this.relNodeIdColoured) {this.relNodeId = null; this.relNodeIdColoured = false;}
        if(this.relCharIdColoured) {this.relCharId = null; this.relCharIdColoured = false;}
        if(this.tableColumnsColoured) {this.tableColumns = null; this.tableColumnsColoured = false;}
        if(this.tableRowsColoured) {this.tableRows = null; this.tableRowsColoured = false;}
        if(this.dataFileTypeColoured) {this.dataFileType = null; this.dataFileTypeColoured = false;}
        if(this.dataFileSizeColoured) {this.dataFileSize = null; this.dataFileSizeColoured = false;}
        if(this.dataFileColoured) {this.dataFile = null; this.dataFileColoured = false;}
        if(this.dataSummaryFileColoured) {this.dataSummaryFile = null; this.dataSummaryFileColoured = false;}
        if(this.tableStateColoured) {this.tableState = null; this.tableStateColoured = false;}
        if(this.descriptionColoured) {this.description = null; this.descriptionColoured = false;}
        if(this.statusColoured) {this.status = null; this.statusColoured = false;}
        if(this.lastUpdateTimeColoured) {this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;}
        if(this.lastUpdateOperColoured) {this.lastUpdateOper = null; this.lastUpdateOperColoured = false;}
        if(this.createTimeColoured) {this.createTime = null; this.createTimeColoured = false;}
        if(this.createOperColoured) {this.createOper = null; this.createOperColoured = false;}
        return;
    }
}