package com.yatop.lambda.base.model;

import java.io.Serializable;
import java.util.Date;

public class PrProject implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_project.PROJECT_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Long projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_project.PROJECT_CODE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String projectCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_project.PROJECT_NAME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_project.DW_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Long dwId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_project.MW_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Long mwId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_project.CACHE_EXIPRE_DAYS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Integer cacheExipreDays;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_project.DESCRIPTION
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_project.STATUS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_project.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_project.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_project.CREATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pr_project.CREATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String createOper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table pr_project
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_project.PROJECT_ID
     *
     * @return the value of pr_project.PROJECT_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_project.PROJECT_ID
     *
     * @param projectId the value for pr_project.PROJECT_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_project.PROJECT_CODE
     *
     * @return the value of pr_project.PROJECT_CODE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_project.PROJECT_CODE
     *
     * @param projectCode the value for pr_project.PROJECT_CODE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode == null ? null : projectCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_project.PROJECT_NAME
     *
     * @return the value of pr_project.PROJECT_NAME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_project.PROJECT_NAME
     *
     * @param projectName the value for pr_project.PROJECT_NAME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName == null ? null : projectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_project.DW_ID
     *
     * @return the value of pr_project.DW_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Long getDwId() {
        return dwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_project.DW_ID
     *
     * @param dwId the value for pr_project.DW_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setDwId(Long dwId) {
        this.dwId = dwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_project.MW_ID
     *
     * @return the value of pr_project.MW_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Long getMwId() {
        return mwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_project.MW_ID
     *
     * @param mwId the value for pr_project.MW_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setMwId(Long mwId) {
        this.mwId = mwId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_project.CACHE_EXIPRE_DAYS
     *
     * @return the value of pr_project.CACHE_EXIPRE_DAYS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Integer getCacheExipreDays() {
        return cacheExipreDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_project.CACHE_EXIPRE_DAYS
     *
     * @param cacheExipreDays the value for pr_project.CACHE_EXIPRE_DAYS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCacheExipreDays(Integer cacheExipreDays) {
        this.cacheExipreDays = cacheExipreDays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_project.DESCRIPTION
     *
     * @return the value of pr_project.DESCRIPTION
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_project.DESCRIPTION
     *
     * @param description the value for pr_project.DESCRIPTION
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_project.STATUS
     *
     * @return the value of pr_project.STATUS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_project.STATUS
     *
     * @param status the value for pr_project.STATUS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_project.LAST_UPDATE_TIME
     *
     * @return the value of pr_project.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_project.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for pr_project.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_project.LAST_UPDATE_OPER
     *
     * @return the value of pr_project.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_project.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for pr_project.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_project.CREATE_TIME
     *
     * @return the value of pr_project.CREATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_project.CREATE_TIME
     *
     * @param createTime the value for pr_project.CREATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pr_project.CREATE_OPER
     *
     * @return the value of pr_project.CREATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pr_project.CREATE_OPER
     *
     * @param createOper the value for pr_project.CREATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_project
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        PrProject other = (PrProject) that;
        return (this.getProjectId() == null ? other.getProjectId() == null : this.getProjectId().equals(other.getProjectId()))
            && (this.getProjectCode() == null ? other.getProjectCode() == null : this.getProjectCode().equals(other.getProjectCode()))
            && (this.getProjectName() == null ? other.getProjectName() == null : this.getProjectName().equals(other.getProjectName()))
            && (this.getDwId() == null ? other.getDwId() == null : this.getDwId().equals(other.getDwId()))
            && (this.getMwId() == null ? other.getMwId() == null : this.getMwId().equals(other.getMwId()))
            && (this.getCacheExipreDays() == null ? other.getCacheExipreDays() == null : this.getCacheExipreDays().equals(other.getCacheExipreDays()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pr_project
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProjectId() == null) ? 0 : getProjectId().hashCode());
        result = prime * result + ((getProjectCode() == null) ? 0 : getProjectCode().hashCode());
        result = prime * result + ((getProjectName() == null) ? 0 : getProjectName().hashCode());
        result = prime * result + ((getDwId() == null) ? 0 : getDwId().hashCode());
        result = prime * result + ((getMwId() == null) ? 0 : getMwId().hashCode());
        result = prime * result + ((getCacheExipreDays() == null) ? 0 : getCacheExipreDays().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }
}