package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;

public class WfCfgModulePropCtrlRel extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.CONTROL_ID
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private Long controlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.CONTROL_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean controlIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.CONTROL_VALUE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String controlValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.CONTROL_VALUE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean controlValueColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.TARGET_SELECT
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String targetSelect;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.TARGET_SELECT:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean targetSelectColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.TARGET_OBJECT
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String targetObject;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.TARGET_OBJECT:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean targetObjectColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.RELATION
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String relation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.RELATION:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean relationColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.DESCRIPTION
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.DESCRIPTION:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.STATUS
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.STATUS:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_TIME
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_OPER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.CREATE_TIME
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.CREATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.CREATE_OPER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl_rel.CREATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean createOperColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wf_cfg_module_prop_ctrl_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.CONTROL_ID
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.CONTROL_ID
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public Long getControlId() {
        return controlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.CONTROL_ID:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.CONTROL_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isControlIdColoured() {
        return controlIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.CONTROL_ID:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.CONTROL_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isControlIdNotColoured() {
        return !controlIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.CONTROL_ID
     *
     * @param controlId the value for wf_cfg_module_prop_ctrl_rel.CONTROL_ID
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setControlId(Long controlId) {
        this.controlId = controlId;
        this.controlIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.CONTROL_ID:Coloured
     *
     * @param controlIdColoured the value for wf_cfg_module_prop_ctrl_rel.CONTROL_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setControlIdColoured(boolean controlIdColoured) {
        this.controlIdColoured = controlIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.CONTROL_VALUE
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.CONTROL_VALUE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getControlValue() {
        return controlValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.CONTROL_VALUE:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.CONTROL_VALUE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isControlValueColoured() {
        return controlValueColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.CONTROL_VALUE:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.CONTROL_VALUE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isControlValueNotColoured() {
        return !controlValueColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.CONTROL_VALUE
     *
     * @param controlValue the value for wf_cfg_module_prop_ctrl_rel.CONTROL_VALUE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setControlValue(String controlValue) {
        this.controlValue = controlValue == null ? null : controlValue.trim();
        this.controlValueColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.CONTROL_VALUE:Coloured
     *
     * @param controlValueColoured the value for wf_cfg_module_prop_ctrl_rel.CONTROL_VALUE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setControlValueColoured(boolean controlValueColoured) {
        this.controlValueColoured = controlValueColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.TARGET_SELECT
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.TARGET_SELECT
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getTargetSelect() {
        return targetSelect;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.TARGET_SELECT:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.TARGET_SELECT:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isTargetSelectColoured() {
        return targetSelectColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.TARGET_SELECT:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.TARGET_SELECT:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isTargetSelectNotColoured() {
        return !targetSelectColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.TARGET_SELECT
     *
     * @param targetSelect the value for wf_cfg_module_prop_ctrl_rel.TARGET_SELECT
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setTargetSelect(String targetSelect) {
        this.targetSelect = targetSelect == null ? null : targetSelect.trim();
        this.targetSelectColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.TARGET_SELECT:Coloured
     *
     * @param targetSelectColoured the value for wf_cfg_module_prop_ctrl_rel.TARGET_SELECT:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setTargetSelectColoured(boolean targetSelectColoured) {
        this.targetSelectColoured = targetSelectColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.TARGET_OBJECT
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.TARGET_OBJECT
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getTargetObject() {
        return targetObject;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.TARGET_OBJECT:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.TARGET_OBJECT:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isTargetObjectColoured() {
        return targetObjectColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.TARGET_OBJECT:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.TARGET_OBJECT:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isTargetObjectNotColoured() {
        return !targetObjectColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.TARGET_OBJECT
     *
     * @param targetObject the value for wf_cfg_module_prop_ctrl_rel.TARGET_OBJECT
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setTargetObject(String targetObject) {
        this.targetObject = targetObject == null ? null : targetObject.trim();
        this.targetObjectColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.TARGET_OBJECT:Coloured
     *
     * @param targetObjectColoured the value for wf_cfg_module_prop_ctrl_rel.TARGET_OBJECT:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setTargetObjectColoured(boolean targetObjectColoured) {
        this.targetObjectColoured = targetObjectColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.RELATION
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.RELATION
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getRelation() {
        return relation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.RELATION:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.RELATION:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isRelationColoured() {
        return relationColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.RELATION:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.RELATION:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isRelationNotColoured() {
        return !relationColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.RELATION
     *
     * @param relation the value for wf_cfg_module_prop_ctrl_rel.RELATION
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setRelation(String relation) {
        this.relation = relation == null ? null : relation.trim();
        this.relationColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.RELATION:Coloured
     *
     * @param relationColoured the value for wf_cfg_module_prop_ctrl_rel.RELATION:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setRelationColoured(boolean relationColoured) {
        this.relationColoured = relationColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.DESCRIPTION
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.DESCRIPTION
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.DESCRIPTION:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.DESCRIPTION:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.DESCRIPTION:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.DESCRIPTION:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isDescriptionNotColoured() {
        return !descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.DESCRIPTION
     *
     * @param description the value for wf_cfg_module_prop_ctrl_rel.DESCRIPTION
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for wf_cfg_module_prop_ctrl_rel.DESCRIPTION:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.STATUS
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.STATUS
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.STATUS:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.STATUS:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.STATUS:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.STATUS:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isStatusNotColoured() {
        return !statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.STATUS
     *
     * @param status the value for wf_cfg_module_prop_ctrl_rel.STATUS
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.STATUS:Coloured
     *
     * @param statusColoured the value for wf_cfg_module_prop_ctrl_rel.STATUS:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_TIME
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_TIME
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isLastUpdateTimeNotColoured() {
        return !lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_TIME
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_OPER
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_OPER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isLastUpdateOperNotColoured() {
        return !lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_OPER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for wf_cfg_module_prop_ctrl_rel.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.CREATE_TIME
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.CREATE_TIME
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.CREATE_TIME:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.CREATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.CREATE_TIME:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.CREATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isCreateTimeNotColoured() {
        return !createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.CREATE_TIME
     *
     * @param createTime the value for wf_cfg_module_prop_ctrl_rel.CREATE_TIME
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for wf_cfg_module_prop_ctrl_rel.CREATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.CREATE_OPER
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.CREATE_OPER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.CREATE_OPER:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.CREATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl_rel.CREATE_OPER:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl_rel.CREATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isCreateOperNotColoured() {
        return !createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.CREATE_OPER
     *
     * @param createOper the value for wf_cfg_module_prop_ctrl_rel.CREATE_OPER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl_rel.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for wf_cfg_module_prop_ctrl_rel.CREATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if(!(that instanceof WfCfgModulePropCtrlRel)) {
            return false;
        }
        WfCfgModulePropCtrlRel other = (WfCfgModulePropCtrlRel) that;
        return (this.getControlId() == null ? other.getControlId() == null : this.getControlId().equals(other.getControlId()))
            && (this.getControlValue() == null ? other.getControlValue() == null : this.getControlValue().equals(other.getControlValue()))
            && (this.getTargetSelect() == null ? other.getTargetSelect() == null : this.getTargetSelect().equals(other.getTargetSelect()))
            && (this.getTargetObject() == null ? other.getTargetObject() == null : this.getTargetObject().equals(other.getTargetObject()))
            && (this.getRelation() == null ? other.getRelation() == null : this.getRelation().equals(other.getRelation()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getControlId() == null) ? 0 : getControlId().hashCode());
        result = prime * result + ((getControlValue() == null) ? 0 : getControlValue().hashCode());
        result = prime * result + ((getTargetSelect() == null) ? 0 : getTargetSelect().hashCode());
        result = prime * result + ((getTargetObject() == null) ? 0 : getTargetObject().hashCode());
        result = prime * result + ((getRelation() == null) ? 0 : getRelation().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void copyProperties(WfCfgModulePropCtrlRel that) {
        if (this == that || that == null) {
            return;
        }
        if(that.isControlIdColoured() ) {this.setControlId(that.getControlId() );}
        if(that.isControlValueColoured() ) {this.setControlValue(that.getControlValue() );}
        if(that.isTargetSelectColoured() ) {this.setTargetSelect(that.getTargetSelect() );}
        if(that.isTargetObjectColoured() ) {this.setTargetObject(that.getTargetObject() );}
        if(that.isRelationColoured() ) {this.setRelation(that.getRelation() );}
        if(that.isDescriptionColoured() ) {this.setDescription(that.getDescription() );}
        if(that.isStatusColoured() ) {this.setStatus(that.getStatus() );}
        if(that.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(that.getLastUpdateTime() );}
        if(that.isLastUpdateOperColoured() ) {this.setLastUpdateOper(that.getLastUpdateOper() );}
        if(that.isCreateTimeColoured() ) {this.setCreateTime(that.getCreateTime() );}
        if(that.isCreateOperColoured() ) {this.setCreateOper(that.getCreateOper() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public WfCfgModulePropCtrlRel makeCopy() {
        WfCfgModulePropCtrlRel copy = new WfCfgModulePropCtrlRel();
        if(this.controlId != null ) {copy.controlId = this.controlId;}
        if(this.controlValue != null ) {copy.controlValue = this.controlValue;}
        if(this.targetSelect != null ) {copy.targetSelect = this.targetSelect;}
        if(this.targetObject != null ) {copy.targetObject = this.targetObject;}
        if(this.relation != null ) {copy.relation = this.relation;}
        if(this.description != null ) {copy.description = this.description;}
        if(this.status != null ) {copy.status = this.status;}
        if(this.lastUpdateTime != null ) {copy.lastUpdateTime = this.lastUpdateTime;}
        if(this.lastUpdateOper != null ) {copy.lastUpdateOper = this.lastUpdateOper;}
        if(this.createTime != null ) {copy.createTime = this.createTime;}
        if(this.createOper != null ) {copy.createOper = this.createOper;}
        return copy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    @Override
    public JSONObject toJSON() {
        JSONObject jsonObj = new JSONObject(32, true);
        if(this.controlId != null) {jsonObj.put("controlId", this.controlId);}
        if(this.controlValue != null) {jsonObj.put("controlValue", this.controlValue);}
        if(this.targetSelect != null) {jsonObj.put("targetSelect", this.targetSelect);}
        if(this.targetObject != null) {jsonObj.put("targetObject", this.targetObject);}
        if(this.relation != null) {jsonObj.put("relation", this.relation);}
        if(this.description != null) {jsonObj.put("description", this.description);}
        if(this.status != null) {jsonObj.put("status", this.status);}
        if(this.lastUpdateTime != null) {jsonObj.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOper != null) {jsonObj.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTime != null) {jsonObj.put("createTime", this.createTime);}
        if(this.createOper != null) {jsonObj.put("createOper", this.createOper);}
        return jsonObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    @Override
    public void clear() {
         this.controlId = null; this.controlIdColoured = false;
         this.controlValue = null; this.controlValueColoured = false;
         this.targetSelect = null; this.targetSelectColoured = false;
         this.targetObject = null; this.targetObjectColoured = false;
         this.relation = null; this.relationColoured = false;
         this.description = null; this.descriptionColoured = false;
         this.status = null; this.statusColoured = false;
         this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;
         this.lastUpdateOper = null; this.lastUpdateOperColoured = false;
         this.createTime = null; this.createTimeColoured = false;
         this.createOper = null; this.createOperColoured = false;
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    @Override
    public void clearColoured() {
        this.controlIdColoured = false;
        this.controlValueColoured = false;
        this.targetSelectColoured = false;
        this.targetObjectColoured = false;
        this.relationColoured = false;
        this.descriptionColoured = false;
        this.statusColoured = false;
        this.lastUpdateTimeColoured = false;
        this.lastUpdateOperColoured = false;
        this.createTimeColoured = false;
        this.createOperColoured = false;
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl_rel
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    @Override
    public boolean isColoured() {
        if(this.controlIdColoured) return true;
        if(this.controlValueColoured) return true;
        if(this.targetSelectColoured) return true;
        if(this.targetObjectColoured) return true;
        if(this.relationColoured) return true;
        if(this.descriptionColoured) return true;
        if(this.statusColoured) return true;
        if(this.lastUpdateTimeColoured) return true;
        if(this.lastUpdateOperColoured) return true;
        if(this.createTimeColoured) return true;
        if(this.createOperColoured) return true;
        return false;
    }
}