package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;

public class WfCfgModulePropCtrl extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.CONTROL_ID
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private Long controlId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.CONTROL_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean controlIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.CONTROL_CODE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String controlCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.CONTROL_CODE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean controlCodeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.CONTROL_LABEL
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String controlLabel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.CONTROL_LABEL:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean controlLabelColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.CONTROL_TYPE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String controlType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.CONTROL_TYPE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean controlTypeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.OWNER_MODULE_ID
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private Long ownerModuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.OWNER_MODULE_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean ownerModuleIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.OWNER_TAB_ID
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private Long ownerTabId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.OWNER_TAB_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean ownerTabIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.BIND_CHAR_CODE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String bindCharCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.BIND_CHAR_CODE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean bindCharCodeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.SEQUENCE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.SEQUENCE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean sequenceColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.PLACE_HOLDER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String placeHolder;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.PLACE_HOLDER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean placeHolderColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.TOOLTIP
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String tooltip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.TOOLTIP:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean tooltipColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.LONG_TOOLTIP
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String longTooltip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.LONG_TOOLTIP:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean longTooltipColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.IS_DISABLED
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private Integer isDisabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.IS_DISABLED:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean isDisabledColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.DESCRIPTION
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.DESCRIPTION:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.STATUS
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.STATUS:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_TIME
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_OPER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.CREATE_TIME
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.CREATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.CREATE_OPER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_cfg_module_prop_ctrl.CREATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private boolean createOperColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CONTROL_ID
     *
     * @return the value of wf_cfg_module_prop_ctrl.CONTROL_ID
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public Long getControlId() {
        return controlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CONTROL_ID:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.CONTROL_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isControlIdColoured() {
        return controlIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CONTROL_ID:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.CONTROL_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isControlIdNotColoured() {
        return !controlIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.CONTROL_ID
     *
     * @param controlId the value for wf_cfg_module_prop_ctrl.CONTROL_ID
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setControlId(Long controlId) {
        this.controlId = controlId;
        this.controlIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.CONTROL_ID:Coloured
     *
     * @param controlIdColoured the value for wf_cfg_module_prop_ctrl.CONTROL_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setControlIdColoured(boolean controlIdColoured) {
        this.controlIdColoured = controlIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CONTROL_CODE
     *
     * @return the value of wf_cfg_module_prop_ctrl.CONTROL_CODE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getControlCode() {
        return controlCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CONTROL_CODE:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.CONTROL_CODE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isControlCodeColoured() {
        return controlCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CONTROL_CODE:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.CONTROL_CODE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isControlCodeNotColoured() {
        return !controlCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.CONTROL_CODE
     *
     * @param controlCode the value for wf_cfg_module_prop_ctrl.CONTROL_CODE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setControlCode(String controlCode) {
        this.controlCode = controlCode == null ? null : controlCode.trim();
        this.controlCodeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.CONTROL_CODE:Coloured
     *
     * @param controlCodeColoured the value for wf_cfg_module_prop_ctrl.CONTROL_CODE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setControlCodeColoured(boolean controlCodeColoured) {
        this.controlCodeColoured = controlCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CONTROL_LABEL
     *
     * @return the value of wf_cfg_module_prop_ctrl.CONTROL_LABEL
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getControlLabel() {
        return controlLabel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CONTROL_LABEL:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.CONTROL_LABEL:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isControlLabelColoured() {
        return controlLabelColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CONTROL_LABEL:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.CONTROL_LABEL:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isControlLabelNotColoured() {
        return !controlLabelColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.CONTROL_LABEL
     *
     * @param controlLabel the value for wf_cfg_module_prop_ctrl.CONTROL_LABEL
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setControlLabel(String controlLabel) {
        this.controlLabel = controlLabel == null ? null : controlLabel.trim();
        this.controlLabelColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.CONTROL_LABEL:Coloured
     *
     * @param controlLabelColoured the value for wf_cfg_module_prop_ctrl.CONTROL_LABEL:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setControlLabelColoured(boolean controlLabelColoured) {
        this.controlLabelColoured = controlLabelColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CONTROL_TYPE
     *
     * @return the value of wf_cfg_module_prop_ctrl.CONTROL_TYPE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getControlType() {
        return controlType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CONTROL_TYPE:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.CONTROL_TYPE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isControlTypeColoured() {
        return controlTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CONTROL_TYPE:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.CONTROL_TYPE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isControlTypeNotColoured() {
        return !controlTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.CONTROL_TYPE
     *
     * @param controlType the value for wf_cfg_module_prop_ctrl.CONTROL_TYPE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setControlType(String controlType) {
        this.controlType = controlType == null ? null : controlType.trim();
        this.controlTypeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.CONTROL_TYPE:Coloured
     *
     * @param controlTypeColoured the value for wf_cfg_module_prop_ctrl.CONTROL_TYPE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setControlTypeColoured(boolean controlTypeColoured) {
        this.controlTypeColoured = controlTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.OWNER_MODULE_ID
     *
     * @return the value of wf_cfg_module_prop_ctrl.OWNER_MODULE_ID
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public Long getOwnerModuleId() {
        return ownerModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.OWNER_MODULE_ID:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.OWNER_MODULE_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isOwnerModuleIdColoured() {
        return ownerModuleIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.OWNER_MODULE_ID:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.OWNER_MODULE_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isOwnerModuleIdNotColoured() {
        return !ownerModuleIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.OWNER_MODULE_ID
     *
     * @param ownerModuleId the value for wf_cfg_module_prop_ctrl.OWNER_MODULE_ID
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setOwnerModuleId(Long ownerModuleId) {
        this.ownerModuleId = ownerModuleId;
        this.ownerModuleIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.OWNER_MODULE_ID:Coloured
     *
     * @param ownerModuleIdColoured the value for wf_cfg_module_prop_ctrl.OWNER_MODULE_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setOwnerModuleIdColoured(boolean ownerModuleIdColoured) {
        this.ownerModuleIdColoured = ownerModuleIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.OWNER_TAB_ID
     *
     * @return the value of wf_cfg_module_prop_ctrl.OWNER_TAB_ID
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public Long getOwnerTabId() {
        return ownerTabId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.OWNER_TAB_ID:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.OWNER_TAB_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isOwnerTabIdColoured() {
        return ownerTabIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.OWNER_TAB_ID:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.OWNER_TAB_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isOwnerTabIdNotColoured() {
        return !ownerTabIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.OWNER_TAB_ID
     *
     * @param ownerTabId the value for wf_cfg_module_prop_ctrl.OWNER_TAB_ID
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setOwnerTabId(Long ownerTabId) {
        this.ownerTabId = ownerTabId;
        this.ownerTabIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.OWNER_TAB_ID:Coloured
     *
     * @param ownerTabIdColoured the value for wf_cfg_module_prop_ctrl.OWNER_TAB_ID:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setOwnerTabIdColoured(boolean ownerTabIdColoured) {
        this.ownerTabIdColoured = ownerTabIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.BIND_CHAR_CODE
     *
     * @return the value of wf_cfg_module_prop_ctrl.BIND_CHAR_CODE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getBindCharCode() {
        return bindCharCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.BIND_CHAR_CODE:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.BIND_CHAR_CODE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isBindCharCodeColoured() {
        return bindCharCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.BIND_CHAR_CODE:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.BIND_CHAR_CODE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isBindCharCodeNotColoured() {
        return !bindCharCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.BIND_CHAR_CODE
     *
     * @param bindCharCode the value for wf_cfg_module_prop_ctrl.BIND_CHAR_CODE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setBindCharCode(String bindCharCode) {
        this.bindCharCode = bindCharCode == null ? null : bindCharCode.trim();
        this.bindCharCodeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.BIND_CHAR_CODE:Coloured
     *
     * @param bindCharCodeColoured the value for wf_cfg_module_prop_ctrl.BIND_CHAR_CODE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setBindCharCodeColoured(boolean bindCharCodeColoured) {
        this.bindCharCodeColoured = bindCharCodeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.SEQUENCE
     *
     * @return the value of wf_cfg_module_prop_ctrl.SEQUENCE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.SEQUENCE:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.SEQUENCE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isSequenceColoured() {
        return sequenceColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.SEQUENCE:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.SEQUENCE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isSequenceNotColoured() {
        return !sequenceColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.SEQUENCE
     *
     * @param sequence the value for wf_cfg_module_prop_ctrl.SEQUENCE
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
        this.sequenceColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.SEQUENCE:Coloured
     *
     * @param sequenceColoured the value for wf_cfg_module_prop_ctrl.SEQUENCE:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setSequenceColoured(boolean sequenceColoured) {
        this.sequenceColoured = sequenceColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.PLACE_HOLDER
     *
     * @return the value of wf_cfg_module_prop_ctrl.PLACE_HOLDER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getPlaceHolder() {
        return placeHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.PLACE_HOLDER:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.PLACE_HOLDER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isPlaceHolderColoured() {
        return placeHolderColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.PLACE_HOLDER:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.PLACE_HOLDER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isPlaceHolderNotColoured() {
        return !placeHolderColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.PLACE_HOLDER
     *
     * @param placeHolder the value for wf_cfg_module_prop_ctrl.PLACE_HOLDER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setPlaceHolder(String placeHolder) {
        this.placeHolder = placeHolder == null ? null : placeHolder.trim();
        this.placeHolderColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.PLACE_HOLDER:Coloured
     *
     * @param placeHolderColoured the value for wf_cfg_module_prop_ctrl.PLACE_HOLDER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setPlaceHolderColoured(boolean placeHolderColoured) {
        this.placeHolderColoured = placeHolderColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.TOOLTIP
     *
     * @return the value of wf_cfg_module_prop_ctrl.TOOLTIP
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getTooltip() {
        return tooltip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.TOOLTIP:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.TOOLTIP:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isTooltipColoured() {
        return tooltipColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.TOOLTIP:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.TOOLTIP:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isTooltipNotColoured() {
        return !tooltipColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.TOOLTIP
     *
     * @param tooltip the value for wf_cfg_module_prop_ctrl.TOOLTIP
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setTooltip(String tooltip) {
        this.tooltip = tooltip == null ? null : tooltip.trim();
        this.tooltipColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.TOOLTIP:Coloured
     *
     * @param tooltipColoured the value for wf_cfg_module_prop_ctrl.TOOLTIP:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setTooltipColoured(boolean tooltipColoured) {
        this.tooltipColoured = tooltipColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.LONG_TOOLTIP
     *
     * @return the value of wf_cfg_module_prop_ctrl.LONG_TOOLTIP
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getLongTooltip() {
        return longTooltip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.LONG_TOOLTIP:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.LONG_TOOLTIP:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isLongTooltipColoured() {
        return longTooltipColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.LONG_TOOLTIP:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.LONG_TOOLTIP:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isLongTooltipNotColoured() {
        return !longTooltipColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.LONG_TOOLTIP
     *
     * @param longTooltip the value for wf_cfg_module_prop_ctrl.LONG_TOOLTIP
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setLongTooltip(String longTooltip) {
        this.longTooltip = longTooltip == null ? null : longTooltip.trim();
        this.longTooltipColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.LONG_TOOLTIP:Coloured
     *
     * @param longTooltipColoured the value for wf_cfg_module_prop_ctrl.LONG_TOOLTIP:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setLongTooltipColoured(boolean longTooltipColoured) {
        this.longTooltipColoured = longTooltipColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.IS_DISABLED
     *
     * @return the value of wf_cfg_module_prop_ctrl.IS_DISABLED
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public Integer getIsDisabled() {
        return isDisabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.IS_DISABLED:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.IS_DISABLED:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isIsDisabledColoured() {
        return isDisabledColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.IS_DISABLED:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.IS_DISABLED:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isIsDisabledNotColoured() {
        return !isDisabledColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.IS_DISABLED
     *
     * @param isDisabled the value for wf_cfg_module_prop_ctrl.IS_DISABLED
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setIsDisabled(Integer isDisabled) {
        this.isDisabled = isDisabled;
        this.isDisabledColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.IS_DISABLED:Coloured
     *
     * @param isDisabledColoured the value for wf_cfg_module_prop_ctrl.IS_DISABLED:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setIsDisabledColoured(boolean isDisabledColoured) {
        this.isDisabledColoured = isDisabledColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.DESCRIPTION
     *
     * @return the value of wf_cfg_module_prop_ctrl.DESCRIPTION
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.DESCRIPTION:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.DESCRIPTION:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.DESCRIPTION:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.DESCRIPTION:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isDescriptionNotColoured() {
        return !descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.DESCRIPTION
     *
     * @param description the value for wf_cfg_module_prop_ctrl.DESCRIPTION
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for wf_cfg_module_prop_ctrl.DESCRIPTION:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.STATUS
     *
     * @return the value of wf_cfg_module_prop_ctrl.STATUS
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.STATUS:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.STATUS:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.STATUS:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.STATUS:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isStatusNotColoured() {
        return !statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.STATUS
     *
     * @param status the value for wf_cfg_module_prop_ctrl.STATUS
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.STATUS:Coloured
     *
     * @param statusColoured the value for wf_cfg_module_prop_ctrl.STATUS:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_TIME
     *
     * @return the value of wf_cfg_module_prop_ctrl.LAST_UPDATE_TIME
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isLastUpdateTimeNotColoured() {
        return !lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wf_cfg_module_prop_ctrl.LAST_UPDATE_TIME
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for wf_cfg_module_prop_ctrl.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_OPER
     *
     * @return the value of wf_cfg_module_prop_ctrl.LAST_UPDATE_OPER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isLastUpdateOperNotColoured() {
        return !lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for wf_cfg_module_prop_ctrl.LAST_UPDATE_OPER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for wf_cfg_module_prop_ctrl.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CREATE_TIME
     *
     * @return the value of wf_cfg_module_prop_ctrl.CREATE_TIME
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CREATE_TIME:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.CREATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CREATE_TIME:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.CREATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isCreateTimeNotColoured() {
        return !createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.CREATE_TIME
     *
     * @param createTime the value for wf_cfg_module_prop_ctrl.CREATE_TIME
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for wf_cfg_module_prop_ctrl.CREATE_TIME:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CREATE_OPER
     *
     * @return the value of wf_cfg_module_prop_ctrl.CREATE_OPER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CREATE_OPER:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.CREATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_cfg_module_prop_ctrl.CREATE_OPER:Coloured
     *
     * @return the value of wf_cfg_module_prop_ctrl.CREATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public boolean isCreateOperNotColoured() {
        return !createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.CREATE_OPER
     *
     * @param createOper the value for wf_cfg_module_prop_ctrl.CREATE_OPER
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_cfg_module_prop_ctrl.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for wf_cfg_module_prop_ctrl.CREATE_OPER:Coloured
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if(!(that instanceof WfCfgModulePropCtrl)) {
            return false;
        }
        WfCfgModulePropCtrl other = (WfCfgModulePropCtrl) that;
        return (this.getControlId() == null ? other.getControlId() == null : this.getControlId().equals(other.getControlId()))
            && (this.getControlCode() == null ? other.getControlCode() == null : this.getControlCode().equals(other.getControlCode()))
            && (this.getControlLabel() == null ? other.getControlLabel() == null : this.getControlLabel().equals(other.getControlLabel()))
            && (this.getControlType() == null ? other.getControlType() == null : this.getControlType().equals(other.getControlType()))
            && (this.getOwnerModuleId() == null ? other.getOwnerModuleId() == null : this.getOwnerModuleId().equals(other.getOwnerModuleId()))
            && (this.getOwnerTabId() == null ? other.getOwnerTabId() == null : this.getOwnerTabId().equals(other.getOwnerTabId()))
            && (this.getBindCharCode() == null ? other.getBindCharCode() == null : this.getBindCharCode().equals(other.getBindCharCode()))
            && (this.getSequence() == null ? other.getSequence() == null : this.getSequence().equals(other.getSequence()))
            && (this.getPlaceHolder() == null ? other.getPlaceHolder() == null : this.getPlaceHolder().equals(other.getPlaceHolder()))
            && (this.getTooltip() == null ? other.getTooltip() == null : this.getTooltip().equals(other.getTooltip()))
            && (this.getLongTooltip() == null ? other.getLongTooltip() == null : this.getLongTooltip().equals(other.getLongTooltip()))
            && (this.getIsDisabled() == null ? other.getIsDisabled() == null : this.getIsDisabled().equals(other.getIsDisabled()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getControlId() == null) ? 0 : getControlId().hashCode());
        result = prime * result + ((getControlCode() == null) ? 0 : getControlCode().hashCode());
        result = prime * result + ((getControlLabel() == null) ? 0 : getControlLabel().hashCode());
        result = prime * result + ((getControlType() == null) ? 0 : getControlType().hashCode());
        result = prime * result + ((getOwnerModuleId() == null) ? 0 : getOwnerModuleId().hashCode());
        result = prime * result + ((getOwnerTabId() == null) ? 0 : getOwnerTabId().hashCode());
        result = prime * result + ((getBindCharCode() == null) ? 0 : getBindCharCode().hashCode());
        result = prime * result + ((getSequence() == null) ? 0 : getSequence().hashCode());
        result = prime * result + ((getPlaceHolder() == null) ? 0 : getPlaceHolder().hashCode());
        result = prime * result + ((getTooltip() == null) ? 0 : getTooltip().hashCode());
        result = prime * result + ((getLongTooltip() == null) ? 0 : getLongTooltip().hashCode());
        result = prime * result + ((getIsDisabled() == null) ? 0 : getIsDisabled().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public void copyProperties(WfCfgModulePropCtrl that) {
        if (this == that || that == null) {
            return;
        }
        if(that.isControlIdColoured() ) {this.setControlId(that.getControlId() );}
        if(that.isControlCodeColoured() ) {this.setControlCode(that.getControlCode() );}
        if(that.isControlLabelColoured() ) {this.setControlLabel(that.getControlLabel() );}
        if(that.isControlTypeColoured() ) {this.setControlType(that.getControlType() );}
        if(that.isOwnerModuleIdColoured() ) {this.setOwnerModuleId(that.getOwnerModuleId() );}
        if(that.isOwnerTabIdColoured() ) {this.setOwnerTabId(that.getOwnerTabId() );}
        if(that.isBindCharCodeColoured() ) {this.setBindCharCode(that.getBindCharCode() );}
        if(that.isSequenceColoured() ) {this.setSequence(that.getSequence() );}
        if(that.isPlaceHolderColoured() ) {this.setPlaceHolder(that.getPlaceHolder() );}
        if(that.isTooltipColoured() ) {this.setTooltip(that.getTooltip() );}
        if(that.isLongTooltipColoured() ) {this.setLongTooltip(that.getLongTooltip() );}
        if(that.isIsDisabledColoured() ) {this.setIsDisabled(that.getIsDisabled() );}
        if(that.isDescriptionColoured() ) {this.setDescription(that.getDescription() );}
        if(that.isStatusColoured() ) {this.setStatus(that.getStatus() );}
        if(that.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(that.getLastUpdateTime() );}
        if(that.isLastUpdateOperColoured() ) {this.setLastUpdateOper(that.getLastUpdateOper() );}
        if(that.isCreateTimeColoured() ) {this.setCreateTime(that.getCreateTime() );}
        if(that.isCreateOperColoured() ) {this.setCreateOper(that.getCreateOper() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    public WfCfgModulePropCtrl makeCopy() {
        WfCfgModulePropCtrl copy = new WfCfgModulePropCtrl();
        if(this.controlId != null ) {copy.controlId = this.controlId;}
        if(this.controlCode != null ) {copy.controlCode = this.controlCode;}
        if(this.controlLabel != null ) {copy.controlLabel = this.controlLabel;}
        if(this.controlType != null ) {copy.controlType = this.controlType;}
        if(this.ownerModuleId != null ) {copy.ownerModuleId = this.ownerModuleId;}
        if(this.ownerTabId != null ) {copy.ownerTabId = this.ownerTabId;}
        if(this.bindCharCode != null ) {copy.bindCharCode = this.bindCharCode;}
        if(this.sequence != null ) {copy.sequence = this.sequence;}
        if(this.placeHolder != null ) {copy.placeHolder = this.placeHolder;}
        if(this.tooltip != null ) {copy.tooltip = this.tooltip;}
        if(this.longTooltip != null ) {copy.longTooltip = this.longTooltip;}
        if(this.isDisabled != null ) {copy.isDisabled = this.isDisabled;}
        if(this.description != null ) {copy.description = this.description;}
        if(this.status != null ) {copy.status = this.status;}
        if(this.lastUpdateTime != null ) {copy.lastUpdateTime = this.lastUpdateTime;}
        if(this.lastUpdateOper != null ) {copy.lastUpdateOper = this.lastUpdateOper;}
        if(this.createTime != null ) {copy.createTime = this.createTime;}
        if(this.createOper != null ) {copy.createOper = this.createOper;}
        return copy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    @Override
    public JSONObject toJSON() {
        JSONObject jsonObj = new JSONObject(32, true);
        if(this.controlId != null) {jsonObj.put("controlId", this.controlId);}
        if(this.controlCode != null) {jsonObj.put("controlCode", this.controlCode);}
        if(this.controlLabel != null) {jsonObj.put("controlLabel", this.controlLabel);}
        if(this.controlType != null) {jsonObj.put("controlType", this.controlType);}
        if(this.ownerModuleId != null) {jsonObj.put("ownerModuleId", this.ownerModuleId);}
        if(this.ownerTabId != null) {jsonObj.put("ownerTabId", this.ownerTabId);}
        if(this.bindCharCode != null) {jsonObj.put("bindCharCode", this.bindCharCode);}
        if(this.sequence != null) {jsonObj.put("sequence", this.sequence);}
        if(this.placeHolder != null) {jsonObj.put("placeHolder", this.placeHolder);}
        if(this.tooltip != null) {jsonObj.put("tooltip", this.tooltip);}
        if(this.longTooltip != null) {jsonObj.put("longTooltip", this.longTooltip);}
        if(this.isDisabled != null) {jsonObj.put("isDisabled", this.isDisabled);}
        if(this.description != null) {jsonObj.put("description", this.description);}
        if(this.status != null) {jsonObj.put("status", this.status);}
        if(this.lastUpdateTime != null) {jsonObj.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOper != null) {jsonObj.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTime != null) {jsonObj.put("createTime", this.createTime);}
        if(this.createOper != null) {jsonObj.put("createOper", this.createOper);}
        return jsonObj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    @Override
    public void clear() {
         this.controlId = null; this.controlIdColoured = false;
         this.controlCode = null; this.controlCodeColoured = false;
         this.controlLabel = null; this.controlLabelColoured = false;
         this.controlType = null; this.controlTypeColoured = false;
         this.ownerModuleId = null; this.ownerModuleIdColoured = false;
         this.ownerTabId = null; this.ownerTabIdColoured = false;
         this.bindCharCode = null; this.bindCharCodeColoured = false;
         this.sequence = null; this.sequenceColoured = false;
         this.placeHolder = null; this.placeHolderColoured = false;
         this.tooltip = null; this.tooltipColoured = false;
         this.longTooltip = null; this.longTooltipColoured = false;
         this.isDisabled = null; this.isDisabledColoured = false;
         this.description = null; this.descriptionColoured = false;
         this.status = null; this.statusColoured = false;
         this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;
         this.lastUpdateOper = null; this.lastUpdateOperColoured = false;
         this.createTime = null; this.createTimeColoured = false;
         this.createOper = null; this.createOperColoured = false;
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    @Override
    public void clearColoured() {
        this.controlIdColoured = false;
        this.controlCodeColoured = false;
        this.controlLabelColoured = false;
        this.controlTypeColoured = false;
        this.ownerModuleIdColoured = false;
        this.ownerTabIdColoured = false;
        this.bindCharCodeColoured = false;
        this.sequenceColoured = false;
        this.placeHolderColoured = false;
        this.tooltipColoured = false;
        this.longTooltipColoured = false;
        this.isDisabledColoured = false;
        this.descriptionColoured = false;
        this.statusColoured = false;
        this.lastUpdateTimeColoured = false;
        this.lastUpdateOperColoured = false;
        this.createTimeColoured = false;
        this.createOperColoured = false;
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_cfg_module_prop_ctrl
     *
     * @mbg.generated Fri Mar 15 15:22:18 CST 2019
     */
    @Override
    public boolean isColoured() {
        if(this.controlIdColoured) return true;
        if(this.controlCodeColoured) return true;
        if(this.controlLabelColoured) return true;
        if(this.controlTypeColoured) return true;
        if(this.ownerModuleIdColoured) return true;
        if(this.ownerTabIdColoured) return true;
        if(this.bindCharCodeColoured) return true;
        if(this.sequenceColoured) return true;
        if(this.placeHolderColoured) return true;
        if(this.tooltipColoured) return true;
        if(this.longTooltipColoured) return true;
        if(this.isDisabledColoured) return true;
        if(this.descriptionColoured) return true;
        if(this.statusColoured) return true;
        if(this.lastUpdateTimeColoured) return true;
        if(this.lastUpdateOperColoured) return true;
        if(this.createTimeColoured) return true;
        if(this.createOperColoured) return true;
        return false;
    }
}