package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;

public class WfCodeScript extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.SCRIPT_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long scriptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.SCRIPT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean scriptIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.SCRIPT_NAME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private String scriptName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.SCRIPT_NAME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean scriptNameColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.SCRIPT_TYPE
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Integer scriptType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.SCRIPT_TYPE:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean scriptTypeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.OWNER_PROJECT_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long ownerProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean ownerProjectIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.REL_FLOW_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long relFlowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.REL_FLOW_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean relFlowIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.REL_SNAPSHOT_VERSION
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long relSnapshotVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.REL_SNAPSHOT_VERSION:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean relSnapshotVersionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.REL_JOB_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long relJobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.REL_JOB_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean relJobIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.REL_NODE_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long relNodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.REL_NODE_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean relNodeIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.REL_CHAR_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long relCharId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.REL_CHAR_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean relCharIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.SCRIPT_STATE
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Integer scriptState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.SCRIPT_STATE:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean scriptStateColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.DESCRIPTION
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.STATUS
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.STATUS:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.LAST_UPDATE_OPER
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.CREATE_TIME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.CREATE_OPER
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean createOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.SCRIPT_CONTENT
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private String scriptContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_code_script.SCRIPT_CONTENT:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean scriptContentColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wf_code_script
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.SCRIPT_ID
     *
     * @return the value of wf_code_script.SCRIPT_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getScriptId() {
        return scriptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.SCRIPT_ID:Coloured
     *
     * @return the value of wf_code_script.SCRIPT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isScriptIdColoured() {
        return scriptIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.SCRIPT_ID
     *
     * @param scriptId the value for wf_code_script.SCRIPT_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setScriptId(Long scriptId) {
        this.scriptId = scriptId;
        this.scriptIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.SCRIPT_ID:Coloured
     *
     * @param scriptIdColoured the value for wf_code_script.SCRIPT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setScriptIdColoured(boolean scriptIdColoured) {
        this.scriptIdColoured = scriptIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.SCRIPT_NAME
     *
     * @return the value of wf_code_script.SCRIPT_NAME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public String getScriptName() {
        return scriptName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.SCRIPT_NAME:Coloured
     *
     * @return the value of wf_code_script.SCRIPT_NAME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isScriptNameColoured() {
        return scriptNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.SCRIPT_NAME
     *
     * @param scriptName the value for wf_code_script.SCRIPT_NAME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setScriptName(String scriptName) {
        this.scriptName = scriptName == null ? null : scriptName.trim();
        this.scriptNameColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.SCRIPT_NAME:Coloured
     *
     * @param scriptNameColoured the value for wf_code_script.SCRIPT_NAME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setScriptNameColoured(boolean scriptNameColoured) {
        this.scriptNameColoured = scriptNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.SCRIPT_TYPE
     *
     * @return the value of wf_code_script.SCRIPT_TYPE
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Integer getScriptType() {
        return scriptType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.SCRIPT_TYPE:Coloured
     *
     * @return the value of wf_code_script.SCRIPT_TYPE:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isScriptTypeColoured() {
        return scriptTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.SCRIPT_TYPE
     *
     * @param scriptType the value for wf_code_script.SCRIPT_TYPE
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setScriptType(Integer scriptType) {
        this.scriptType = scriptType;
        this.scriptTypeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.SCRIPT_TYPE:Coloured
     *
     * @param scriptTypeColoured the value for wf_code_script.SCRIPT_TYPE:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setScriptTypeColoured(boolean scriptTypeColoured) {
        this.scriptTypeColoured = scriptTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.OWNER_PROJECT_ID
     *
     * @return the value of wf_code_script.OWNER_PROJECT_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getOwnerProjectId() {
        return ownerProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.OWNER_PROJECT_ID:Coloured
     *
     * @return the value of wf_code_script.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isOwnerProjectIdColoured() {
        return ownerProjectIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.OWNER_PROJECT_ID
     *
     * @param ownerProjectId the value for wf_code_script.OWNER_PROJECT_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setOwnerProjectId(Long ownerProjectId) {
        this.ownerProjectId = ownerProjectId;
        this.ownerProjectIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.OWNER_PROJECT_ID:Coloured
     *
     * @param ownerProjectIdColoured the value for wf_code_script.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setOwnerProjectIdColoured(boolean ownerProjectIdColoured) {
        this.ownerProjectIdColoured = ownerProjectIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.REL_FLOW_ID
     *
     * @return the value of wf_code_script.REL_FLOW_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getRelFlowId() {
        return relFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.REL_FLOW_ID:Coloured
     *
     * @return the value of wf_code_script.REL_FLOW_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isRelFlowIdColoured() {
        return relFlowIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.REL_FLOW_ID
     *
     * @param relFlowId the value for wf_code_script.REL_FLOW_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setRelFlowId(Long relFlowId) {
        this.relFlowId = relFlowId;
        this.relFlowIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.REL_FLOW_ID:Coloured
     *
     * @param relFlowIdColoured the value for wf_code_script.REL_FLOW_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setRelFlowIdColoured(boolean relFlowIdColoured) {
        this.relFlowIdColoured = relFlowIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.REL_SNAPSHOT_VERSION
     *
     * @return the value of wf_code_script.REL_SNAPSHOT_VERSION
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getRelSnapshotVersion() {
        return relSnapshotVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.REL_SNAPSHOT_VERSION:Coloured
     *
     * @return the value of wf_code_script.REL_SNAPSHOT_VERSION:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isRelSnapshotVersionColoured() {
        return relSnapshotVersionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.REL_SNAPSHOT_VERSION
     *
     * @param relSnapshotVersion the value for wf_code_script.REL_SNAPSHOT_VERSION
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setRelSnapshotVersion(Long relSnapshotVersion) {
        this.relSnapshotVersion = relSnapshotVersion;
        this.relSnapshotVersionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.REL_SNAPSHOT_VERSION:Coloured
     *
     * @param relSnapshotVersionColoured the value for wf_code_script.REL_SNAPSHOT_VERSION:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setRelSnapshotVersionColoured(boolean relSnapshotVersionColoured) {
        this.relSnapshotVersionColoured = relSnapshotVersionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.REL_JOB_ID
     *
     * @return the value of wf_code_script.REL_JOB_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getRelJobId() {
        return relJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.REL_JOB_ID:Coloured
     *
     * @return the value of wf_code_script.REL_JOB_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isRelJobIdColoured() {
        return relJobIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.REL_JOB_ID
     *
     * @param relJobId the value for wf_code_script.REL_JOB_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setRelJobId(Long relJobId) {
        this.relJobId = relJobId;
        this.relJobIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.REL_JOB_ID:Coloured
     *
     * @param relJobIdColoured the value for wf_code_script.REL_JOB_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setRelJobIdColoured(boolean relJobIdColoured) {
        this.relJobIdColoured = relJobIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.REL_NODE_ID
     *
     * @return the value of wf_code_script.REL_NODE_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getRelNodeId() {
        return relNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.REL_NODE_ID:Coloured
     *
     * @return the value of wf_code_script.REL_NODE_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isRelNodeIdColoured() {
        return relNodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.REL_NODE_ID
     *
     * @param relNodeId the value for wf_code_script.REL_NODE_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setRelNodeId(Long relNodeId) {
        this.relNodeId = relNodeId;
        this.relNodeIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.REL_NODE_ID:Coloured
     *
     * @param relNodeIdColoured the value for wf_code_script.REL_NODE_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setRelNodeIdColoured(boolean relNodeIdColoured) {
        this.relNodeIdColoured = relNodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.REL_CHAR_ID
     *
     * @return the value of wf_code_script.REL_CHAR_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getRelCharId() {
        return relCharId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.REL_CHAR_ID:Coloured
     *
     * @return the value of wf_code_script.REL_CHAR_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isRelCharIdColoured() {
        return relCharIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.REL_CHAR_ID
     *
     * @param relCharId the value for wf_code_script.REL_CHAR_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setRelCharId(Long relCharId) {
        this.relCharId = relCharId;
        this.relCharIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.REL_CHAR_ID:Coloured
     *
     * @param relCharIdColoured the value for wf_code_script.REL_CHAR_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setRelCharIdColoured(boolean relCharIdColoured) {
        this.relCharIdColoured = relCharIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.SCRIPT_STATE
     *
     * @return the value of wf_code_script.SCRIPT_STATE
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Integer getScriptState() {
        return scriptState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.SCRIPT_STATE:Coloured
     *
     * @return the value of wf_code_script.SCRIPT_STATE:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isScriptStateColoured() {
        return scriptStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.SCRIPT_STATE
     *
     * @param scriptState the value for wf_code_script.SCRIPT_STATE
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setScriptState(Integer scriptState) {
        this.scriptState = scriptState;
        this.scriptStateColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.SCRIPT_STATE:Coloured
     *
     * @param scriptStateColoured the value for wf_code_script.SCRIPT_STATE:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setScriptStateColoured(boolean scriptStateColoured) {
        this.scriptStateColoured = scriptStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.DESCRIPTION
     *
     * @return the value of wf_code_script.DESCRIPTION
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.DESCRIPTION:Coloured
     *
     * @return the value of wf_code_script.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.DESCRIPTION
     *
     * @param description the value for wf_code_script.DESCRIPTION
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for wf_code_script.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.STATUS
     *
     * @return the value of wf_code_script.STATUS
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.STATUS:Coloured
     *
     * @return the value of wf_code_script.STATUS:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.STATUS
     *
     * @param status the value for wf_code_script.STATUS
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.STATUS:Coloured
     *
     * @param statusColoured the value for wf_code_script.STATUS:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.LAST_UPDATE_TIME
     *
     * @return the value of wf_code_script.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of wf_code_script.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wf_code_script.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for wf_code_script.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.LAST_UPDATE_OPER
     *
     * @return the value of wf_code_script.LAST_UPDATE_OPER
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of wf_code_script.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for wf_code_script.LAST_UPDATE_OPER
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for wf_code_script.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.CREATE_TIME
     *
     * @return the value of wf_code_script.CREATE_TIME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.CREATE_TIME:Coloured
     *
     * @return the value of wf_code_script.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.CREATE_TIME
     *
     * @param createTime the value for wf_code_script.CREATE_TIME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for wf_code_script.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.CREATE_OPER
     *
     * @return the value of wf_code_script.CREATE_OPER
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.CREATE_OPER:Coloured
     *
     * @return the value of wf_code_script.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.CREATE_OPER
     *
     * @param createOper the value for wf_code_script.CREATE_OPER
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for wf_code_script.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.SCRIPT_CONTENT
     *
     * @return the value of wf_code_script.SCRIPT_CONTENT
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public String getScriptContent() {
        return scriptContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_code_script.SCRIPT_CONTENT:Coloured
     *
     * @return the value of wf_code_script.SCRIPT_CONTENT:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isScriptContentColoured() {
        return scriptContentColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.SCRIPT_CONTENT
     *
     * @param scriptContent the value for wf_code_script.SCRIPT_CONTENT
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setScriptContent(String scriptContent) {
        this.scriptContent = scriptContent == null ? null : scriptContent.trim();
        this.scriptContentColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_code_script.SCRIPT_CONTENT:Coloured
     *
     * @param scriptContentColoured the value for wf_code_script.SCRIPT_CONTENT:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setScriptContentColoured(boolean scriptContentColoured) {
        this.scriptContentColoured = scriptContentColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_code_script
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WfCodeScript other = (WfCodeScript) that;
        return (this.getScriptId() == null ? other.getScriptId() == null : this.getScriptId().equals(other.getScriptId()))
            && (this.getScriptName() == null ? other.getScriptName() == null : this.getScriptName().equals(other.getScriptName()))
            && (this.getScriptType() == null ? other.getScriptType() == null : this.getScriptType().equals(other.getScriptType()))
            && (this.getOwnerProjectId() == null ? other.getOwnerProjectId() == null : this.getOwnerProjectId().equals(other.getOwnerProjectId()))
            && (this.getRelFlowId() == null ? other.getRelFlowId() == null : this.getRelFlowId().equals(other.getRelFlowId()))
            && (this.getRelSnapshotVersion() == null ? other.getRelSnapshotVersion() == null : this.getRelSnapshotVersion().equals(other.getRelSnapshotVersion()))
            && (this.getRelJobId() == null ? other.getRelJobId() == null : this.getRelJobId().equals(other.getRelJobId()))
            && (this.getRelNodeId() == null ? other.getRelNodeId() == null : this.getRelNodeId().equals(other.getRelNodeId()))
            && (this.getRelCharId() == null ? other.getRelCharId() == null : this.getRelCharId().equals(other.getRelCharId()))
            && (this.getScriptState() == null ? other.getScriptState() == null : this.getScriptState().equals(other.getScriptState()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()))
            && (this.getScriptContent() == null ? other.getScriptContent() == null : this.getScriptContent().equals(other.getScriptContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_code_script
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getScriptId() == null) ? 0 : getScriptId().hashCode());
        result = prime * result + ((getScriptName() == null) ? 0 : getScriptName().hashCode());
        result = prime * result + ((getScriptType() == null) ? 0 : getScriptType().hashCode());
        result = prime * result + ((getOwnerProjectId() == null) ? 0 : getOwnerProjectId().hashCode());
        result = prime * result + ((getRelFlowId() == null) ? 0 : getRelFlowId().hashCode());
        result = prime * result + ((getRelSnapshotVersion() == null) ? 0 : getRelSnapshotVersion().hashCode());
        result = prime * result + ((getRelJobId() == null) ? 0 : getRelJobId().hashCode());
        result = prime * result + ((getRelNodeId() == null) ? 0 : getRelNodeId().hashCode());
        result = prime * result + ((getRelCharId() == null) ? 0 : getRelCharId().hashCode());
        result = prime * result + ((getScriptState() == null) ? 0 : getScriptState().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        result = prime * result + ((getScriptContent() == null) ? 0 : getScriptContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_code_script
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    @Override
    public void copyProperties(Object that) {
        if (this == that || that == null || this.getClass() != that.getClass() ) {
            return;
        }
        WfCodeScript other = (WfCodeScript) that;
        if(other.isScriptIdColoured() ) {this.setScriptId(other.getScriptId() );}
        if(other.isScriptNameColoured() ) {this.setScriptName(other.getScriptName() );}
        if(other.isScriptTypeColoured() ) {this.setScriptType(other.getScriptType() );}
        if(other.isOwnerProjectIdColoured() ) {this.setOwnerProjectId(other.getOwnerProjectId() );}
        if(other.isRelFlowIdColoured() ) {this.setRelFlowId(other.getRelFlowId() );}
        if(other.isRelSnapshotVersionColoured() ) {this.setRelSnapshotVersion(other.getRelSnapshotVersion() );}
        if(other.isRelJobIdColoured() ) {this.setRelJobId(other.getRelJobId() );}
        if(other.isRelNodeIdColoured() ) {this.setRelNodeId(other.getRelNodeId() );}
        if(other.isRelCharIdColoured() ) {this.setRelCharId(other.getRelCharId() );}
        if(other.isScriptStateColoured() ) {this.setScriptState(other.getScriptState() );}
        if(other.isDescriptionColoured() ) {this.setDescription(other.getDescription() );}
        if(other.isStatusColoured() ) {this.setStatus(other.getStatus() );}
        if(other.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(other.getLastUpdateTime() );}
        if(other.isLastUpdateOperColoured() ) {this.setLastUpdateOper(other.getLastUpdateOper() );}
        if(other.isCreateTimeColoured() ) {this.setCreateTime(other.getCreateTime() );}
        if(other.isCreateOperColoured() ) {this.setCreateOper(other.getCreateOper() );}
        if(other.isScriptContentColoured() ) {this.setScriptContent(other.getScriptContent() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_code_script
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    @Override
    public JSONObject toJSON() {
        HashMap<String, Object> hashMap = new HashMap();
        if(this.scriptIdColoured) {hashMap.put("scriptId", this.scriptId);}
        if(this.scriptNameColoured) {hashMap.put("scriptName", this.scriptName);}
        if(this.scriptTypeColoured) {hashMap.put("scriptType", this.scriptType);}
        if(this.ownerProjectIdColoured) {hashMap.put("ownerProjectId", this.ownerProjectId);}
        if(this.relFlowIdColoured) {hashMap.put("relFlowId", this.relFlowId);}
        if(this.relSnapshotVersionColoured) {hashMap.put("relSnapshotVersion", this.relSnapshotVersion);}
        if(this.relJobIdColoured) {hashMap.put("relJobId", this.relJobId);}
        if(this.relNodeIdColoured) {hashMap.put("relNodeId", this.relNodeId);}
        if(this.relCharIdColoured) {hashMap.put("relCharId", this.relCharId);}
        if(this.scriptStateColoured) {hashMap.put("scriptState", this.scriptState);}
        if(this.descriptionColoured) {hashMap.put("description", this.description);}
        if(this.statusColoured) {hashMap.put("status", this.status);}
        if(this.lastUpdateTimeColoured) {hashMap.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOperColoured) {hashMap.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTimeColoured) {hashMap.put("createTime", this.createTime);}
        if(this.createOperColoured) {hashMap.put("createOper", this.createOper);}
        if(this.scriptContentColoured) {hashMap.put("scriptContent", this.scriptContent);}
        return (JSONObject) JSON.toJSON(hashMap);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_code_script
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    @Override
    public void clear() {
        if(this.scriptIdColoured) {this.scriptId = null; this.scriptIdColoured = false;}
        if(this.scriptNameColoured) {this.scriptName = null; this.scriptNameColoured = false;}
        if(this.scriptTypeColoured) {this.scriptType = null; this.scriptTypeColoured = false;}
        if(this.ownerProjectIdColoured) {this.ownerProjectId = null; this.ownerProjectIdColoured = false;}
        if(this.relFlowIdColoured) {this.relFlowId = null; this.relFlowIdColoured = false;}
        if(this.relSnapshotVersionColoured) {this.relSnapshotVersion = null; this.relSnapshotVersionColoured = false;}
        if(this.relJobIdColoured) {this.relJobId = null; this.relJobIdColoured = false;}
        if(this.relNodeIdColoured) {this.relNodeId = null; this.relNodeIdColoured = false;}
        if(this.relCharIdColoured) {this.relCharId = null; this.relCharIdColoured = false;}
        if(this.scriptStateColoured) {this.scriptState = null; this.scriptStateColoured = false;}
        if(this.descriptionColoured) {this.description = null; this.descriptionColoured = false;}
        if(this.statusColoured) {this.status = null; this.statusColoured = false;}
        if(this.lastUpdateTimeColoured) {this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;}
        if(this.lastUpdateOperColoured) {this.lastUpdateOper = null; this.lastUpdateOperColoured = false;}
        if(this.createTimeColoured) {this.createTime = null; this.createTimeColoured = false;}
        if(this.createOperColoured) {this.createOper = null; this.createOperColoured = false;}
        if(this.scriptContentColoured) {this.scriptContent = null; this.scriptContentColoured = false;}
        return;
    }
}