package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;

public class WfExecutionTask extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_ID
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean taskIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_NAME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private String taskName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_NAME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean taskNameColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.OWNER_JOB_ID
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private Long ownerJobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.OWNER_JOB_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean ownerJobIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.SEQUENCE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.SEQUENCE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean sequenceColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.REL_NODE_ID
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private Long relNodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.REL_NODE_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean relNodeIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.ENGINE_TYPE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private String engineType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.ENGINE_TYPE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean engineTypeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.EXTERNAL_ID
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private String externalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.EXTERNAL_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean externalIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.SUBMIT_FILE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private String submitFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.SUBMIT_FILE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean submitFileColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.RETURN_FILE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private String returnFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.RETURN_FILE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean returnFileColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.LOG_FILE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private String logFile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.LOG_FILE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean logFileColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.COST_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private Long costTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.COST_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean costTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_START_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private Date taskStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_START_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean taskStartTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_END_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private Date taskEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_END_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean taskEndTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_PROGRESS
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private Integer taskProgress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_PROGRESS:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean taskProgressColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_STATE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private Integer taskState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_STATE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean taskStateColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.DESCRIPTION
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.DESCRIPTION:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.STATUS
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.STATUS:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.CREATE_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.CREATE_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.CREATE_OPER
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.CREATE_OPER:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean createOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_CONTEXT
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private String taskContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task.TASK_CONTEXT:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private boolean taskContextColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wf_execution_task
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_ID
     *
     * @return the value of wf_execution_task.TASK_ID
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_ID:Coloured
     *
     * @return the value of wf_execution_task.TASK_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskIdColoured() {
        return taskIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_ID:Coloured
     *
     * @return the value of wf_execution_task.TASK_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskIdNotColoured() {
        return !taskIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_ID
     *
     * @param taskId the value for wf_execution_task.TASK_ID
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
        this.taskIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_ID:Coloured
     *
     * @param taskIdColoured the value for wf_execution_task.TASK_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskIdColoured(boolean taskIdColoured) {
        this.taskIdColoured = taskIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_NAME
     *
     * @return the value of wf_execution_task.TASK_NAME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public String getTaskName() {
        return taskName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_NAME:Coloured
     *
     * @return the value of wf_execution_task.TASK_NAME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskNameColoured() {
        return taskNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_NAME:Coloured
     *
     * @return the value of wf_execution_task.TASK_NAME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskNameNotColoured() {
        return !taskNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_NAME
     *
     * @param taskName the value for wf_execution_task.TASK_NAME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskName(String taskName) {
        this.taskName = taskName == null ? null : taskName.trim();
        this.taskNameColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_NAME:Coloured
     *
     * @param taskNameColoured the value for wf_execution_task.TASK_NAME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskNameColoured(boolean taskNameColoured) {
        this.taskNameColoured = taskNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.OWNER_JOB_ID
     *
     * @return the value of wf_execution_task.OWNER_JOB_ID
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public Long getOwnerJobId() {
        return ownerJobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.OWNER_JOB_ID:Coloured
     *
     * @return the value of wf_execution_task.OWNER_JOB_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isOwnerJobIdColoured() {
        return ownerJobIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.OWNER_JOB_ID:Coloured
     *
     * @return the value of wf_execution_task.OWNER_JOB_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isOwnerJobIdNotColoured() {
        return !ownerJobIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.OWNER_JOB_ID
     *
     * @param ownerJobId the value for wf_execution_task.OWNER_JOB_ID
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setOwnerJobId(Long ownerJobId) {
        this.ownerJobId = ownerJobId;
        this.ownerJobIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.OWNER_JOB_ID:Coloured
     *
     * @param ownerJobIdColoured the value for wf_execution_task.OWNER_JOB_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setOwnerJobIdColoured(boolean ownerJobIdColoured) {
        this.ownerJobIdColoured = ownerJobIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.SEQUENCE
     *
     * @return the value of wf_execution_task.SEQUENCE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.SEQUENCE:Coloured
     *
     * @return the value of wf_execution_task.SEQUENCE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isSequenceColoured() {
        return sequenceColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.SEQUENCE:Coloured
     *
     * @return the value of wf_execution_task.SEQUENCE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isSequenceNotColoured() {
        return !sequenceColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.SEQUENCE
     *
     * @param sequence the value for wf_execution_task.SEQUENCE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
        this.sequenceColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.SEQUENCE:Coloured
     *
     * @param sequenceColoured the value for wf_execution_task.SEQUENCE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setSequenceColoured(boolean sequenceColoured) {
        this.sequenceColoured = sequenceColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.REL_NODE_ID
     *
     * @return the value of wf_execution_task.REL_NODE_ID
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public Long getRelNodeId() {
        return relNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.REL_NODE_ID:Coloured
     *
     * @return the value of wf_execution_task.REL_NODE_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isRelNodeIdColoured() {
        return relNodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.REL_NODE_ID:Coloured
     *
     * @return the value of wf_execution_task.REL_NODE_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isRelNodeIdNotColoured() {
        return !relNodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.REL_NODE_ID
     *
     * @param relNodeId the value for wf_execution_task.REL_NODE_ID
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setRelNodeId(Long relNodeId) {
        this.relNodeId = relNodeId;
        this.relNodeIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.REL_NODE_ID:Coloured
     *
     * @param relNodeIdColoured the value for wf_execution_task.REL_NODE_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setRelNodeIdColoured(boolean relNodeIdColoured) {
        this.relNodeIdColoured = relNodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.ENGINE_TYPE
     *
     * @return the value of wf_execution_task.ENGINE_TYPE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public String getEngineType() {
        return engineType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.ENGINE_TYPE:Coloured
     *
     * @return the value of wf_execution_task.ENGINE_TYPE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isEngineTypeColoured() {
        return engineTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.ENGINE_TYPE:Coloured
     *
     * @return the value of wf_execution_task.ENGINE_TYPE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isEngineTypeNotColoured() {
        return !engineTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.ENGINE_TYPE
     *
     * @param engineType the value for wf_execution_task.ENGINE_TYPE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setEngineType(String engineType) {
        this.engineType = engineType == null ? null : engineType.trim();
        this.engineTypeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.ENGINE_TYPE:Coloured
     *
     * @param engineTypeColoured the value for wf_execution_task.ENGINE_TYPE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setEngineTypeColoured(boolean engineTypeColoured) {
        this.engineTypeColoured = engineTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.EXTERNAL_ID
     *
     * @return the value of wf_execution_task.EXTERNAL_ID
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public String getExternalId() {
        return externalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.EXTERNAL_ID:Coloured
     *
     * @return the value of wf_execution_task.EXTERNAL_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isExternalIdColoured() {
        return externalIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.EXTERNAL_ID:Coloured
     *
     * @return the value of wf_execution_task.EXTERNAL_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isExternalIdNotColoured() {
        return !externalIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.EXTERNAL_ID
     *
     * @param externalId the value for wf_execution_task.EXTERNAL_ID
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setExternalId(String externalId) {
        this.externalId = externalId == null ? null : externalId.trim();
        this.externalIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.EXTERNAL_ID:Coloured
     *
     * @param externalIdColoured the value for wf_execution_task.EXTERNAL_ID:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setExternalIdColoured(boolean externalIdColoured) {
        this.externalIdColoured = externalIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.SUBMIT_FILE
     *
     * @return the value of wf_execution_task.SUBMIT_FILE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public String getSubmitFile() {
        return submitFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.SUBMIT_FILE:Coloured
     *
     * @return the value of wf_execution_task.SUBMIT_FILE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isSubmitFileColoured() {
        return submitFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.SUBMIT_FILE:Coloured
     *
     * @return the value of wf_execution_task.SUBMIT_FILE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isSubmitFileNotColoured() {
        return !submitFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.SUBMIT_FILE
     *
     * @param submitFile the value for wf_execution_task.SUBMIT_FILE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setSubmitFile(String submitFile) {
        this.submitFile = submitFile == null ? null : submitFile.trim();
        this.submitFileColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.SUBMIT_FILE:Coloured
     *
     * @param submitFileColoured the value for wf_execution_task.SUBMIT_FILE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setSubmitFileColoured(boolean submitFileColoured) {
        this.submitFileColoured = submitFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.RETURN_FILE
     *
     * @return the value of wf_execution_task.RETURN_FILE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public String getReturnFile() {
        return returnFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.RETURN_FILE:Coloured
     *
     * @return the value of wf_execution_task.RETURN_FILE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isReturnFileColoured() {
        return returnFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.RETURN_FILE:Coloured
     *
     * @return the value of wf_execution_task.RETURN_FILE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isReturnFileNotColoured() {
        return !returnFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.RETURN_FILE
     *
     * @param returnFile the value for wf_execution_task.RETURN_FILE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setReturnFile(String returnFile) {
        this.returnFile = returnFile == null ? null : returnFile.trim();
        this.returnFileColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.RETURN_FILE:Coloured
     *
     * @param returnFileColoured the value for wf_execution_task.RETURN_FILE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setReturnFileColoured(boolean returnFileColoured) {
        this.returnFileColoured = returnFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.LOG_FILE
     *
     * @return the value of wf_execution_task.LOG_FILE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public String getLogFile() {
        return logFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.LOG_FILE:Coloured
     *
     * @return the value of wf_execution_task.LOG_FILE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isLogFileColoured() {
        return logFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.LOG_FILE:Coloured
     *
     * @return the value of wf_execution_task.LOG_FILE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isLogFileNotColoured() {
        return !logFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.LOG_FILE
     *
     * @param logFile the value for wf_execution_task.LOG_FILE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setLogFile(String logFile) {
        this.logFile = logFile == null ? null : logFile.trim();
        this.logFileColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.LOG_FILE:Coloured
     *
     * @param logFileColoured the value for wf_execution_task.LOG_FILE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setLogFileColoured(boolean logFileColoured) {
        this.logFileColoured = logFileColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.COST_TIME
     *
     * @return the value of wf_execution_task.COST_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public Long getCostTime() {
        return costTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.COST_TIME:Coloured
     *
     * @return the value of wf_execution_task.COST_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isCostTimeColoured() {
        return costTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.COST_TIME:Coloured
     *
     * @return the value of wf_execution_task.COST_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isCostTimeNotColoured() {
        return !costTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.COST_TIME
     *
     * @param costTime the value for wf_execution_task.COST_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setCostTime(Long costTime) {
        this.costTime = costTime;
        this.costTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.COST_TIME:Coloured
     *
     * @param costTimeColoured the value for wf_execution_task.COST_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setCostTimeColoured(boolean costTimeColoured) {
        this.costTimeColoured = costTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_START_TIME
     *
     * @return the value of wf_execution_task.TASK_START_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public Date getTaskStartTime() {
        return taskStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_START_TIME:Coloured
     *
     * @return the value of wf_execution_task.TASK_START_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskStartTimeColoured() {
        return taskStartTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_START_TIME:Coloured
     *
     * @return the value of wf_execution_task.TASK_START_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskStartTimeNotColoured() {
        return !taskStartTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_START_TIME
     *
     * @param taskStartTime the value for wf_execution_task.TASK_START_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskStartTime(Date taskStartTime) {
        this.taskStartTime = taskStartTime;
        this.taskStartTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_START_TIME:Coloured
     *
     * @param taskStartTimeColoured the value for wf_execution_task.TASK_START_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskStartTimeColoured(boolean taskStartTimeColoured) {
        this.taskStartTimeColoured = taskStartTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_END_TIME
     *
     * @return the value of wf_execution_task.TASK_END_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public Date getTaskEndTime() {
        return taskEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_END_TIME:Coloured
     *
     * @return the value of wf_execution_task.TASK_END_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskEndTimeColoured() {
        return taskEndTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_END_TIME:Coloured
     *
     * @return the value of wf_execution_task.TASK_END_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskEndTimeNotColoured() {
        return !taskEndTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_END_TIME
     *
     * @param taskEndTime the value for wf_execution_task.TASK_END_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskEndTime(Date taskEndTime) {
        this.taskEndTime = taskEndTime;
        this.taskEndTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_END_TIME:Coloured
     *
     * @param taskEndTimeColoured the value for wf_execution_task.TASK_END_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskEndTimeColoured(boolean taskEndTimeColoured) {
        this.taskEndTimeColoured = taskEndTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_PROGRESS
     *
     * @return the value of wf_execution_task.TASK_PROGRESS
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public Integer getTaskProgress() {
        return taskProgress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_PROGRESS:Coloured
     *
     * @return the value of wf_execution_task.TASK_PROGRESS:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskProgressColoured() {
        return taskProgressColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_PROGRESS:Coloured
     *
     * @return the value of wf_execution_task.TASK_PROGRESS:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskProgressNotColoured() {
        return !taskProgressColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_PROGRESS
     *
     * @param taskProgress the value for wf_execution_task.TASK_PROGRESS
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskProgress(Integer taskProgress) {
        this.taskProgress = taskProgress;
        this.taskProgressColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_PROGRESS:Coloured
     *
     * @param taskProgressColoured the value for wf_execution_task.TASK_PROGRESS:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskProgressColoured(boolean taskProgressColoured) {
        this.taskProgressColoured = taskProgressColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_STATE
     *
     * @return the value of wf_execution_task.TASK_STATE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public Integer getTaskState() {
        return taskState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_STATE:Coloured
     *
     * @return the value of wf_execution_task.TASK_STATE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskStateColoured() {
        return taskStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_STATE:Coloured
     *
     * @return the value of wf_execution_task.TASK_STATE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskStateNotColoured() {
        return !taskStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_STATE
     *
     * @param taskState the value for wf_execution_task.TASK_STATE
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskState(Integer taskState) {
        this.taskState = taskState;
        this.taskStateColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_STATE:Coloured
     *
     * @param taskStateColoured the value for wf_execution_task.TASK_STATE:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskStateColoured(boolean taskStateColoured) {
        this.taskStateColoured = taskStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.DESCRIPTION
     *
     * @return the value of wf_execution_task.DESCRIPTION
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.DESCRIPTION:Coloured
     *
     * @return the value of wf_execution_task.DESCRIPTION:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.DESCRIPTION:Coloured
     *
     * @return the value of wf_execution_task.DESCRIPTION:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isDescriptionNotColoured() {
        return !descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.DESCRIPTION
     *
     * @param description the value for wf_execution_task.DESCRIPTION
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for wf_execution_task.DESCRIPTION:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.STATUS
     *
     * @return the value of wf_execution_task.STATUS
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.STATUS:Coloured
     *
     * @return the value of wf_execution_task.STATUS:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.STATUS:Coloured
     *
     * @return the value of wf_execution_task.STATUS:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isStatusNotColoured() {
        return !statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.STATUS
     *
     * @param status the value for wf_execution_task.STATUS
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.STATUS:Coloured
     *
     * @param statusColoured the value for wf_execution_task.STATUS:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.LAST_UPDATE_TIME
     *
     * @return the value of wf_execution_task.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of wf_execution_task.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of wf_execution_task.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isLastUpdateTimeNotColoured() {
        return !lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wf_execution_task.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for wf_execution_task.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.LAST_UPDATE_OPER
     *
     * @return the value of wf_execution_task.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of wf_execution_task.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of wf_execution_task.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isLastUpdateOperNotColoured() {
        return !lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for wf_execution_task.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for wf_execution_task.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.CREATE_TIME
     *
     * @return the value of wf_execution_task.CREATE_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.CREATE_TIME:Coloured
     *
     * @return the value of wf_execution_task.CREATE_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.CREATE_TIME:Coloured
     *
     * @return the value of wf_execution_task.CREATE_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isCreateTimeNotColoured() {
        return !createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.CREATE_TIME
     *
     * @param createTime the value for wf_execution_task.CREATE_TIME
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for wf_execution_task.CREATE_TIME:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.CREATE_OPER
     *
     * @return the value of wf_execution_task.CREATE_OPER
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.CREATE_OPER:Coloured
     *
     * @return the value of wf_execution_task.CREATE_OPER:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.CREATE_OPER:Coloured
     *
     * @return the value of wf_execution_task.CREATE_OPER:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isCreateOperNotColoured() {
        return !createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.CREATE_OPER
     *
     * @param createOper the value for wf_execution_task.CREATE_OPER
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for wf_execution_task.CREATE_OPER:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_CONTEXT
     *
     * @return the value of wf_execution_task.TASK_CONTEXT
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public String getTaskContext() {
        return taskContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_CONTEXT:Coloured
     *
     * @return the value of wf_execution_task.TASK_CONTEXT:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskContextColoured() {
        return taskContextColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task.TASK_CONTEXT:Coloured
     *
     * @return the value of wf_execution_task.TASK_CONTEXT:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public boolean isTaskContextNotColoured() {
        return !taskContextColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_CONTEXT
     *
     * @param taskContext the value for wf_execution_task.TASK_CONTEXT
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskContext(String taskContext) {
        this.taskContext = taskContext == null ? null : taskContext.trim();
        this.taskContextColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task.TASK_CONTEXT:Coloured
     *
     * @param taskContextColoured the value for wf_execution_task.TASK_CONTEXT:Coloured
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    public void setTaskContextColoured(boolean taskContextColoured) {
        this.taskContextColoured = taskContextColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WfExecutionTask other = (WfExecutionTask) that;
        return (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
            && (this.getTaskName() == null ? other.getTaskName() == null : this.getTaskName().equals(other.getTaskName()))
            && (this.getOwnerJobId() == null ? other.getOwnerJobId() == null : this.getOwnerJobId().equals(other.getOwnerJobId()))
            && (this.getSequence() == null ? other.getSequence() == null : this.getSequence().equals(other.getSequence()))
            && (this.getRelNodeId() == null ? other.getRelNodeId() == null : this.getRelNodeId().equals(other.getRelNodeId()))
            && (this.getEngineType() == null ? other.getEngineType() == null : this.getEngineType().equals(other.getEngineType()))
            && (this.getExternalId() == null ? other.getExternalId() == null : this.getExternalId().equals(other.getExternalId()))
            && (this.getSubmitFile() == null ? other.getSubmitFile() == null : this.getSubmitFile().equals(other.getSubmitFile()))
            && (this.getReturnFile() == null ? other.getReturnFile() == null : this.getReturnFile().equals(other.getReturnFile()))
            && (this.getLogFile() == null ? other.getLogFile() == null : this.getLogFile().equals(other.getLogFile()))
            && (this.getCostTime() == null ? other.getCostTime() == null : this.getCostTime().equals(other.getCostTime()))
            && (this.getTaskStartTime() == null ? other.getTaskStartTime() == null : this.getTaskStartTime().equals(other.getTaskStartTime()))
            && (this.getTaskEndTime() == null ? other.getTaskEndTime() == null : this.getTaskEndTime().equals(other.getTaskEndTime()))
            && (this.getTaskProgress() == null ? other.getTaskProgress() == null : this.getTaskProgress().equals(other.getTaskProgress()))
            && (this.getTaskState() == null ? other.getTaskState() == null : this.getTaskState().equals(other.getTaskState()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()))
            && (this.getTaskContext() == null ? other.getTaskContext() == null : this.getTaskContext().equals(other.getTaskContext()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getTaskName() == null) ? 0 : getTaskName().hashCode());
        result = prime * result + ((getOwnerJobId() == null) ? 0 : getOwnerJobId().hashCode());
        result = prime * result + ((getSequence() == null) ? 0 : getSequence().hashCode());
        result = prime * result + ((getRelNodeId() == null) ? 0 : getRelNodeId().hashCode());
        result = prime * result + ((getEngineType() == null) ? 0 : getEngineType().hashCode());
        result = prime * result + ((getExternalId() == null) ? 0 : getExternalId().hashCode());
        result = prime * result + ((getSubmitFile() == null) ? 0 : getSubmitFile().hashCode());
        result = prime * result + ((getReturnFile() == null) ? 0 : getReturnFile().hashCode());
        result = prime * result + ((getLogFile() == null) ? 0 : getLogFile().hashCode());
        result = prime * result + ((getCostTime() == null) ? 0 : getCostTime().hashCode());
        result = prime * result + ((getTaskStartTime() == null) ? 0 : getTaskStartTime().hashCode());
        result = prime * result + ((getTaskEndTime() == null) ? 0 : getTaskEndTime().hashCode());
        result = prime * result + ((getTaskProgress() == null) ? 0 : getTaskProgress().hashCode());
        result = prime * result + ((getTaskState() == null) ? 0 : getTaskState().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        result = prime * result + ((getTaskContext() == null) ? 0 : getTaskContext().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    @Override
    public void copyProperties(Object that) {
        if (this == that || that == null || this.getClass() != that.getClass() ) {
            return;
        }
        WfExecutionTask other = (WfExecutionTask) that;
        if(other.isTaskIdColoured() ) {this.setTaskId(other.getTaskId() );}
        if(other.isTaskNameColoured() ) {this.setTaskName(other.getTaskName() );}
        if(other.isOwnerJobIdColoured() ) {this.setOwnerJobId(other.getOwnerJobId() );}
        if(other.isSequenceColoured() ) {this.setSequence(other.getSequence() );}
        if(other.isRelNodeIdColoured() ) {this.setRelNodeId(other.getRelNodeId() );}
        if(other.isEngineTypeColoured() ) {this.setEngineType(other.getEngineType() );}
        if(other.isExternalIdColoured() ) {this.setExternalId(other.getExternalId() );}
        if(other.isSubmitFileColoured() ) {this.setSubmitFile(other.getSubmitFile() );}
        if(other.isReturnFileColoured() ) {this.setReturnFile(other.getReturnFile() );}
        if(other.isLogFileColoured() ) {this.setLogFile(other.getLogFile() );}
        if(other.isCostTimeColoured() ) {this.setCostTime(other.getCostTime() );}
        if(other.isTaskStartTimeColoured() ) {this.setTaskStartTime(other.getTaskStartTime() );}
        if(other.isTaskEndTimeColoured() ) {this.setTaskEndTime(other.getTaskEndTime() );}
        if(other.isTaskProgressColoured() ) {this.setTaskProgress(other.getTaskProgress() );}
        if(other.isTaskStateColoured() ) {this.setTaskState(other.getTaskState() );}
        if(other.isDescriptionColoured() ) {this.setDescription(other.getDescription() );}
        if(other.isStatusColoured() ) {this.setStatus(other.getStatus() );}
        if(other.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(other.getLastUpdateTime() );}
        if(other.isLastUpdateOperColoured() ) {this.setLastUpdateOper(other.getLastUpdateOper() );}
        if(other.isCreateTimeColoured() ) {this.setCreateTime(other.getCreateTime() );}
        if(other.isCreateOperColoured() ) {this.setCreateOper(other.getCreateOper() );}
        if(other.isTaskContextColoured() ) {this.setTaskContext(other.getTaskContext() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    @Override
    public JSONObject toJSON() {
        HashMap<String, Object> hashMap = new HashMap();
        if(this.taskIdColoured) {hashMap.put("taskId", this.taskId);}
        if(this.taskNameColoured) {hashMap.put("taskName", this.taskName);}
        if(this.ownerJobIdColoured) {hashMap.put("ownerJobId", this.ownerJobId);}
        if(this.sequenceColoured) {hashMap.put("sequence", this.sequence);}
        if(this.relNodeIdColoured) {hashMap.put("relNodeId", this.relNodeId);}
        if(this.engineTypeColoured) {hashMap.put("engineType", this.engineType);}
        if(this.externalIdColoured) {hashMap.put("externalId", this.externalId);}
        if(this.submitFileColoured) {hashMap.put("submitFile", this.submitFile);}
        if(this.returnFileColoured) {hashMap.put("returnFile", this.returnFile);}
        if(this.logFileColoured) {hashMap.put("logFile", this.logFile);}
        if(this.costTimeColoured) {hashMap.put("costTime", this.costTime);}
        if(this.taskStartTimeColoured) {hashMap.put("taskStartTime", this.taskStartTime);}
        if(this.taskEndTimeColoured) {hashMap.put("taskEndTime", this.taskEndTime);}
        if(this.taskProgressColoured) {hashMap.put("taskProgress", this.taskProgress);}
        if(this.taskStateColoured) {hashMap.put("taskState", this.taskState);}
        if(this.descriptionColoured) {hashMap.put("description", this.description);}
        if(this.statusColoured) {hashMap.put("status", this.status);}
        if(this.lastUpdateTimeColoured) {hashMap.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOperColoured) {hashMap.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTimeColoured) {hashMap.put("createTime", this.createTime);}
        if(this.createOperColoured) {hashMap.put("createOper", this.createOper);}
        if(this.taskContextColoured) {hashMap.put("taskContext", this.taskContext);}
        return (JSONObject) JSON.toJSON(hashMap);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task
     *
     * @mbg.generated Sat Dec 08 18:35:55 CST 2018
     */
    @Override
    public void clear() {
        if(this.taskIdColoured) {this.taskId = null; this.taskIdColoured = false;}
        if(this.taskNameColoured) {this.taskName = null; this.taskNameColoured = false;}
        if(this.ownerJobIdColoured) {this.ownerJobId = null; this.ownerJobIdColoured = false;}
        if(this.sequenceColoured) {this.sequence = null; this.sequenceColoured = false;}
        if(this.relNodeIdColoured) {this.relNodeId = null; this.relNodeIdColoured = false;}
        if(this.engineTypeColoured) {this.engineType = null; this.engineTypeColoured = false;}
        if(this.externalIdColoured) {this.externalId = null; this.externalIdColoured = false;}
        if(this.submitFileColoured) {this.submitFile = null; this.submitFileColoured = false;}
        if(this.returnFileColoured) {this.returnFile = null; this.returnFileColoured = false;}
        if(this.logFileColoured) {this.logFile = null; this.logFileColoured = false;}
        if(this.costTimeColoured) {this.costTime = null; this.costTimeColoured = false;}
        if(this.taskStartTimeColoured) {this.taskStartTime = null; this.taskStartTimeColoured = false;}
        if(this.taskEndTimeColoured) {this.taskEndTime = null; this.taskEndTimeColoured = false;}
        if(this.taskProgressColoured) {this.taskProgress = null; this.taskProgressColoured = false;}
        if(this.taskStateColoured) {this.taskState = null; this.taskStateColoured = false;}
        if(this.descriptionColoured) {this.description = null; this.descriptionColoured = false;}
        if(this.statusColoured) {this.status = null; this.statusColoured = false;}
        if(this.lastUpdateTimeColoured) {this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;}
        if(this.lastUpdateOperColoured) {this.lastUpdateOper = null; this.lastUpdateOperColoured = false;}
        if(this.createTimeColoured) {this.createTime = null; this.createTimeColoured = false;}
        if(this.createOperColoured) {this.createOper = null; this.createOperColoured = false;}
        if(this.taskContextColoured) {this.taskContext = null; this.taskContextColoured = false;}
        return;
    }
}