package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;

public class WfExecutionJob extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long jobId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean jobIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_NAME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String jobName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_NAME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean jobNameColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_TYPE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Integer jobType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_TYPE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean jobTypeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.OWNER_PROJECT_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long ownerProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean ownerProjectIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.REL_FLOW_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long relFlowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.REL_FLOW_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean relFlowIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.REL_SNAPSHOT_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long relSnapshotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.REL_SNAPSHOT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean relSnapshotIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.REL_NODE_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long relNodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.REL_NODE_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean relNodeIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_DFS_DIR
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String jobDfsDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_DFS_DIR:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean jobDfsDirColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_LOCAL_DIR
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String jobLocalDir;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_LOCAL_DIR:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean jobLocalDirColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.NEXT_TASK_SEQUENCE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Long nextTaskSequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.NEXT_TASK_SEQUENCE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean nextTaskSequenceColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_SUBMIT_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Date jobSubmitTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_SUBMIT_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean jobSubmitTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_START_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Date jobStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_START_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean jobStartTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_END_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Date jobEndTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_END_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean jobEndTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_STATE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Integer jobState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_STATE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean jobStateColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.DESCRIPTION
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.DESCRIPTION:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.STATUS
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.STATUS:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.LAST_UPDATE_OPER
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.CREATE_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.CREATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.CREATE_OPER
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.CREATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean createOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_CONTEXT
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private String jobContext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_job.JOB_CONTEXT:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private boolean jobContextColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wf_execution_job
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_ID
     *
     * @return the value of wf_execution_job.JOB_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getJobId() {
        return jobId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_ID:Coloured
     *
     * @return the value of wf_execution_job.JOB_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isJobIdColoured() {
        return jobIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_ID
     *
     * @param jobId the value for wf_execution_job.JOB_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobId(Long jobId) {
        this.jobId = jobId;
        this.jobIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_ID:Coloured
     *
     * @param jobIdColoured the value for wf_execution_job.JOB_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobIdColoured(boolean jobIdColoured) {
        this.jobIdColoured = jobIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_NAME
     *
     * @return the value of wf_execution_job.JOB_NAME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_NAME:Coloured
     *
     * @return the value of wf_execution_job.JOB_NAME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isJobNameColoured() {
        return jobNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_NAME
     *
     * @param jobName the value for wf_execution_job.JOB_NAME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
        this.jobNameColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_NAME:Coloured
     *
     * @param jobNameColoured the value for wf_execution_job.JOB_NAME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobNameColoured(boolean jobNameColoured) {
        this.jobNameColoured = jobNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_TYPE
     *
     * @return the value of wf_execution_job.JOB_TYPE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Integer getJobType() {
        return jobType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_TYPE:Coloured
     *
     * @return the value of wf_execution_job.JOB_TYPE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isJobTypeColoured() {
        return jobTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_TYPE
     *
     * @param jobType the value for wf_execution_job.JOB_TYPE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobType(Integer jobType) {
        this.jobType = jobType;
        this.jobTypeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_TYPE:Coloured
     *
     * @param jobTypeColoured the value for wf_execution_job.JOB_TYPE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobTypeColoured(boolean jobTypeColoured) {
        this.jobTypeColoured = jobTypeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.OWNER_PROJECT_ID
     *
     * @return the value of wf_execution_job.OWNER_PROJECT_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getOwnerProjectId() {
        return ownerProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.OWNER_PROJECT_ID:Coloured
     *
     * @return the value of wf_execution_job.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isOwnerProjectIdColoured() {
        return ownerProjectIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.OWNER_PROJECT_ID
     *
     * @param ownerProjectId the value for wf_execution_job.OWNER_PROJECT_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setOwnerProjectId(Long ownerProjectId) {
        this.ownerProjectId = ownerProjectId;
        this.ownerProjectIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.OWNER_PROJECT_ID:Coloured
     *
     * @param ownerProjectIdColoured the value for wf_execution_job.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setOwnerProjectIdColoured(boolean ownerProjectIdColoured) {
        this.ownerProjectIdColoured = ownerProjectIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.REL_FLOW_ID
     *
     * @return the value of wf_execution_job.REL_FLOW_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getRelFlowId() {
        return relFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.REL_FLOW_ID:Coloured
     *
     * @return the value of wf_execution_job.REL_FLOW_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isRelFlowIdColoured() {
        return relFlowIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.REL_FLOW_ID
     *
     * @param relFlowId the value for wf_execution_job.REL_FLOW_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelFlowId(Long relFlowId) {
        this.relFlowId = relFlowId;
        this.relFlowIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.REL_FLOW_ID:Coloured
     *
     * @param relFlowIdColoured the value for wf_execution_job.REL_FLOW_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelFlowIdColoured(boolean relFlowIdColoured) {
        this.relFlowIdColoured = relFlowIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.REL_SNAPSHOT_ID
     *
     * @return the value of wf_execution_job.REL_SNAPSHOT_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getRelSnapshotId() {
        return relSnapshotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.REL_SNAPSHOT_ID:Coloured
     *
     * @return the value of wf_execution_job.REL_SNAPSHOT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isRelSnapshotIdColoured() {
        return relSnapshotIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.REL_SNAPSHOT_ID
     *
     * @param relSnapshotId the value for wf_execution_job.REL_SNAPSHOT_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelSnapshotId(Long relSnapshotId) {
        this.relSnapshotId = relSnapshotId;
        this.relSnapshotIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.REL_SNAPSHOT_ID:Coloured
     *
     * @param relSnapshotIdColoured the value for wf_execution_job.REL_SNAPSHOT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelSnapshotIdColoured(boolean relSnapshotIdColoured) {
        this.relSnapshotIdColoured = relSnapshotIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.REL_NODE_ID
     *
     * @return the value of wf_execution_job.REL_NODE_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getRelNodeId() {
        return relNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.REL_NODE_ID:Coloured
     *
     * @return the value of wf_execution_job.REL_NODE_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isRelNodeIdColoured() {
        return relNodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.REL_NODE_ID
     *
     * @param relNodeId the value for wf_execution_job.REL_NODE_ID
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelNodeId(Long relNodeId) {
        this.relNodeId = relNodeId;
        this.relNodeIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.REL_NODE_ID:Coloured
     *
     * @param relNodeIdColoured the value for wf_execution_job.REL_NODE_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setRelNodeIdColoured(boolean relNodeIdColoured) {
        this.relNodeIdColoured = relNodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_DFS_DIR
     *
     * @return the value of wf_execution_job.JOB_DFS_DIR
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getJobDfsDir() {
        return jobDfsDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_DFS_DIR:Coloured
     *
     * @return the value of wf_execution_job.JOB_DFS_DIR:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isJobDfsDirColoured() {
        return jobDfsDirColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_DFS_DIR
     *
     * @param jobDfsDir the value for wf_execution_job.JOB_DFS_DIR
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobDfsDir(String jobDfsDir) {
        this.jobDfsDir = jobDfsDir == null ? null : jobDfsDir.trim();
        this.jobDfsDirColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_DFS_DIR:Coloured
     *
     * @param jobDfsDirColoured the value for wf_execution_job.JOB_DFS_DIR:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobDfsDirColoured(boolean jobDfsDirColoured) {
        this.jobDfsDirColoured = jobDfsDirColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_LOCAL_DIR
     *
     * @return the value of wf_execution_job.JOB_LOCAL_DIR
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getJobLocalDir() {
        return jobLocalDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_LOCAL_DIR:Coloured
     *
     * @return the value of wf_execution_job.JOB_LOCAL_DIR:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isJobLocalDirColoured() {
        return jobLocalDirColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_LOCAL_DIR
     *
     * @param jobLocalDir the value for wf_execution_job.JOB_LOCAL_DIR
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobLocalDir(String jobLocalDir) {
        this.jobLocalDir = jobLocalDir == null ? null : jobLocalDir.trim();
        this.jobLocalDirColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_LOCAL_DIR:Coloured
     *
     * @param jobLocalDirColoured the value for wf_execution_job.JOB_LOCAL_DIR:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobLocalDirColoured(boolean jobLocalDirColoured) {
        this.jobLocalDirColoured = jobLocalDirColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.NEXT_TASK_SEQUENCE
     *
     * @return the value of wf_execution_job.NEXT_TASK_SEQUENCE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Long getNextTaskSequence() {
        return nextTaskSequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.NEXT_TASK_SEQUENCE:Coloured
     *
     * @return the value of wf_execution_job.NEXT_TASK_SEQUENCE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isNextTaskSequenceColoured() {
        return nextTaskSequenceColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.NEXT_TASK_SEQUENCE
     *
     * @param nextTaskSequence the value for wf_execution_job.NEXT_TASK_SEQUENCE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setNextTaskSequence(Long nextTaskSequence) {
        this.nextTaskSequence = nextTaskSequence;
        this.nextTaskSequenceColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.NEXT_TASK_SEQUENCE:Coloured
     *
     * @param nextTaskSequenceColoured the value for wf_execution_job.NEXT_TASK_SEQUENCE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setNextTaskSequenceColoured(boolean nextTaskSequenceColoured) {
        this.nextTaskSequenceColoured = nextTaskSequenceColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_SUBMIT_TIME
     *
     * @return the value of wf_execution_job.JOB_SUBMIT_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Date getJobSubmitTime() {
        return jobSubmitTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_SUBMIT_TIME:Coloured
     *
     * @return the value of wf_execution_job.JOB_SUBMIT_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isJobSubmitTimeColoured() {
        return jobSubmitTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_SUBMIT_TIME
     *
     * @param jobSubmitTime the value for wf_execution_job.JOB_SUBMIT_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobSubmitTime(Date jobSubmitTime) {
        this.jobSubmitTime = jobSubmitTime;
        this.jobSubmitTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_SUBMIT_TIME:Coloured
     *
     * @param jobSubmitTimeColoured the value for wf_execution_job.JOB_SUBMIT_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobSubmitTimeColoured(boolean jobSubmitTimeColoured) {
        this.jobSubmitTimeColoured = jobSubmitTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_START_TIME
     *
     * @return the value of wf_execution_job.JOB_START_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Date getJobStartTime() {
        return jobStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_START_TIME:Coloured
     *
     * @return the value of wf_execution_job.JOB_START_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isJobStartTimeColoured() {
        return jobStartTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_START_TIME
     *
     * @param jobStartTime the value for wf_execution_job.JOB_START_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobStartTime(Date jobStartTime) {
        this.jobStartTime = jobStartTime;
        this.jobStartTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_START_TIME:Coloured
     *
     * @param jobStartTimeColoured the value for wf_execution_job.JOB_START_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobStartTimeColoured(boolean jobStartTimeColoured) {
        this.jobStartTimeColoured = jobStartTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_END_TIME
     *
     * @return the value of wf_execution_job.JOB_END_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Date getJobEndTime() {
        return jobEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_END_TIME:Coloured
     *
     * @return the value of wf_execution_job.JOB_END_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isJobEndTimeColoured() {
        return jobEndTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_END_TIME
     *
     * @param jobEndTime the value for wf_execution_job.JOB_END_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobEndTime(Date jobEndTime) {
        this.jobEndTime = jobEndTime;
        this.jobEndTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_END_TIME:Coloured
     *
     * @param jobEndTimeColoured the value for wf_execution_job.JOB_END_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobEndTimeColoured(boolean jobEndTimeColoured) {
        this.jobEndTimeColoured = jobEndTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_STATE
     *
     * @return the value of wf_execution_job.JOB_STATE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Integer getJobState() {
        return jobState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_STATE:Coloured
     *
     * @return the value of wf_execution_job.JOB_STATE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isJobStateColoured() {
        return jobStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_STATE
     *
     * @param jobState the value for wf_execution_job.JOB_STATE
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobState(Integer jobState) {
        this.jobState = jobState;
        this.jobStateColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_STATE:Coloured
     *
     * @param jobStateColoured the value for wf_execution_job.JOB_STATE:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobStateColoured(boolean jobStateColoured) {
        this.jobStateColoured = jobStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.DESCRIPTION
     *
     * @return the value of wf_execution_job.DESCRIPTION
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.DESCRIPTION:Coloured
     *
     * @return the value of wf_execution_job.DESCRIPTION:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.DESCRIPTION
     *
     * @param description the value for wf_execution_job.DESCRIPTION
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for wf_execution_job.DESCRIPTION:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.STATUS
     *
     * @return the value of wf_execution_job.STATUS
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.STATUS:Coloured
     *
     * @return the value of wf_execution_job.STATUS:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.STATUS
     *
     * @param status the value for wf_execution_job.STATUS
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.STATUS:Coloured
     *
     * @param statusColoured the value for wf_execution_job.STATUS:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.LAST_UPDATE_TIME
     *
     * @return the value of wf_execution_job.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of wf_execution_job.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wf_execution_job.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for wf_execution_job.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.LAST_UPDATE_OPER
     *
     * @return the value of wf_execution_job.LAST_UPDATE_OPER
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of wf_execution_job.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for wf_execution_job.LAST_UPDATE_OPER
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for wf_execution_job.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.CREATE_TIME
     *
     * @return the value of wf_execution_job.CREATE_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.CREATE_TIME:Coloured
     *
     * @return the value of wf_execution_job.CREATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.CREATE_TIME
     *
     * @param createTime the value for wf_execution_job.CREATE_TIME
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for wf_execution_job.CREATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.CREATE_OPER
     *
     * @return the value of wf_execution_job.CREATE_OPER
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.CREATE_OPER:Coloured
     *
     * @return the value of wf_execution_job.CREATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.CREATE_OPER
     *
     * @param createOper the value for wf_execution_job.CREATE_OPER
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for wf_execution_job.CREATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_CONTEXT
     *
     * @return the value of wf_execution_job.JOB_CONTEXT
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public String getJobContext() {
        return jobContext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_job.JOB_CONTEXT:Coloured
     *
     * @return the value of wf_execution_job.JOB_CONTEXT:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public boolean isJobContextColoured() {
        return jobContextColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_CONTEXT
     *
     * @param jobContext the value for wf_execution_job.JOB_CONTEXT
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobContext(String jobContext) {
        this.jobContext = jobContext == null ? null : jobContext.trim();
        this.jobContextColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_job.JOB_CONTEXT:Coloured
     *
     * @param jobContextColoured the value for wf_execution_job.JOB_CONTEXT:Coloured
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    public void setJobContextColoured(boolean jobContextColoured) {
        this.jobContextColoured = jobContextColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_job
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WfExecutionJob other = (WfExecutionJob) that;
        return (this.getJobId() == null ? other.getJobId() == null : this.getJobId().equals(other.getJobId()))
            && (this.getJobName() == null ? other.getJobName() == null : this.getJobName().equals(other.getJobName()))
            && (this.getJobType() == null ? other.getJobType() == null : this.getJobType().equals(other.getJobType()))
            && (this.getOwnerProjectId() == null ? other.getOwnerProjectId() == null : this.getOwnerProjectId().equals(other.getOwnerProjectId()))
            && (this.getRelFlowId() == null ? other.getRelFlowId() == null : this.getRelFlowId().equals(other.getRelFlowId()))
            && (this.getRelSnapshotId() == null ? other.getRelSnapshotId() == null : this.getRelSnapshotId().equals(other.getRelSnapshotId()))
            && (this.getRelNodeId() == null ? other.getRelNodeId() == null : this.getRelNodeId().equals(other.getRelNodeId()))
            && (this.getJobDfsDir() == null ? other.getJobDfsDir() == null : this.getJobDfsDir().equals(other.getJobDfsDir()))
            && (this.getJobLocalDir() == null ? other.getJobLocalDir() == null : this.getJobLocalDir().equals(other.getJobLocalDir()))
            && (this.getNextTaskSequence() == null ? other.getNextTaskSequence() == null : this.getNextTaskSequence().equals(other.getNextTaskSequence()))
            && (this.getJobSubmitTime() == null ? other.getJobSubmitTime() == null : this.getJobSubmitTime().equals(other.getJobSubmitTime()))
            && (this.getJobStartTime() == null ? other.getJobStartTime() == null : this.getJobStartTime().equals(other.getJobStartTime()))
            && (this.getJobEndTime() == null ? other.getJobEndTime() == null : this.getJobEndTime().equals(other.getJobEndTime()))
            && (this.getJobState() == null ? other.getJobState() == null : this.getJobState().equals(other.getJobState()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()))
            && (this.getJobContext() == null ? other.getJobContext() == null : this.getJobContext().equals(other.getJobContext()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_job
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getJobId() == null) ? 0 : getJobId().hashCode());
        result = prime * result + ((getJobName() == null) ? 0 : getJobName().hashCode());
        result = prime * result + ((getJobType() == null) ? 0 : getJobType().hashCode());
        result = prime * result + ((getOwnerProjectId() == null) ? 0 : getOwnerProjectId().hashCode());
        result = prime * result + ((getRelFlowId() == null) ? 0 : getRelFlowId().hashCode());
        result = prime * result + ((getRelSnapshotId() == null) ? 0 : getRelSnapshotId().hashCode());
        result = prime * result + ((getRelNodeId() == null) ? 0 : getRelNodeId().hashCode());
        result = prime * result + ((getJobDfsDir() == null) ? 0 : getJobDfsDir().hashCode());
        result = prime * result + ((getJobLocalDir() == null) ? 0 : getJobLocalDir().hashCode());
        result = prime * result + ((getNextTaskSequence() == null) ? 0 : getNextTaskSequence().hashCode());
        result = prime * result + ((getJobSubmitTime() == null) ? 0 : getJobSubmitTime().hashCode());
        result = prime * result + ((getJobStartTime() == null) ? 0 : getJobStartTime().hashCode());
        result = prime * result + ((getJobEndTime() == null) ? 0 : getJobEndTime().hashCode());
        result = prime * result + ((getJobState() == null) ? 0 : getJobState().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        result = prime * result + ((getJobContext() == null) ? 0 : getJobContext().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_job
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    @Override
    public void copyProperties(Object that) {
        if (this == that || that == null || this.getClass() != that.getClass() ) {
            return;
        }
        WfExecutionJob other = (WfExecutionJob) that;
        if(other.isJobIdColoured() ) {this.setJobId(other.getJobId() );}
        if(other.isJobNameColoured() ) {this.setJobName(other.getJobName() );}
        if(other.isJobTypeColoured() ) {this.setJobType(other.getJobType() );}
        if(other.isOwnerProjectIdColoured() ) {this.setOwnerProjectId(other.getOwnerProjectId() );}
        if(other.isRelFlowIdColoured() ) {this.setRelFlowId(other.getRelFlowId() );}
        if(other.isRelSnapshotIdColoured() ) {this.setRelSnapshotId(other.getRelSnapshotId() );}
        if(other.isRelNodeIdColoured() ) {this.setRelNodeId(other.getRelNodeId() );}
        if(other.isJobDfsDirColoured() ) {this.setJobDfsDir(other.getJobDfsDir() );}
        if(other.isJobLocalDirColoured() ) {this.setJobLocalDir(other.getJobLocalDir() );}
        if(other.isNextTaskSequenceColoured() ) {this.setNextTaskSequence(other.getNextTaskSequence() );}
        if(other.isJobSubmitTimeColoured() ) {this.setJobSubmitTime(other.getJobSubmitTime() );}
        if(other.isJobStartTimeColoured() ) {this.setJobStartTime(other.getJobStartTime() );}
        if(other.isJobEndTimeColoured() ) {this.setJobEndTime(other.getJobEndTime() );}
        if(other.isJobStateColoured() ) {this.setJobState(other.getJobState() );}
        if(other.isDescriptionColoured() ) {this.setDescription(other.getDescription() );}
        if(other.isStatusColoured() ) {this.setStatus(other.getStatus() );}
        if(other.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(other.getLastUpdateTime() );}
        if(other.isLastUpdateOperColoured() ) {this.setLastUpdateOper(other.getLastUpdateOper() );}
        if(other.isCreateTimeColoured() ) {this.setCreateTime(other.getCreateTime() );}
        if(other.isCreateOperColoured() ) {this.setCreateOper(other.getCreateOper() );}
        if(other.isJobContextColoured() ) {this.setJobContext(other.getJobContext() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_job
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    @Override
    public JSONObject toJSON() {
        HashMap<String, Object> hashMap = new HashMap();
        if(this.jobIdColoured) {hashMap.put("jobId", this.jobId);}
        if(this.jobNameColoured) {hashMap.put("jobName", this.jobName);}
        if(this.jobTypeColoured) {hashMap.put("jobType", this.jobType);}
        if(this.ownerProjectIdColoured) {hashMap.put("ownerProjectId", this.ownerProjectId);}
        if(this.relFlowIdColoured) {hashMap.put("relFlowId", this.relFlowId);}
        if(this.relSnapshotIdColoured) {hashMap.put("relSnapshotId", this.relSnapshotId);}
        if(this.relNodeIdColoured) {hashMap.put("relNodeId", this.relNodeId);}
        if(this.jobDfsDirColoured) {hashMap.put("jobDfsDir", this.jobDfsDir);}
        if(this.jobLocalDirColoured) {hashMap.put("jobLocalDir", this.jobLocalDir);}
        if(this.nextTaskSequenceColoured) {hashMap.put("nextTaskSequence", this.nextTaskSequence);}
        if(this.jobSubmitTimeColoured) {hashMap.put("jobSubmitTime", this.jobSubmitTime);}
        if(this.jobStartTimeColoured) {hashMap.put("jobStartTime", this.jobStartTime);}
        if(this.jobEndTimeColoured) {hashMap.put("jobEndTime", this.jobEndTime);}
        if(this.jobStateColoured) {hashMap.put("jobState", this.jobState);}
        if(this.descriptionColoured) {hashMap.put("description", this.description);}
        if(this.statusColoured) {hashMap.put("status", this.status);}
        if(this.lastUpdateTimeColoured) {hashMap.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOperColoured) {hashMap.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTimeColoured) {hashMap.put("createTime", this.createTime);}
        if(this.createOperColoured) {hashMap.put("createOper", this.createOper);}
        if(this.jobContextColoured) {hashMap.put("jobContext", this.jobContext);}
        return (JSONObject) JSON.toJSON(hashMap);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_job
     *
     * @mbg.generated Wed Dec 05 02:52:56 CST 2018
     */
    @Override
    public void clear() {
        if(this.jobIdColoured) {this.jobId = null; this.jobIdColoured = false;}
        if(this.jobNameColoured) {this.jobName = null; this.jobNameColoured = false;}
        if(this.jobTypeColoured) {this.jobType = null; this.jobTypeColoured = false;}
        if(this.ownerProjectIdColoured) {this.ownerProjectId = null; this.ownerProjectIdColoured = false;}
        if(this.relFlowIdColoured) {this.relFlowId = null; this.relFlowIdColoured = false;}
        if(this.relSnapshotIdColoured) {this.relSnapshotId = null; this.relSnapshotIdColoured = false;}
        if(this.relNodeIdColoured) {this.relNodeId = null; this.relNodeIdColoured = false;}
        if(this.jobDfsDirColoured) {this.jobDfsDir = null; this.jobDfsDirColoured = false;}
        if(this.jobLocalDirColoured) {this.jobLocalDir = null; this.jobLocalDirColoured = false;}
        if(this.nextTaskSequenceColoured) {this.nextTaskSequence = null; this.nextTaskSequenceColoured = false;}
        if(this.jobSubmitTimeColoured) {this.jobSubmitTime = null; this.jobSubmitTimeColoured = false;}
        if(this.jobStartTimeColoured) {this.jobStartTime = null; this.jobStartTimeColoured = false;}
        if(this.jobEndTimeColoured) {this.jobEndTime = null; this.jobEndTimeColoured = false;}
        if(this.jobStateColoured) {this.jobState = null; this.jobStateColoured = false;}
        if(this.descriptionColoured) {this.description = null; this.descriptionColoured = false;}
        if(this.statusColoured) {this.status = null; this.statusColoured = false;}
        if(this.lastUpdateTimeColoured) {this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;}
        if(this.lastUpdateOperColoured) {this.lastUpdateOper = null; this.lastUpdateOperColoured = false;}
        if(this.createTimeColoured) {this.createTime = null; this.createTimeColoured = false;}
        if(this.createOperColoured) {this.createOper = null; this.createOperColoured = false;}
        if(this.jobContextColoured) {this.jobContext = null; this.jobContextColoured = false;}
        return;
    }
}