package com.yatop.lambda.base.model;

import java.io.Serializable;
import java.util.Date;

public class WfExecutionTaskOutput implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task_output.TASK_ID
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task_output.CHAR_ID
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private Long charId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task_output.CHAR_VALUE
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private String charValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task_output.DESCRIPTION
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task_output.STATUS
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task_output.LAST_UPDATE_TIME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task_output.LAST_UPDATE_OPER
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task_output.CREATE_TIME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_execution_task_output.CREATE_OPER
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private String createOper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wf_execution_task_output
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task_output.TASK_ID
     *
     * @return the value of wf_execution_task_output.TASK_ID
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task_output.TASK_ID
     *
     * @param taskId the value for wf_execution_task_output.TASK_ID
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task_output.CHAR_ID
     *
     * @return the value of wf_execution_task_output.CHAR_ID
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public Long getCharId() {
        return charId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task_output.CHAR_ID
     *
     * @param charId the value for wf_execution_task_output.CHAR_ID
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setCharId(Long charId) {
        this.charId = charId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task_output.CHAR_VALUE
     *
     * @return the value of wf_execution_task_output.CHAR_VALUE
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public String getCharValue() {
        return charValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task_output.CHAR_VALUE
     *
     * @param charValue the value for wf_execution_task_output.CHAR_VALUE
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setCharValue(String charValue) {
        this.charValue = charValue == null ? null : charValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task_output.DESCRIPTION
     *
     * @return the value of wf_execution_task_output.DESCRIPTION
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task_output.DESCRIPTION
     *
     * @param description the value for wf_execution_task_output.DESCRIPTION
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task_output.STATUS
     *
     * @return the value of wf_execution_task_output.STATUS
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task_output.STATUS
     *
     * @param status the value for wf_execution_task_output.STATUS
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task_output.LAST_UPDATE_TIME
     *
     * @return the value of wf_execution_task_output.LAST_UPDATE_TIME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task_output.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wf_execution_task_output.LAST_UPDATE_TIME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task_output.LAST_UPDATE_OPER
     *
     * @return the value of wf_execution_task_output.LAST_UPDATE_OPER
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task_output.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for wf_execution_task_output.LAST_UPDATE_OPER
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task_output.CREATE_TIME
     *
     * @return the value of wf_execution_task_output.CREATE_TIME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task_output.CREATE_TIME
     *
     * @param createTime the value for wf_execution_task_output.CREATE_TIME
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_execution_task_output.CREATE_OPER
     *
     * @return the value of wf_execution_task_output.CREATE_OPER
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_execution_task_output.CREATE_OPER
     *
     * @param createOper the value for wf_execution_task_output.CREATE_OPER
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task_output
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WfExecutionTaskOutput other = (WfExecutionTaskOutput) that;
        return (this.getTaskId() == null ? other.getTaskId() == null : this.getTaskId().equals(other.getTaskId()))
            && (this.getCharId() == null ? other.getCharId() == null : this.getCharId().equals(other.getCharId()))
            && (this.getCharValue() == null ? other.getCharValue() == null : this.getCharValue().equals(other.getCharValue()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_execution_task_output
     *
     * @mbg.generated Sun Dec 02 15:46:24 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTaskId() == null) ? 0 : getTaskId().hashCode());
        result = prime * result + ((getCharId() == null) ? 0 : getCharId().hashCode());
        result = prime * result + ((getCharValue() == null) ? 0 : getCharValue().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }
}