package com.yatop.lambda.base.model;

import java.io.Serializable;
import java.util.Date;

public class WfFlowNodeParameter implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.NODE_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Long nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.SPEC_TYPE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Integer specType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.CHAR_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Long charId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.CHAR_VALUE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String charValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.IS_GLOBAL_PARAMETER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Integer isGlobalParameter;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.IS_DUPLICATED
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Integer isDuplicated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.WARNING_MSG
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String warningMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.DESCRIPTION
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.STATUS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.CREATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_parameter.CREATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String createOper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wf_flow_node_parameter
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.NODE_ID
     *
     * @return the value of wf_flow_node_parameter.NODE_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Long getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.NODE_ID
     *
     * @param nodeId the value for wf_flow_node_parameter.NODE_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setNodeId(Long nodeId) {
        this.nodeId = nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.SPEC_TYPE
     *
     * @return the value of wf_flow_node_parameter.SPEC_TYPE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Integer getSpecType() {
        return specType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.SPEC_TYPE
     *
     * @param specType the value for wf_flow_node_parameter.SPEC_TYPE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setSpecType(Integer specType) {
        this.specType = specType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.CHAR_ID
     *
     * @return the value of wf_flow_node_parameter.CHAR_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Long getCharId() {
        return charId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.CHAR_ID
     *
     * @param charId the value for wf_flow_node_parameter.CHAR_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCharId(Long charId) {
        this.charId = charId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.CHAR_VALUE
     *
     * @return the value of wf_flow_node_parameter.CHAR_VALUE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getCharValue() {
        return charValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.CHAR_VALUE
     *
     * @param charValue the value for wf_flow_node_parameter.CHAR_VALUE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCharValue(String charValue) {
        this.charValue = charValue == null ? null : charValue.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.IS_GLOBAL_PARAMETER
     *
     * @return the value of wf_flow_node_parameter.IS_GLOBAL_PARAMETER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Integer getIsGlobalParameter() {
        return isGlobalParameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.IS_GLOBAL_PARAMETER
     *
     * @param isGlobalParameter the value for wf_flow_node_parameter.IS_GLOBAL_PARAMETER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setIsGlobalParameter(Integer isGlobalParameter) {
        this.isGlobalParameter = isGlobalParameter;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.IS_DUPLICATED
     *
     * @return the value of wf_flow_node_parameter.IS_DUPLICATED
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Integer getIsDuplicated() {
        return isDuplicated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.IS_DUPLICATED
     *
     * @param isDuplicated the value for wf_flow_node_parameter.IS_DUPLICATED
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setIsDuplicated(Integer isDuplicated) {
        this.isDuplicated = isDuplicated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.WARNING_MSG
     *
     * @return the value of wf_flow_node_parameter.WARNING_MSG
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getWarningMsg() {
        return warningMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.WARNING_MSG
     *
     * @param warningMsg the value for wf_flow_node_parameter.WARNING_MSG
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setWarningMsg(String warningMsg) {
        this.warningMsg = warningMsg == null ? null : warningMsg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.DESCRIPTION
     *
     * @return the value of wf_flow_node_parameter.DESCRIPTION
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.DESCRIPTION
     *
     * @param description the value for wf_flow_node_parameter.DESCRIPTION
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.STATUS
     *
     * @return the value of wf_flow_node_parameter.STATUS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.STATUS
     *
     * @param status the value for wf_flow_node_parameter.STATUS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.LAST_UPDATE_TIME
     *
     * @return the value of wf_flow_node_parameter.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wf_flow_node_parameter.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.LAST_UPDATE_OPER
     *
     * @return the value of wf_flow_node_parameter.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for wf_flow_node_parameter.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.CREATE_TIME
     *
     * @return the value of wf_flow_node_parameter.CREATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.CREATE_TIME
     *
     * @param createTime the value for wf_flow_node_parameter.CREATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_parameter.CREATE_OPER
     *
     * @return the value of wf_flow_node_parameter.CREATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_parameter.CREATE_OPER
     *
     * @param createOper the value for wf_flow_node_parameter.CREATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node_parameter
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WfFlowNodeParameter other = (WfFlowNodeParameter) that;
        return (this.getNodeId() == null ? other.getNodeId() == null : this.getNodeId().equals(other.getNodeId()))
            && (this.getSpecType() == null ? other.getSpecType() == null : this.getSpecType().equals(other.getSpecType()))
            && (this.getCharId() == null ? other.getCharId() == null : this.getCharId().equals(other.getCharId()))
            && (this.getCharValue() == null ? other.getCharValue() == null : this.getCharValue().equals(other.getCharValue()))
            && (this.getIsGlobalParameter() == null ? other.getIsGlobalParameter() == null : this.getIsGlobalParameter().equals(other.getIsGlobalParameter()))
            && (this.getIsDuplicated() == null ? other.getIsDuplicated() == null : this.getIsDuplicated().equals(other.getIsDuplicated()))
            && (this.getWarningMsg() == null ? other.getWarningMsg() == null : this.getWarningMsg().equals(other.getWarningMsg()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node_parameter
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNodeId() == null) ? 0 : getNodeId().hashCode());
        result = prime * result + ((getSpecType() == null) ? 0 : getSpecType().hashCode());
        result = prime * result + ((getCharId() == null) ? 0 : getCharId().hashCode());
        result = prime * result + ((getCharValue() == null) ? 0 : getCharValue().hashCode());
        result = prime * result + ((getIsGlobalParameter() == null) ? 0 : getIsGlobalParameter().hashCode());
        result = prime * result + ((getIsDuplicated() == null) ? 0 : getIsDuplicated().hashCode());
        result = prime * result + ((getWarningMsg() == null) ? 0 : getWarningMsg().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }
}