package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;

public class WfFlowNodePort extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.NODE_PORT_ID
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private Long nodePortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.NODE_PORT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private boolean nodePortIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.OWNER_NODE_ID
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private Long ownerNodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.OWNER_NODE_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private boolean ownerNodeIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.REF_PORT_ID
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private Long refPortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.REF_PORT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private boolean refPortIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.REF_CHAR_ID
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private String refCharId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.REF_CHAR_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private boolean refCharIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.DESCRIPTION
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.STATUS
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.STATUS:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.LAST_UPDATE_OPER
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.CREATE_TIME
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.CREATE_OPER
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_port.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private boolean createOperColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wf_flow_node_port
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.NODE_PORT_ID
     *
     * @return the value of wf_flow_node_port.NODE_PORT_ID
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public Long getNodePortId() {
        return nodePortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.NODE_PORT_ID:Coloured
     *
     * @return the value of wf_flow_node_port.NODE_PORT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public boolean isNodePortIdColoured() {
        return nodePortIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.NODE_PORT_ID
     *
     * @param nodePortId the value for wf_flow_node_port.NODE_PORT_ID
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setNodePortId(Long nodePortId) {
        this.nodePortId = nodePortId;
        this.nodePortIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.NODE_PORT_ID:Coloured
     *
     * @param nodePortIdColoured the value for wf_flow_node_port.NODE_PORT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setNodePortIdColoured(boolean nodePortIdColoured) {
        this.nodePortIdColoured = nodePortIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.OWNER_NODE_ID
     *
     * @return the value of wf_flow_node_port.OWNER_NODE_ID
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public Long getOwnerNodeId() {
        return ownerNodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.OWNER_NODE_ID:Coloured
     *
     * @return the value of wf_flow_node_port.OWNER_NODE_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public boolean isOwnerNodeIdColoured() {
        return ownerNodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.OWNER_NODE_ID
     *
     * @param ownerNodeId the value for wf_flow_node_port.OWNER_NODE_ID
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setOwnerNodeId(Long ownerNodeId) {
        this.ownerNodeId = ownerNodeId;
        this.ownerNodeIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.OWNER_NODE_ID:Coloured
     *
     * @param ownerNodeIdColoured the value for wf_flow_node_port.OWNER_NODE_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setOwnerNodeIdColoured(boolean ownerNodeIdColoured) {
        this.ownerNodeIdColoured = ownerNodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.REF_PORT_ID
     *
     * @return the value of wf_flow_node_port.REF_PORT_ID
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public Long getRefPortId() {
        return refPortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.REF_PORT_ID:Coloured
     *
     * @return the value of wf_flow_node_port.REF_PORT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public boolean isRefPortIdColoured() {
        return refPortIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.REF_PORT_ID
     *
     * @param refPortId the value for wf_flow_node_port.REF_PORT_ID
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setRefPortId(Long refPortId) {
        this.refPortId = refPortId;
        this.refPortIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.REF_PORT_ID:Coloured
     *
     * @param refPortIdColoured the value for wf_flow_node_port.REF_PORT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setRefPortIdColoured(boolean refPortIdColoured) {
        this.refPortIdColoured = refPortIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.REF_CHAR_ID
     *
     * @return the value of wf_flow_node_port.REF_CHAR_ID
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public String getRefCharId() {
        return refCharId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.REF_CHAR_ID:Coloured
     *
     * @return the value of wf_flow_node_port.REF_CHAR_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public boolean isRefCharIdColoured() {
        return refCharIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.REF_CHAR_ID
     *
     * @param refCharId the value for wf_flow_node_port.REF_CHAR_ID
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setRefCharId(String refCharId) {
        this.refCharId = refCharId == null ? null : refCharId.trim();
        this.refCharIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.REF_CHAR_ID:Coloured
     *
     * @param refCharIdColoured the value for wf_flow_node_port.REF_CHAR_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setRefCharIdColoured(boolean refCharIdColoured) {
        this.refCharIdColoured = refCharIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.DESCRIPTION
     *
     * @return the value of wf_flow_node_port.DESCRIPTION
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.DESCRIPTION:Coloured
     *
     * @return the value of wf_flow_node_port.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.DESCRIPTION
     *
     * @param description the value for wf_flow_node_port.DESCRIPTION
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for wf_flow_node_port.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.STATUS
     *
     * @return the value of wf_flow_node_port.STATUS
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.STATUS:Coloured
     *
     * @return the value of wf_flow_node_port.STATUS:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.STATUS
     *
     * @param status the value for wf_flow_node_port.STATUS
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.STATUS:Coloured
     *
     * @param statusColoured the value for wf_flow_node_port.STATUS:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.LAST_UPDATE_TIME
     *
     * @return the value of wf_flow_node_port.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of wf_flow_node_port.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wf_flow_node_port.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for wf_flow_node_port.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.LAST_UPDATE_OPER
     *
     * @return the value of wf_flow_node_port.LAST_UPDATE_OPER
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of wf_flow_node_port.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for wf_flow_node_port.LAST_UPDATE_OPER
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for wf_flow_node_port.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.CREATE_TIME
     *
     * @return the value of wf_flow_node_port.CREATE_TIME
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.CREATE_TIME:Coloured
     *
     * @return the value of wf_flow_node_port.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.CREATE_TIME
     *
     * @param createTime the value for wf_flow_node_port.CREATE_TIME
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for wf_flow_node_port.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.CREATE_OPER
     *
     * @return the value of wf_flow_node_port.CREATE_OPER
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_port.CREATE_OPER:Coloured
     *
     * @return the value of wf_flow_node_port.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.CREATE_OPER
     *
     * @param createOper the value for wf_flow_node_port.CREATE_OPER
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_port.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for wf_flow_node_port.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node_port
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WfFlowNodePort other = (WfFlowNodePort) that;
        return (this.getNodePortId() == null ? other.getNodePortId() == null : this.getNodePortId().equals(other.getNodePortId()))
            && (this.getOwnerNodeId() == null ? other.getOwnerNodeId() == null : this.getOwnerNodeId().equals(other.getOwnerNodeId()))
            && (this.getRefPortId() == null ? other.getRefPortId() == null : this.getRefPortId().equals(other.getRefPortId()))
            && (this.getRefCharId() == null ? other.getRefCharId() == null : this.getRefCharId().equals(other.getRefCharId()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node_port
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNodePortId() == null) ? 0 : getNodePortId().hashCode());
        result = prime * result + ((getOwnerNodeId() == null) ? 0 : getOwnerNodeId().hashCode());
        result = prime * result + ((getRefPortId() == null) ? 0 : getRefPortId().hashCode());
        result = prime * result + ((getRefCharId() == null) ? 0 : getRefCharId().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node_port
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    @Override
    public void copyProperties(Object that) {
        if (this == that || that == null || this.getClass() != that.getClass() ) {
            return;
        }
        WfFlowNodePort other = (WfFlowNodePort) that;
        if(other.isNodePortIdColoured() ) {this.setNodePortId(other.getNodePortId() );}
        if(other.isOwnerNodeIdColoured() ) {this.setOwnerNodeId(other.getOwnerNodeId() );}
        if(other.isRefPortIdColoured() ) {this.setRefPortId(other.getRefPortId() );}
        if(other.isRefCharIdColoured() ) {this.setRefCharId(other.getRefCharId() );}
        if(other.isDescriptionColoured() ) {this.setDescription(other.getDescription() );}
        if(other.isStatusColoured() ) {this.setStatus(other.getStatus() );}
        if(other.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(other.getLastUpdateTime() );}
        if(other.isLastUpdateOperColoured() ) {this.setLastUpdateOper(other.getLastUpdateOper() );}
        if(other.isCreateTimeColoured() ) {this.setCreateTime(other.getCreateTime() );}
        if(other.isCreateOperColoured() ) {this.setCreateOper(other.getCreateOper() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node_port
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    @Override
    public JSONObject toJSON() {
        HashMap<String, Object> hashMap = new HashMap();
        if(this.nodePortIdColoured) {hashMap.put("nodePortId", this.nodePortId);}
        if(this.ownerNodeIdColoured) {hashMap.put("ownerNodeId", this.ownerNodeId);}
        if(this.refPortIdColoured) {hashMap.put("refPortId", this.refPortId);}
        if(this.refCharIdColoured) {hashMap.put("refCharId", this.refCharId);}
        if(this.descriptionColoured) {hashMap.put("description", this.description);}
        if(this.statusColoured) {hashMap.put("status", this.status);}
        if(this.lastUpdateTimeColoured) {hashMap.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOperColoured) {hashMap.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTimeColoured) {hashMap.put("createTime", this.createTime);}
        if(this.createOperColoured) {hashMap.put("createOper", this.createOper);}
        return (JSONObject) JSON.toJSON(hashMap);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node_port
     *
     * @mbg.generated Tue Dec 04 13:25:54 CST 2018
     */
    @Override
    public void clear() {
        if(this.nodePortIdColoured) {this.nodePortId = null; this.nodePortIdColoured = false;}
        if(this.ownerNodeIdColoured) {this.ownerNodeId = null; this.ownerNodeIdColoured = false;}
        if(this.refPortIdColoured) {this.refPortId = null; this.refPortIdColoured = false;}
        if(this.refCharIdColoured) {this.refCharId = null; this.refCharIdColoured = false;}
        if(this.descriptionColoured) {this.description = null; this.descriptionColoured = false;}
        if(this.statusColoured) {this.status = null; this.statusColoured = false;}
        if(this.lastUpdateTimeColoured) {this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;}
        if(this.lastUpdateOperColoured) {this.lastUpdateOper = null; this.lastUpdateOperColoured = false;}
        if(this.createTimeColoured) {this.createTime = null; this.createTimeColoured = false;}
        if(this.createOperColoured) {this.createOper = null; this.createOperColoured = false;}
        return;
    }
}