package com.yatop.lambda.base.model;

import java.io.Serializable;
import java.util.Date;

public class WfFlowNodeSchema implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_schema.NODE_PORT_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Long nodePortId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_schema.OBJECT_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Long objectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_schema.SCHEMA_STATE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Integer schemaState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_schema.DESCRIPTION
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_schema.STATUS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_schema.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_schema.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_schema.CREATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node_schema.CREATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private String createOper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wf_flow_node_schema
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_schema.NODE_PORT_ID
     *
     * @return the value of wf_flow_node_schema.NODE_PORT_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Long getNodePortId() {
        return nodePortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_schema.NODE_PORT_ID
     *
     * @param nodePortId the value for wf_flow_node_schema.NODE_PORT_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setNodePortId(Long nodePortId) {
        this.nodePortId = nodePortId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_schema.OBJECT_ID
     *
     * @return the value of wf_flow_node_schema.OBJECT_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Long getObjectId() {
        return objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_schema.OBJECT_ID
     *
     * @param objectId the value for wf_flow_node_schema.OBJECT_ID
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setObjectId(Long objectId) {
        this.objectId = objectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_schema.SCHEMA_STATE
     *
     * @return the value of wf_flow_node_schema.SCHEMA_STATE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Integer getSchemaState() {
        return schemaState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_schema.SCHEMA_STATE
     *
     * @param schemaState the value for wf_flow_node_schema.SCHEMA_STATE
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setSchemaState(Integer schemaState) {
        this.schemaState = schemaState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_schema.DESCRIPTION
     *
     * @return the value of wf_flow_node_schema.DESCRIPTION
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_schema.DESCRIPTION
     *
     * @param description the value for wf_flow_node_schema.DESCRIPTION
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_schema.STATUS
     *
     * @return the value of wf_flow_node_schema.STATUS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_schema.STATUS
     *
     * @param status the value for wf_flow_node_schema.STATUS
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_schema.LAST_UPDATE_TIME
     *
     * @return the value of wf_flow_node_schema.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_schema.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wf_flow_node_schema.LAST_UPDATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_schema.LAST_UPDATE_OPER
     *
     * @return the value of wf_flow_node_schema.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_schema.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for wf_flow_node_schema.LAST_UPDATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_schema.CREATE_TIME
     *
     * @return the value of wf_flow_node_schema.CREATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_schema.CREATE_TIME
     *
     * @param createTime the value for wf_flow_node_schema.CREATE_TIME
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node_schema.CREATE_OPER
     *
     * @return the value of wf_flow_node_schema.CREATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node_schema.CREATE_OPER
     *
     * @param createOper the value for wf_flow_node_schema.CREATE_OPER
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node_schema
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WfFlowNodeSchema other = (WfFlowNodeSchema) that;
        return (this.getNodePortId() == null ? other.getNodePortId() == null : this.getNodePortId().equals(other.getNodePortId()))
            && (this.getObjectId() == null ? other.getObjectId() == null : this.getObjectId().equals(other.getObjectId()))
            && (this.getSchemaState() == null ? other.getSchemaState() == null : this.getSchemaState().equals(other.getSchemaState()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node_schema
     *
     * @mbg.generated Sat Dec 01 22:15:38 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNodePortId() == null) ? 0 : getNodePortId().hashCode());
        result = prime * result + ((getObjectId() == null) ? 0 : getObjectId().hashCode());
        result = prime * result + ((getSchemaState() == null) ? 0 : getSchemaState().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }
}