package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;

public class WfFlowNode extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.NODE_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long nodeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.NODE_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean nodeIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.NODE_NAME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private String nodeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.NODE_NAME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean nodeNameColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.OWNER_PROJECT_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long ownerProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean ownerProjectIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.OWNER_FLOW_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long ownerFlowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.OWNER_FLOW_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean ownerFlowIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.REF_MODULE_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long refModuleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.REF_MODULE_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean refModuleIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.POSITION_X
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long positionX;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.POSITION_X:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean positionXColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.POSITION_Y
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long positionY;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.POSITION_Y:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean positionYColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.LAST_TASK_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Long lastTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.LAST_TASK_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean lastTaskIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.WARNING_MSG
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private String warningMsg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.WARNING_MSG:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean warningMsgColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.NODE_STATE
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Integer nodeState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.NODE_STATE:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean nodeStateColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.SUMMARY
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private String summary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.SUMMARY:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean summaryColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.DESCRIPTION
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.STATUS
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.STATUS:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.LAST_UPDATE_OPER
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.CREATE_TIME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.CREATE_OPER
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_flow_node.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private boolean createOperColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wf_flow_node
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.NODE_ID
     *
     * @return the value of wf_flow_node.NODE_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getNodeId() {
        return nodeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.NODE_ID:Coloured
     *
     * @return the value of wf_flow_node.NODE_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isNodeIdColoured() {
        return nodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.NODE_ID
     *
     * @param nodeId the value for wf_flow_node.NODE_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setNodeId(Long nodeId) {
        this.nodeId = nodeId;
        this.nodeIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.NODE_ID:Coloured
     *
     * @param nodeIdColoured the value for wf_flow_node.NODE_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setNodeIdColoured(boolean nodeIdColoured) {
        this.nodeIdColoured = nodeIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.NODE_NAME
     *
     * @return the value of wf_flow_node.NODE_NAME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public String getNodeName() {
        return nodeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.NODE_NAME:Coloured
     *
     * @return the value of wf_flow_node.NODE_NAME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isNodeNameColoured() {
        return nodeNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.NODE_NAME
     *
     * @param nodeName the value for wf_flow_node.NODE_NAME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setNodeName(String nodeName) {
        this.nodeName = nodeName == null ? null : nodeName.trim();
        this.nodeNameColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.NODE_NAME:Coloured
     *
     * @param nodeNameColoured the value for wf_flow_node.NODE_NAME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setNodeNameColoured(boolean nodeNameColoured) {
        this.nodeNameColoured = nodeNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.OWNER_PROJECT_ID
     *
     * @return the value of wf_flow_node.OWNER_PROJECT_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getOwnerProjectId() {
        return ownerProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.OWNER_PROJECT_ID:Coloured
     *
     * @return the value of wf_flow_node.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isOwnerProjectIdColoured() {
        return ownerProjectIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.OWNER_PROJECT_ID
     *
     * @param ownerProjectId the value for wf_flow_node.OWNER_PROJECT_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setOwnerProjectId(Long ownerProjectId) {
        this.ownerProjectId = ownerProjectId;
        this.ownerProjectIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.OWNER_PROJECT_ID:Coloured
     *
     * @param ownerProjectIdColoured the value for wf_flow_node.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setOwnerProjectIdColoured(boolean ownerProjectIdColoured) {
        this.ownerProjectIdColoured = ownerProjectIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.OWNER_FLOW_ID
     *
     * @return the value of wf_flow_node.OWNER_FLOW_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getOwnerFlowId() {
        return ownerFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.OWNER_FLOW_ID:Coloured
     *
     * @return the value of wf_flow_node.OWNER_FLOW_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isOwnerFlowIdColoured() {
        return ownerFlowIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.OWNER_FLOW_ID
     *
     * @param ownerFlowId the value for wf_flow_node.OWNER_FLOW_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setOwnerFlowId(Long ownerFlowId) {
        this.ownerFlowId = ownerFlowId;
        this.ownerFlowIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.OWNER_FLOW_ID:Coloured
     *
     * @param ownerFlowIdColoured the value for wf_flow_node.OWNER_FLOW_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setOwnerFlowIdColoured(boolean ownerFlowIdColoured) {
        this.ownerFlowIdColoured = ownerFlowIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.REF_MODULE_ID
     *
     * @return the value of wf_flow_node.REF_MODULE_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getRefModuleId() {
        return refModuleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.REF_MODULE_ID:Coloured
     *
     * @return the value of wf_flow_node.REF_MODULE_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isRefModuleIdColoured() {
        return refModuleIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.REF_MODULE_ID
     *
     * @param refModuleId the value for wf_flow_node.REF_MODULE_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setRefModuleId(Long refModuleId) {
        this.refModuleId = refModuleId;
        this.refModuleIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.REF_MODULE_ID:Coloured
     *
     * @param refModuleIdColoured the value for wf_flow_node.REF_MODULE_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setRefModuleIdColoured(boolean refModuleIdColoured) {
        this.refModuleIdColoured = refModuleIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.POSITION_X
     *
     * @return the value of wf_flow_node.POSITION_X
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getPositionX() {
        return positionX;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.POSITION_X:Coloured
     *
     * @return the value of wf_flow_node.POSITION_X:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isPositionXColoured() {
        return positionXColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.POSITION_X
     *
     * @param positionX the value for wf_flow_node.POSITION_X
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setPositionX(Long positionX) {
        this.positionX = positionX;
        this.positionXColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.POSITION_X:Coloured
     *
     * @param positionXColoured the value for wf_flow_node.POSITION_X:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setPositionXColoured(boolean positionXColoured) {
        this.positionXColoured = positionXColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.POSITION_Y
     *
     * @return the value of wf_flow_node.POSITION_Y
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getPositionY() {
        return positionY;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.POSITION_Y:Coloured
     *
     * @return the value of wf_flow_node.POSITION_Y:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isPositionYColoured() {
        return positionYColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.POSITION_Y
     *
     * @param positionY the value for wf_flow_node.POSITION_Y
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setPositionY(Long positionY) {
        this.positionY = positionY;
        this.positionYColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.POSITION_Y:Coloured
     *
     * @param positionYColoured the value for wf_flow_node.POSITION_Y:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setPositionYColoured(boolean positionYColoured) {
        this.positionYColoured = positionYColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.LAST_TASK_ID
     *
     * @return the value of wf_flow_node.LAST_TASK_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Long getLastTaskId() {
        return lastTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.LAST_TASK_ID:Coloured
     *
     * @return the value of wf_flow_node.LAST_TASK_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isLastTaskIdColoured() {
        return lastTaskIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.LAST_TASK_ID
     *
     * @param lastTaskId the value for wf_flow_node.LAST_TASK_ID
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setLastTaskId(Long lastTaskId) {
        this.lastTaskId = lastTaskId;
        this.lastTaskIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.LAST_TASK_ID:Coloured
     *
     * @param lastTaskIdColoured the value for wf_flow_node.LAST_TASK_ID:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setLastTaskIdColoured(boolean lastTaskIdColoured) {
        this.lastTaskIdColoured = lastTaskIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.WARNING_MSG
     *
     * @return the value of wf_flow_node.WARNING_MSG
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public String getWarningMsg() {
        return warningMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.WARNING_MSG:Coloured
     *
     * @return the value of wf_flow_node.WARNING_MSG:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isWarningMsgColoured() {
        return warningMsgColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.WARNING_MSG
     *
     * @param warningMsg the value for wf_flow_node.WARNING_MSG
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setWarningMsg(String warningMsg) {
        this.warningMsg = warningMsg == null ? null : warningMsg.trim();
        this.warningMsgColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.WARNING_MSG:Coloured
     *
     * @param warningMsgColoured the value for wf_flow_node.WARNING_MSG:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setWarningMsgColoured(boolean warningMsgColoured) {
        this.warningMsgColoured = warningMsgColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.NODE_STATE
     *
     * @return the value of wf_flow_node.NODE_STATE
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Integer getNodeState() {
        return nodeState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.NODE_STATE:Coloured
     *
     * @return the value of wf_flow_node.NODE_STATE:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isNodeStateColoured() {
        return nodeStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.NODE_STATE
     *
     * @param nodeState the value for wf_flow_node.NODE_STATE
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setNodeState(Integer nodeState) {
        this.nodeState = nodeState;
        this.nodeStateColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.NODE_STATE:Coloured
     *
     * @param nodeStateColoured the value for wf_flow_node.NODE_STATE:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setNodeStateColoured(boolean nodeStateColoured) {
        this.nodeStateColoured = nodeStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.SUMMARY
     *
     * @return the value of wf_flow_node.SUMMARY
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public String getSummary() {
        return summary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.SUMMARY:Coloured
     *
     * @return the value of wf_flow_node.SUMMARY:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isSummaryColoured() {
        return summaryColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.SUMMARY
     *
     * @param summary the value for wf_flow_node.SUMMARY
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setSummary(String summary) {
        this.summary = summary == null ? null : summary.trim();
        this.summaryColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.SUMMARY:Coloured
     *
     * @param summaryColoured the value for wf_flow_node.SUMMARY:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setSummaryColoured(boolean summaryColoured) {
        this.summaryColoured = summaryColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.DESCRIPTION
     *
     * @return the value of wf_flow_node.DESCRIPTION
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.DESCRIPTION:Coloured
     *
     * @return the value of wf_flow_node.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.DESCRIPTION
     *
     * @param description the value for wf_flow_node.DESCRIPTION
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for wf_flow_node.DESCRIPTION:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.STATUS
     *
     * @return the value of wf_flow_node.STATUS
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.STATUS:Coloured
     *
     * @return the value of wf_flow_node.STATUS:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.STATUS
     *
     * @param status the value for wf_flow_node.STATUS
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.STATUS:Coloured
     *
     * @param statusColoured the value for wf_flow_node.STATUS:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.LAST_UPDATE_TIME
     *
     * @return the value of wf_flow_node.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of wf_flow_node.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wf_flow_node.LAST_UPDATE_TIME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for wf_flow_node.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.LAST_UPDATE_OPER
     *
     * @return the value of wf_flow_node.LAST_UPDATE_OPER
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of wf_flow_node.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for wf_flow_node.LAST_UPDATE_OPER
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for wf_flow_node.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.CREATE_TIME
     *
     * @return the value of wf_flow_node.CREATE_TIME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.CREATE_TIME:Coloured
     *
     * @return the value of wf_flow_node.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.CREATE_TIME
     *
     * @param createTime the value for wf_flow_node.CREATE_TIME
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for wf_flow_node.CREATE_TIME:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.CREATE_OPER
     *
     * @return the value of wf_flow_node.CREATE_OPER
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_flow_node.CREATE_OPER:Coloured
     *
     * @return the value of wf_flow_node.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.CREATE_OPER
     *
     * @param createOper the value for wf_flow_node.CREATE_OPER
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_flow_node.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for wf_flow_node.CREATE_OPER:Coloured
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WfFlowNode other = (WfFlowNode) that;
        return (this.getNodeId() == null ? other.getNodeId() == null : this.getNodeId().equals(other.getNodeId()))
            && (this.getNodeName() == null ? other.getNodeName() == null : this.getNodeName().equals(other.getNodeName()))
            && (this.getOwnerProjectId() == null ? other.getOwnerProjectId() == null : this.getOwnerProjectId().equals(other.getOwnerProjectId()))
            && (this.getOwnerFlowId() == null ? other.getOwnerFlowId() == null : this.getOwnerFlowId().equals(other.getOwnerFlowId()))
            && (this.getRefModuleId() == null ? other.getRefModuleId() == null : this.getRefModuleId().equals(other.getRefModuleId()))
            && (this.getPositionX() == null ? other.getPositionX() == null : this.getPositionX().equals(other.getPositionX()))
            && (this.getPositionY() == null ? other.getPositionY() == null : this.getPositionY().equals(other.getPositionY()))
            && (this.getLastTaskId() == null ? other.getLastTaskId() == null : this.getLastTaskId().equals(other.getLastTaskId()))
            && (this.getWarningMsg() == null ? other.getWarningMsg() == null : this.getWarningMsg().equals(other.getWarningMsg()))
            && (this.getNodeState() == null ? other.getNodeState() == null : this.getNodeState().equals(other.getNodeState()))
            && (this.getSummary() == null ? other.getSummary() == null : this.getSummary().equals(other.getSummary()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNodeId() == null) ? 0 : getNodeId().hashCode());
        result = prime * result + ((getNodeName() == null) ? 0 : getNodeName().hashCode());
        result = prime * result + ((getOwnerProjectId() == null) ? 0 : getOwnerProjectId().hashCode());
        result = prime * result + ((getOwnerFlowId() == null) ? 0 : getOwnerFlowId().hashCode());
        result = prime * result + ((getRefModuleId() == null) ? 0 : getRefModuleId().hashCode());
        result = prime * result + ((getPositionX() == null) ? 0 : getPositionX().hashCode());
        result = prime * result + ((getPositionY() == null) ? 0 : getPositionY().hashCode());
        result = prime * result + ((getLastTaskId() == null) ? 0 : getLastTaskId().hashCode());
        result = prime * result + ((getWarningMsg() == null) ? 0 : getWarningMsg().hashCode());
        result = prime * result + ((getNodeState() == null) ? 0 : getNodeState().hashCode());
        result = prime * result + ((getSummary() == null) ? 0 : getSummary().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    @Override
    public void copyProperties(Object that) {
        if (this == that || that == null || this.getClass() != that.getClass() ) {
            return;
        }
        WfFlowNode other = (WfFlowNode) that;
        if(other.isNodeIdColoured() ) {this.setNodeId(other.getNodeId() );}
        if(other.isNodeNameColoured() ) {this.setNodeName(other.getNodeName() );}
        if(other.isOwnerProjectIdColoured() ) {this.setOwnerProjectId(other.getOwnerProjectId() );}
        if(other.isOwnerFlowIdColoured() ) {this.setOwnerFlowId(other.getOwnerFlowId() );}
        if(other.isRefModuleIdColoured() ) {this.setRefModuleId(other.getRefModuleId() );}
        if(other.isPositionXColoured() ) {this.setPositionX(other.getPositionX() );}
        if(other.isPositionYColoured() ) {this.setPositionY(other.getPositionY() );}
        if(other.isLastTaskIdColoured() ) {this.setLastTaskId(other.getLastTaskId() );}
        if(other.isWarningMsgColoured() ) {this.setWarningMsg(other.getWarningMsg() );}
        if(other.isNodeStateColoured() ) {this.setNodeState(other.getNodeState() );}
        if(other.isSummaryColoured() ) {this.setSummary(other.getSummary() );}
        if(other.isDescriptionColoured() ) {this.setDescription(other.getDescription() );}
        if(other.isStatusColoured() ) {this.setStatus(other.getStatus() );}
        if(other.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(other.getLastUpdateTime() );}
        if(other.isLastUpdateOperColoured() ) {this.setLastUpdateOper(other.getLastUpdateOper() );}
        if(other.isCreateTimeColoured() ) {this.setCreateTime(other.getCreateTime() );}
        if(other.isCreateOperColoured() ) {this.setCreateOper(other.getCreateOper() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    @Override
    public JSONObject toJSON() {
        HashMap<String, Object> hashMap = new HashMap();
        if(this.nodeIdColoured) {hashMap.put("nodeId", this.nodeId);}
        if(this.nodeNameColoured) {hashMap.put("nodeName", this.nodeName);}
        if(this.ownerProjectIdColoured) {hashMap.put("ownerProjectId", this.ownerProjectId);}
        if(this.ownerFlowIdColoured) {hashMap.put("ownerFlowId", this.ownerFlowId);}
        if(this.refModuleIdColoured) {hashMap.put("refModuleId", this.refModuleId);}
        if(this.positionXColoured) {hashMap.put("positionX", this.positionX);}
        if(this.positionYColoured) {hashMap.put("positionY", this.positionY);}
        if(this.lastTaskIdColoured) {hashMap.put("lastTaskId", this.lastTaskId);}
        if(this.warningMsgColoured) {hashMap.put("warningMsg", this.warningMsg);}
        if(this.nodeStateColoured) {hashMap.put("nodeState", this.nodeState);}
        if(this.summaryColoured) {hashMap.put("summary", this.summary);}
        if(this.descriptionColoured) {hashMap.put("description", this.description);}
        if(this.statusColoured) {hashMap.put("status", this.status);}
        if(this.lastUpdateTimeColoured) {hashMap.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOperColoured) {hashMap.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTimeColoured) {hashMap.put("createTime", this.createTime);}
        if(this.createOperColoured) {hashMap.put("createOper", this.createOper);}
        return (JSONObject) JSON.toJSON(hashMap);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_flow_node
     *
     * @mbg.generated Tue Dec 04 08:41:08 CST 2018
     */
    @Override
    public void clear() {
        if(this.nodeIdColoured) {this.nodeId = null; this.nodeIdColoured = false;}
        if(this.nodeNameColoured) {this.nodeName = null; this.nodeNameColoured = false;}
        if(this.ownerProjectIdColoured) {this.ownerProjectId = null; this.ownerProjectIdColoured = false;}
        if(this.ownerFlowIdColoured) {this.ownerFlowId = null; this.ownerFlowIdColoured = false;}
        if(this.refModuleIdColoured) {this.refModuleId = null; this.refModuleIdColoured = false;}
        if(this.positionXColoured) {this.positionX = null; this.positionXColoured = false;}
        if(this.positionYColoured) {this.positionY = null; this.positionYColoured = false;}
        if(this.lastTaskIdColoured) {this.lastTaskId = null; this.lastTaskIdColoured = false;}
        if(this.warningMsgColoured) {this.warningMsg = null; this.warningMsgColoured = false;}
        if(this.nodeStateColoured) {this.nodeState = null; this.nodeStateColoured = false;}
        if(this.summaryColoured) {this.summary = null; this.summaryColoured = false;}
        if(this.descriptionColoured) {this.description = null; this.descriptionColoured = false;}
        if(this.statusColoured) {this.status = null; this.statusColoured = false;}
        if(this.lastUpdateTimeColoured) {this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;}
        if(this.lastUpdateOperColoured) {this.lastUpdateOper = null; this.lastUpdateOperColoured = false;}
        if(this.createTimeColoured) {this.createTime = null; this.createTimeColoured = false;}
        if(this.createOperColoured) {this.createOper = null; this.createOperColoured = false;}
        return;
    }
}