package com.yatop.lambda.base.model;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;
import com.yatop.lambda.base.utils.LambdaRootModel;
import java.io.Serializable;
import java.util.Date;
import java.util.HashMap;

public class WfSnapshot extends LambdaRootModel implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.SNAPSHOT_ID
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private Long snapshotId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.SNAPSHOT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean snapshotIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.SNAPSHOT_NAME
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private String snapshotName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.SNAPSHOT_NAME:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean snapshotNameColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.SHAPSHOT_SRC
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private Integer shapshotSrc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.SHAPSHOT_SRC:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean shapshotSrcColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.OWNER_PROJECT_ID
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private Long ownerProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean ownerProjectIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.OWNER_FLOW_ID
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private Long ownerFlowId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.OWNER_FLOW_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean ownerFlowIdColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.SNAPSHOT_VERSION
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private Long snapshotVersion;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.SNAPSHOT_VERSION:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean snapshotVersionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.SNAPSHOT_STATE
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private Integer snapshotState;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.SNAPSHOT_STATE:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean snapshotStateColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.DESCRIPTION
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.DESCRIPTION:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean descriptionColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.STATUS
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.STATUS:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean statusColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private Date lastUpdateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean lastUpdateTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.LAST_UPDATE_OPER
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private String lastUpdateOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean lastUpdateOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.CREATE_TIME
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.CREATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean createTimeColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.CREATE_OPER
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private String createOper;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.CREATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean createOperColoured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.SNAPSHOT_CONTENT
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private String snapshotContent;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wf_snapshot.SNAPSHOT_CONTENT:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private boolean snapshotContentColoured;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wf_snapshot
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.SNAPSHOT_ID
     *
     * @return the value of wf_snapshot.SNAPSHOT_ID
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public Long getSnapshotId() {
        return snapshotId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.SNAPSHOT_ID:Coloured
     *
     * @return the value of wf_snapshot.SNAPSHOT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isSnapshotIdColoured() {
        return snapshotIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.SNAPSHOT_ID
     *
     * @param snapshotId the value for wf_snapshot.SNAPSHOT_ID
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setSnapshotId(Long snapshotId) {
        this.snapshotId = snapshotId;
        this.snapshotIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.SNAPSHOT_ID:Coloured
     *
     * @param snapshotIdColoured the value for wf_snapshot.SNAPSHOT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setSnapshotIdColoured(boolean snapshotIdColoured) {
        this.snapshotIdColoured = snapshotIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.SNAPSHOT_NAME
     *
     * @return the value of wf_snapshot.SNAPSHOT_NAME
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public String getSnapshotName() {
        return snapshotName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.SNAPSHOT_NAME:Coloured
     *
     * @return the value of wf_snapshot.SNAPSHOT_NAME:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isSnapshotNameColoured() {
        return snapshotNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.SNAPSHOT_NAME
     *
     * @param snapshotName the value for wf_snapshot.SNAPSHOT_NAME
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setSnapshotName(String snapshotName) {
        this.snapshotName = snapshotName == null ? null : snapshotName.trim();
        this.snapshotNameColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.SNAPSHOT_NAME:Coloured
     *
     * @param snapshotNameColoured the value for wf_snapshot.SNAPSHOT_NAME:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setSnapshotNameColoured(boolean snapshotNameColoured) {
        this.snapshotNameColoured = snapshotNameColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.SHAPSHOT_SRC
     *
     * @return the value of wf_snapshot.SHAPSHOT_SRC
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public Integer getShapshotSrc() {
        return shapshotSrc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.SHAPSHOT_SRC:Coloured
     *
     * @return the value of wf_snapshot.SHAPSHOT_SRC:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isShapshotSrcColoured() {
        return shapshotSrcColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.SHAPSHOT_SRC
     *
     * @param shapshotSrc the value for wf_snapshot.SHAPSHOT_SRC
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setShapshotSrc(Integer shapshotSrc) {
        this.shapshotSrc = shapshotSrc;
        this.shapshotSrcColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.SHAPSHOT_SRC:Coloured
     *
     * @param shapshotSrcColoured the value for wf_snapshot.SHAPSHOT_SRC:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setShapshotSrcColoured(boolean shapshotSrcColoured) {
        this.shapshotSrcColoured = shapshotSrcColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.OWNER_PROJECT_ID
     *
     * @return the value of wf_snapshot.OWNER_PROJECT_ID
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public Long getOwnerProjectId() {
        return ownerProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.OWNER_PROJECT_ID:Coloured
     *
     * @return the value of wf_snapshot.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isOwnerProjectIdColoured() {
        return ownerProjectIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.OWNER_PROJECT_ID
     *
     * @param ownerProjectId the value for wf_snapshot.OWNER_PROJECT_ID
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setOwnerProjectId(Long ownerProjectId) {
        this.ownerProjectId = ownerProjectId;
        this.ownerProjectIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.OWNER_PROJECT_ID:Coloured
     *
     * @param ownerProjectIdColoured the value for wf_snapshot.OWNER_PROJECT_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setOwnerProjectIdColoured(boolean ownerProjectIdColoured) {
        this.ownerProjectIdColoured = ownerProjectIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.OWNER_FLOW_ID
     *
     * @return the value of wf_snapshot.OWNER_FLOW_ID
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public Long getOwnerFlowId() {
        return ownerFlowId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.OWNER_FLOW_ID:Coloured
     *
     * @return the value of wf_snapshot.OWNER_FLOW_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isOwnerFlowIdColoured() {
        return ownerFlowIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.OWNER_FLOW_ID
     *
     * @param ownerFlowId the value for wf_snapshot.OWNER_FLOW_ID
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setOwnerFlowId(Long ownerFlowId) {
        this.ownerFlowId = ownerFlowId;
        this.ownerFlowIdColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.OWNER_FLOW_ID:Coloured
     *
     * @param ownerFlowIdColoured the value for wf_snapshot.OWNER_FLOW_ID:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setOwnerFlowIdColoured(boolean ownerFlowIdColoured) {
        this.ownerFlowIdColoured = ownerFlowIdColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.SNAPSHOT_VERSION
     *
     * @return the value of wf_snapshot.SNAPSHOT_VERSION
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public Long getSnapshotVersion() {
        return snapshotVersion;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.SNAPSHOT_VERSION:Coloured
     *
     * @return the value of wf_snapshot.SNAPSHOT_VERSION:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isSnapshotVersionColoured() {
        return snapshotVersionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.SNAPSHOT_VERSION
     *
     * @param snapshotVersion the value for wf_snapshot.SNAPSHOT_VERSION
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setSnapshotVersion(Long snapshotVersion) {
        this.snapshotVersion = snapshotVersion;
        this.snapshotVersionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.SNAPSHOT_VERSION:Coloured
     *
     * @param snapshotVersionColoured the value for wf_snapshot.SNAPSHOT_VERSION:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setSnapshotVersionColoured(boolean snapshotVersionColoured) {
        this.snapshotVersionColoured = snapshotVersionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.SNAPSHOT_STATE
     *
     * @return the value of wf_snapshot.SNAPSHOT_STATE
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public Integer getSnapshotState() {
        return snapshotState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.SNAPSHOT_STATE:Coloured
     *
     * @return the value of wf_snapshot.SNAPSHOT_STATE:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isSnapshotStateColoured() {
        return snapshotStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.SNAPSHOT_STATE
     *
     * @param snapshotState the value for wf_snapshot.SNAPSHOT_STATE
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setSnapshotState(Integer snapshotState) {
        this.snapshotState = snapshotState;
        this.snapshotStateColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.SNAPSHOT_STATE:Coloured
     *
     * @param snapshotStateColoured the value for wf_snapshot.SNAPSHOT_STATE:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setSnapshotStateColoured(boolean snapshotStateColoured) {
        this.snapshotStateColoured = snapshotStateColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.DESCRIPTION
     *
     * @return the value of wf_snapshot.DESCRIPTION
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.DESCRIPTION:Coloured
     *
     * @return the value of wf_snapshot.DESCRIPTION:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isDescriptionColoured() {
        return descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.DESCRIPTION
     *
     * @param description the value for wf_snapshot.DESCRIPTION
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
        this.descriptionColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.DESCRIPTION:Coloured
     *
     * @param descriptionColoured the value for wf_snapshot.DESCRIPTION:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setDescriptionColoured(boolean descriptionColoured) {
        this.descriptionColoured = descriptionColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.STATUS
     *
     * @return the value of wf_snapshot.STATUS
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.STATUS:Coloured
     *
     * @return the value of wf_snapshot.STATUS:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isStatusColoured() {
        return statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.STATUS
     *
     * @param status the value for wf_snapshot.STATUS
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setStatus(Integer status) {
        this.status = status;
        this.statusColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.STATUS:Coloured
     *
     * @param statusColoured the value for wf_snapshot.STATUS:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setStatusColoured(boolean statusColoured) {
        this.statusColoured = statusColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.LAST_UPDATE_TIME
     *
     * @return the value of wf_snapshot.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public Date getLastUpdateTime() {
        return lastUpdateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.LAST_UPDATE_TIME:Coloured
     *
     * @return the value of wf_snapshot.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isLastUpdateTimeColoured() {
        return lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.LAST_UPDATE_TIME
     *
     * @param lastUpdateTime the value for wf_snapshot.LAST_UPDATE_TIME
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setLastUpdateTime(Date lastUpdateTime) {
        this.lastUpdateTime = lastUpdateTime;
        this.lastUpdateTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.LAST_UPDATE_TIME:Coloured
     *
     * @param lastUpdateTimeColoured the value for wf_snapshot.LAST_UPDATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setLastUpdateTimeColoured(boolean lastUpdateTimeColoured) {
        this.lastUpdateTimeColoured = lastUpdateTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.LAST_UPDATE_OPER
     *
     * @return the value of wf_snapshot.LAST_UPDATE_OPER
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public String getLastUpdateOper() {
        return lastUpdateOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.LAST_UPDATE_OPER:Coloured
     *
     * @return the value of wf_snapshot.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isLastUpdateOperColoured() {
        return lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.LAST_UPDATE_OPER
     *
     * @param lastUpdateOper the value for wf_snapshot.LAST_UPDATE_OPER
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setLastUpdateOper(String lastUpdateOper) {
        this.lastUpdateOper = lastUpdateOper == null ? null : lastUpdateOper.trim();
        this.lastUpdateOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.LAST_UPDATE_OPER:Coloured
     *
     * @param lastUpdateOperColoured the value for wf_snapshot.LAST_UPDATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setLastUpdateOperColoured(boolean lastUpdateOperColoured) {
        this.lastUpdateOperColoured = lastUpdateOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.CREATE_TIME
     *
     * @return the value of wf_snapshot.CREATE_TIME
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.CREATE_TIME:Coloured
     *
     * @return the value of wf_snapshot.CREATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isCreateTimeColoured() {
        return createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.CREATE_TIME
     *
     * @param createTime the value for wf_snapshot.CREATE_TIME
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
        this.createTimeColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.CREATE_TIME:Coloured
     *
     * @param createTimeColoured the value for wf_snapshot.CREATE_TIME:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setCreateTimeColoured(boolean createTimeColoured) {
        this.createTimeColoured = createTimeColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.CREATE_OPER
     *
     * @return the value of wf_snapshot.CREATE_OPER
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public String getCreateOper() {
        return createOper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.CREATE_OPER:Coloured
     *
     * @return the value of wf_snapshot.CREATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isCreateOperColoured() {
        return createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.CREATE_OPER
     *
     * @param createOper the value for wf_snapshot.CREATE_OPER
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setCreateOper(String createOper) {
        this.createOper = createOper == null ? null : createOper.trim();
        this.createOperColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.CREATE_OPER:Coloured
     *
     * @param createOperColoured the value for wf_snapshot.CREATE_OPER:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setCreateOperColoured(boolean createOperColoured) {
        this.createOperColoured = createOperColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.SNAPSHOT_CONTENT
     *
     * @return the value of wf_snapshot.SNAPSHOT_CONTENT
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public String getSnapshotContent() {
        return snapshotContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wf_snapshot.SNAPSHOT_CONTENT:Coloured
     *
     * @return the value of wf_snapshot.SNAPSHOT_CONTENT:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public boolean isSnapshotContentColoured() {
        return snapshotContentColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.SNAPSHOT_CONTENT
     *
     * @param snapshotContent the value for wf_snapshot.SNAPSHOT_CONTENT
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setSnapshotContent(String snapshotContent) {
        this.snapshotContent = snapshotContent == null ? null : snapshotContent.trim();
        this.snapshotContentColoured = true;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wf_snapshot.SNAPSHOT_CONTENT:Coloured
     *
     * @param snapshotContentColoured the value for wf_snapshot.SNAPSHOT_CONTENT:Coloured
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    public void setSnapshotContentColoured(boolean snapshotContentColoured) {
        this.snapshotContentColoured = snapshotContentColoured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        WfSnapshot other = (WfSnapshot) that;
        return (this.getSnapshotId() == null ? other.getSnapshotId() == null : this.getSnapshotId().equals(other.getSnapshotId()))
            && (this.getSnapshotName() == null ? other.getSnapshotName() == null : this.getSnapshotName().equals(other.getSnapshotName()))
            && (this.getShapshotSrc() == null ? other.getShapshotSrc() == null : this.getShapshotSrc().equals(other.getShapshotSrc()))
            && (this.getOwnerProjectId() == null ? other.getOwnerProjectId() == null : this.getOwnerProjectId().equals(other.getOwnerProjectId()))
            && (this.getOwnerFlowId() == null ? other.getOwnerFlowId() == null : this.getOwnerFlowId().equals(other.getOwnerFlowId()))
            && (this.getSnapshotVersion() == null ? other.getSnapshotVersion() == null : this.getSnapshotVersion().equals(other.getSnapshotVersion()))
            && (this.getSnapshotState() == null ? other.getSnapshotState() == null : this.getSnapshotState().equals(other.getSnapshotState()))
            && (this.getDescription() == null ? other.getDescription() == null : this.getDescription().equals(other.getDescription()))
            && (this.getStatus() == null ? other.getStatus() == null : this.getStatus().equals(other.getStatus()))
            && (this.getLastUpdateTime() == null ? other.getLastUpdateTime() == null : this.getLastUpdateTime().equals(other.getLastUpdateTime()))
            && (this.getLastUpdateOper() == null ? other.getLastUpdateOper() == null : this.getLastUpdateOper().equals(other.getLastUpdateOper()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getCreateOper() == null ? other.getCreateOper() == null : this.getCreateOper().equals(other.getCreateOper()))
            && (this.getSnapshotContent() == null ? other.getSnapshotContent() == null : this.getSnapshotContent().equals(other.getSnapshotContent()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getSnapshotId() == null) ? 0 : getSnapshotId().hashCode());
        result = prime * result + ((getSnapshotName() == null) ? 0 : getSnapshotName().hashCode());
        result = prime * result + ((getShapshotSrc() == null) ? 0 : getShapshotSrc().hashCode());
        result = prime * result + ((getOwnerProjectId() == null) ? 0 : getOwnerProjectId().hashCode());
        result = prime * result + ((getOwnerFlowId() == null) ? 0 : getOwnerFlowId().hashCode());
        result = prime * result + ((getSnapshotVersion() == null) ? 0 : getSnapshotVersion().hashCode());
        result = prime * result + ((getSnapshotState() == null) ? 0 : getSnapshotState().hashCode());
        result = prime * result + ((getDescription() == null) ? 0 : getDescription().hashCode());
        result = prime * result + ((getStatus() == null) ? 0 : getStatus().hashCode());
        result = prime * result + ((getLastUpdateTime() == null) ? 0 : getLastUpdateTime().hashCode());
        result = prime * result + ((getLastUpdateOper() == null) ? 0 : getLastUpdateOper().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getCreateOper() == null) ? 0 : getCreateOper().hashCode());
        result = prime * result + ((getSnapshotContent() == null) ? 0 : getSnapshotContent().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    @Override
    public void copyProperties(Object that) {
        if (this == that || that == null || this.getClass() != that.getClass() ) {
            return;
        }
        WfSnapshot other = (WfSnapshot) that;
        if(other.isSnapshotIdColoured() ) {this.setSnapshotId(other.getSnapshotId() );}
        if(other.isSnapshotNameColoured() ) {this.setSnapshotName(other.getSnapshotName() );}
        if(other.isShapshotSrcColoured() ) {this.setShapshotSrc(other.getShapshotSrc() );}
        if(other.isOwnerProjectIdColoured() ) {this.setOwnerProjectId(other.getOwnerProjectId() );}
        if(other.isOwnerFlowIdColoured() ) {this.setOwnerFlowId(other.getOwnerFlowId() );}
        if(other.isSnapshotVersionColoured() ) {this.setSnapshotVersion(other.getSnapshotVersion() );}
        if(other.isSnapshotStateColoured() ) {this.setSnapshotState(other.getSnapshotState() );}
        if(other.isDescriptionColoured() ) {this.setDescription(other.getDescription() );}
        if(other.isStatusColoured() ) {this.setStatus(other.getStatus() );}
        if(other.isLastUpdateTimeColoured() ) {this.setLastUpdateTime(other.getLastUpdateTime() );}
        if(other.isLastUpdateOperColoured() ) {this.setLastUpdateOper(other.getLastUpdateOper() );}
        if(other.isCreateTimeColoured() ) {this.setCreateTime(other.getCreateTime() );}
        if(other.isCreateOperColoured() ) {this.setCreateOper(other.getCreateOper() );}
        if(other.isSnapshotContentColoured() ) {this.setSnapshotContent(other.getSnapshotContent() );}
        return;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    @Override
    public JSONObject toJSON() {
        HashMap<String, Object> hashMap = new HashMap();
        if(this.snapshotIdColoured) {hashMap.put("snapshotId", this.snapshotId);}
        if(this.snapshotNameColoured) {hashMap.put("snapshotName", this.snapshotName);}
        if(this.shapshotSrcColoured) {hashMap.put("shapshotSrc", this.shapshotSrc);}
        if(this.ownerProjectIdColoured) {hashMap.put("ownerProjectId", this.ownerProjectId);}
        if(this.ownerFlowIdColoured) {hashMap.put("ownerFlowId", this.ownerFlowId);}
        if(this.snapshotVersionColoured) {hashMap.put("snapshotVersion", this.snapshotVersion);}
        if(this.snapshotStateColoured) {hashMap.put("snapshotState", this.snapshotState);}
        if(this.descriptionColoured) {hashMap.put("description", this.description);}
        if(this.statusColoured) {hashMap.put("status", this.status);}
        if(this.lastUpdateTimeColoured) {hashMap.put("lastUpdateTime", this.lastUpdateTime);}
        if(this.lastUpdateOperColoured) {hashMap.put("lastUpdateOper", this.lastUpdateOper);}
        if(this.createTimeColoured) {hashMap.put("createTime", this.createTime);}
        if(this.createOperColoured) {hashMap.put("createOper", this.createOper);}
        if(this.snapshotContentColoured) {hashMap.put("snapshotContent", this.snapshotContent);}
        return (JSONObject) JSON.toJSON(hashMap);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wf_snapshot
     *
     * @mbg.generated Wed Dec 05 11:19:48 CST 2018
     */
    @Override
    public void clear() {
        if(this.snapshotIdColoured) {this.snapshotId = null; this.snapshotIdColoured = false;}
        if(this.snapshotNameColoured) {this.snapshotName = null; this.snapshotNameColoured = false;}
        if(this.shapshotSrcColoured) {this.shapshotSrc = null; this.shapshotSrcColoured = false;}
        if(this.ownerProjectIdColoured) {this.ownerProjectId = null; this.ownerProjectIdColoured = false;}
        if(this.ownerFlowIdColoured) {this.ownerFlowId = null; this.ownerFlowIdColoured = false;}
        if(this.snapshotVersionColoured) {this.snapshotVersion = null; this.snapshotVersionColoured = false;}
        if(this.snapshotStateColoured) {this.snapshotState = null; this.snapshotStateColoured = false;}
        if(this.descriptionColoured) {this.description = null; this.descriptionColoured = false;}
        if(this.statusColoured) {this.status = null; this.statusColoured = false;}
        if(this.lastUpdateTimeColoured) {this.lastUpdateTime = null; this.lastUpdateTimeColoured = false;}
        if(this.lastUpdateOperColoured) {this.lastUpdateOper = null; this.lastUpdateOperColoured = false;}
        if(this.createTimeColoured) {this.createTime = null; this.createTimeColoured = false;}
        if(this.createOperColoured) {this.createOper = null; this.createOperColoured = false;}
        if(this.snapshotContentColoured) {this.snapshotContent = null; this.snapshotContentColoured = false;}
        return;
    }
}