
lambda.mls.jdbc:
  type: mysql #数据库类型
  driverClassName: com.mysql.jdbc.Driver
  maximumPoolSize: 10
  url: jdbc:mysql://127.0.0.1:3306/lambda_mls?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useAffectedRows=true
  username: root
  password: root
  connectionTestQuery: SELECT 1 #由于采用HikiriCP，用于检测数据库连接是否存活。

##############################################################
#### 日志级别配置
##############################################################
logging.file: logs/lambda-mls.log
logging.level.org.apache.hadoop.yarn.client.RMProxy: WARN
logging.level.cn.com.bsfit.portal.mapper: INFO
logging.level.com.atomikos: INFO
logging.level.org.apache.parquet.hadoop.ColumnChunkPageWriteStore: WARN
logging.level.org.apache.parquet.hadoop.InternalParquetRecordWriter: WARN
logging.level.org.apache.parquet.hadoop.InternalParquetRecordReader : WARN
logging.level.org.apache.parquet.hadoop.ParquetFileReader : WARN
logging.level.org.apache.spark.deploy.yarn.Client: WARN
logging.level.org.apache.spark.SecurityManager : WARN

###############################################################
#### tomcat配置
###############################################################
server.session-timeout: 3600
spring.http.multipart.maxRequestSize: 5001Mb
spring.http.multipart.maxFileSize: 5000Mb
server.tomcat.compression: 1024
server.tomcat.compressableMimeTypes: application/json,application/xml,application/javascript,text/html,text/xml,text/plain

## 缓存版本号
spring.resources.chain.strategy.content.enabled: true
spring.resources.chain.strategy.content.paths:
